### ISSUE TITLE
[Ubuntu] Show/hide on tray icon click doesn't work

### ISSUE THREAD

**Issue by keunes** [gyunaev/birdtray#103]
**OS**: Ubuntu 18.04.2 LTS
**Birdtray version**: 1.6 compiled at May 21 2019 09:33:39
**Thunderbird version**: 60.7.0
**Birdtray origin**: From [PPA](https://launchpad.net/~linuxuprising/+archive/ubuntu/apps)
**Qt version**: _NA_ 

**Description**
Clicking on the tray icon opens a menu
![Screenshot from 2019-06-20 23-29-44](https://user-images.githubusercontent.com/11229646/59882760-66860900-93b3-11e9-84b6-aa6ab0813fb7.png)

**Expected behavior**
Clicking on the tray, opens/closes Thunderbird. "Hide/show Thunderbird window when clicking on tray icon" is enabled in the settings.

**Comment by gyunaev** [comment]
Does it happen on a new fresh install with no configuration? For example, if you create a new user on your machine, login using this user and run Thunderbird, do you see the same behavior?

**Comment by keunes** [comment]
Just tested it, and yes, it has the same behaviour.

**Comment by gyunaev** [comment]
Same behavior for left-click and right-click on icon?

**Comment by keunes** [comment]
Yup

**Comment by Abestanis** [comment]
According to [this SO answer](https://stackoverflow.com/a/32912816) it is actually not possible to detect a left or right click of the tray icon on Ubuntu.

**Comment by keunes** [comment]
Hmm, I never realised. If that's the case still today, I think I would prefer a 'click = open Thunderbird' (like [caffeine](https://github.com/eonpatapon/gnome-shell-extension-caffeine) does) rather than 'click = open menu'. I imagine however that that's not true for everyone, so maybe a new setting could be introduced.

**Comment by Abestanis** [comment]
I don't think that will be possible. From what I read online and my testing, Birdtray is simply not notified, when the user clicks the tray icon, so we can't decide between whether to show the menu or activate Thunderbird. It looks like the Unity desktop will always open the menu and there is no way to change that.

The program you linked seems to be a GNOME extension, so I assume it only works on the GNOME desktop? I'm guessing the GNOME desktop does not have this issue and it is specific to the Unity desktop used in newer versions of Ubuntu.

It might be possible to work around the issue with a *hack*: Create an invisible, frameless window over the tray icon and intercept the clicks. But in my opinion, this would be a lot of work for very little benefit. @gyunaev would have to decide on this.

**Comment by gyunaev** [comment]
Switching to "click-open Thunderbird" would mean there is no way to access its menu. For Caffeine it works because it opens Caffeine's own window. But if click opens Thunderbird, how one would access its menu?

I don't think the hack is a good idea for several reasons; one is that it would violate the way UI designers idea how to use their UI. Especially if they went as far in enforcing it as patching Qt. Closing.
