### ISSUE TITLE
[FR] Gnome extension

### ISSUE THREAD

**Issue by keunes** [gyunaev/birdtray#104]
No clue as to whether it's feasible or possible at all, but it would be great if this piece of software were available as a Gnome Extension.

**Comment by gyunaev** [comment]
Unfortunately this would require rewriting it in GTK. The source code would change so much that it would be a totally separated project then. Volunteers are welcome :)

**Comment by keunes** [comment]
That's too bad :/

**Comment by keunes** [comment]
But thanks for making it, either way :)
