### ISSUE TITLE
Nothing happens when clicking on 'New email'

### ISSUE THREAD

**Issue by keunes** [gyunaev/birdtray#106]
**OS**: Ubuntu 18.04.2 LTS
**Birdtray version**: 1.6 compiled at May 21 2019 09:33:39
**Thunderbird version**: 60.7.0
**Birdtray origin**: From [PPA](https://launchpad.net/~linuxuprising/+archive/ubuntu/apps)
**Qt version**: _NA_ 

**Description**
When the 'Enable New Email submenu' is enabled from the settings, a nice menu item appears. However, clicking on the menu entry doesn't do anything (menu closes).
![Screenshot from 2019-06-21 00-14-05](https://user-images.githubusercontent.com/11229646/59884848-c2539080-93b9-11e9-8587-e97fda8ce0f4.png)

**Expected behavior**
Open a blank email composition window.

**Comment by gyunaev** [comment]
It should launch thunderbird; if it cannot launch it, nothing would happen.

**Comment by keunes** [comment]
Ok, thank you. Then that's a bug indeed.

**Comment by geckolinux** [comment]
Thanks  very much, https://github.com/gyunaev/birdtray/commit/5d8cf3a42826d2645d0c31ff5d8c79790a1bb910 fixed the issue for me on openSUSE Tumbleweed with Plasma.
