### ISSUE TITLE
Notification colour setting not respected

### ISSUE THREAD

**Issue by keunes** [gyunaev/birdtray#107]
**OS**: Ubuntu 18.04.2 LTS
**Birdtray version**: 1.6 compiled at May 21 2019 09:33:39
**Thunderbird version**: 60.7.0
**Birdtray origin**: From [PPA](https://launchpad.net/~linuxuprising/+archive/ubuntu/apps)
**Qt version**: _NA_ 

**Description**
The notification colour as set in the General settings is not respected. It seems to me that it's overwritten by the colour set for each Mork index file. As a user, that's a bit confusing. Rather, I would remove either of the colour settings (or transfer the 'general' one to monitoring one, visible when 'global search database' is selected).

**Expected behavior**
When I change the colour in General tab of the settings, it is applied to the notification.

**On a side-note:** Additionally, the colour changes (like other changes, it seems) aren't applied instantly, maybe an 'apply' button would be nice (if instant application isn't possible/feasible).

**Additional comment**
Last comment for tonight, sorry for the flood of new issues. Thanks for making this though, great to have!

**Comment by gyunaev** [comment]
Generally after changing any settings you need to restart the app to make sure they are taken into account. I'll leave it open in case someone wants to fix it though.

**Comment by keunes** [comment]
> Generally after changing any settings you need to restart the app to make sure they are taken into account.

That was the side comment, sorry if it wasn't clear. My main point was that regardless what colour you set in the 'General' tab of the settings, it gets ignored. (I think only if you have the 'Mork' file option, which is the default)

**Comment by gyunaev** [comment]
This was incorrect name for this setting; in fact it is only used when more than one account has emails.

**Comment by keunes** [comment]
Ahh, I get it. Thanks.
