### ISSUE TITLE
Enhancement request: add ability to show hidden files to Monitoring tab file browser

### ISSUE THREAD

**Issue by jaym61** [gyunaev/birdtray#109]
**OS**: MX Linux 18.3
**Birdtray version**: Currently 1.5.1. I also compiled 1.6.0 from source and have the same issue.
**Thunderbird version**: 60.7.2
**Birdtray origin**: 1.5.1: from distro's package manager. 1.6.0: from source
**Qt version**: 5.7.1

**Description**
Settings/Monitor tab/Browse can't view or open thunderbird's hidden directory inside $HOME which is where Inbox.msf is located. (within the default Thunderbird profile.) Example:
/home/jay/.thunderbird/672hrtdy.default/Mail/pop.MyEmailProvider.com/Inbox.msf

**Expected behavior**
Expected a button or other option to allow me to show and access hidden files and directories, or that hidden files and directories be always shown.

**Work-around**
Browse to the Inbox.msf file in the Linux distro's file manager, right-click on it and Copy, then in birdtray right-click and paste in the "Folder:" field instead of clicking the Browse button.

**To Reproduce**
1. Right-click the birdtray tray icon
2. Select Settings
3. Select Monitoring tab
4. Click Add
5. Click Browse

**Screenshots**
https://ibb.co/f2fSJWG

**Comment by jaym61** [comment]
This is my first time using GitHub and I don't know how to change the label from Bug to Enhancement, sorry.

**Comment by gyunaev** [comment]
Try to replace the  DialogAddEditAccount::browse() with the following:

```
void DialogAddEditAccount::browse()
{
    QFileDialog fd;
    fd.setFilter( QDir::AllDirs | QDir::Drives | QDir::Hidden );

    QString e = fd.getOpenFileName(
            0, "Choose the MSF file", Utils::expandPath(THUNDERBIRD_PROFILES_PATH),
            "Mail Index (*.msf)" );

    if ( e.isEmpty() )
        return;

    leFolderPath->setText( e );
}
```
and let us know if the files are shown.
Alternatively, this may be controlled by your file dialog itself (i.e. there is an option in file dialog to show hidden files - this is the case with KDE and cannot be controlled from Qt).

**Comment by jaym61** [comment]
No change after editing dialogaddeditaccount.cpp and replacing the void DialogAddEditAccount::browse() section of code with the above, running make clean, then qmake and make again.

> Alternatively, this may be controlled by your file dialog itself (i.e. there is an option in file dialog to show hidden files - this is the case with KDE and cannot be controlled from Qt).

 I have Xfce version 4.12.3. Does it disallow showing a hidden file option in QT file dialogue boxes?

**Comment by gyunaev** [comment]
I'm unsure about it. Do you see hidden files in any other dialogs (i.e. Thunderbird Open -> Saved Message menu)?

**Comment by Abestanis** [comment]
With the addition of the advanced `AddMailAccountDialog` in #145 and the improvements in #239 it is no longer needed to view hidden files for the typical user. There was also no feedback for half a year, I think we can close this @gyunaev.

**Comment by gyunaev** [comment]
Please provide the feedback whether the latest code fixes this issue, thanks!
