### ISSUE TITLE
Show all new mail

### ISSUE THREAD

**Issue by baconsalad** [gyunaev/birdtray#11]
Instead of selecting all individual account/folders can you have something like user@account/* or even default to show all unread mail?

Thank you for making this. After firetray became obsolete I have been searching forever for a replacement.

**Comment by gyunaev** [comment]
Could you please explain what is the use case to show unread mail in non-Inbox folder? The only one I can think about is when automatic filters are used to move mail to different folders, but in this case wouldn't you like different notification color for each of such folders?

Also note that when you create a new mail, it is shown as unread in Drafts. And if you delete spam right away, it will be "unread" in your trash (although TB suppresses this). Would you want those count toward unread as well?

**Comment by baconsalad** [comment]
Yeah that's my situation, lots of filters/folders. It's no big deal I can just add everything manually.

**Comment by gyunaev** [comment]
Inbox would match inbox$ regexp, and thus would not match subfolders.

But I'll think of a way to add monitoring folders easier.

**Comment by AGCaesar** [comment]
Why not just match INBOX without the end of line $
Then everything should be matched?

**Comment by gyunaev** [comment]
archive/inbox-2015 too?

**Comment by gyunaev** [comment]
Shall be fixed by #21
