### ISSUE TITLE
Works great with Thunderbird 69.0 Beta!

### ISSUE THREAD

**Issue by vayulove** [gyunaev/birdtray#110]
**OS**: AMD64 debian sid KDE 5.14.5
**Birdtray version**: 1.6.0
**Thunderbird version**: 69.0 Beta
**Birdtray origin**: from source, followed readme
**Qt version**: 5.11.3 

**Description**

Compiled per readme instructions, went and added my Thunderbird's profile INBOX folder, set it to minimize when icon clicked, and hide when minimized, and it works great.

I just wanted to let people know that it works. I'm excited because the Thunderbird Beta works with KDE file dialogs when you use the packages for XDG Portal just like it does for Firefox 64+.  I was missing that Firetray didn't work with TB 69.0 but Birdtray worked without a hitch. So now I have Thunderbird integrated with KDE file dialogs.

**Comment by vayulove** [comment]
Sorry I can't figure out how to make this not be a bug label, hopefully it's obvious that this is a thank you comment.

**Comment by gyunaev** [comment]
Thank you for reporting!
