### ISSUE TITLE
Incompatible with Thunderbird 68.0

### ISSUE THREAD

**Issue by aindriu80** [gyunaev/birdtray#112]
I tried installed Birdtray with the recent Thunderbird 68.0 release and it doesn't work - get an error saying its incompatible.  Any ideas?

**Comment by gyunaev** [comment]
Please provide the exact message.

**Comment by aindriu80** [comment]
Legacy extensions must be updated to be compatible with thunderbird 68.0

Error: https://i.imgur.com/GDImXBA.png

More Info:
https://support.mozilla.org/en-US/kb/unable-install-add-on-extension-theme-thunderbird

**Comment by gyunaev** [comment]
Birdtray is not a legacy extension and cannot produce the error you showed. It seems like you're trying to install something different.

**Comment by aindriu80** [comment]
So I must tell you your plugin is broken on Thunderbird **68.0**.  My system is Window 10 Pro version 1903 with latest updates installed.  I downloaded both Thunderbird 68.0 32bit and 64bit versions and they both give the same error - 

Here is a screen shot of me trying to install the plugin on Thunderbird 68.0 64bit version:

https://i.imgur.com/jPa6vkq.png

Thunderbird 64bit bit version check:

https://i.imgur.com/0aZcEjd.png


Bye bye
