### ISSUE TITLE
"Minimize to tray" for arbitrary programs?

### ISSUE THREAD

**Issue by dcjkfgdjhd** [gyunaev/birdtray#114]
Thanks so much for creating this tool! After the last TB update, I urgently needed to restore the minimize to tray functionality somehow. (I am on Windows.)

Here is a question: Would you consider adding the ability to minimize **other** programs to the system tray as well, with the option to specify custom icons like for TB? I guess adding this should not be too complex, as the functionality already works very well for TB.

I have a few other programs that are constantly open (cmd.exe, Workflowy) where it would be great if they would not permanently take up space on the task bar.

(In the past, there were a few programs like this on the market, but most are very old, not supported anymore, and most do not allow choosing arbitrary icons, which is important to achieve that Windows 10 tray icon look.)

**Comment by gyunaev** [comment]
I think you're looking for KDocker:  http://kdocker.sourceforge.net/

**Comment by dcjkfgdjhd** [comment]
KDocker does not work on Windows.

**Comment by gyunaev** [comment]
I'm sure there are similar tools on Windows.

**Comment by dcjkfgdjhd** [comment]
No, as I wrote above, there aren't. But of course it was just an idea.

**Comment by dcjkfgdjhd** [comment]
OK, I wrote myself a 60 line Autohotkey script which does exactly what I want.

**Comment by dcjkfgdjhd** [comment]
OK, I wrote myself a 60 line Autohotkey script which does exactly what I want.

This way I can even get rid of Birdtray and only use AutoHotkey.

**Comment by gyunaev** [comment]
You're welcome.
