### ISSUE TITLE
TB command line options

### ISSUE THREAD

**Issue by alaricljs** [gyunaev/birdtray#115]
It would be useful for birdtray to support passing command line options to thunderbird.  This would likely be an additional string of input on the Advanced tab under the path to thunderbird.

My specific use case is -P/--profile and I don't know that there are any other options that make sense to pass.

**Comment by gyunaev** [comment]
Settings - Advanced - Path to Thunderbird executable?

**Comment by alaricljs** [comment]
Tried that but saw nothing in ps to indicate that it worked.  Suppose I can test with my non-default profile to be sure.

**Comment by gyunaev** [comment]
This field accepts the full command-line, so it should work.
