### ISSUE TITLE
Notification Popup

### ISSUE THREAD

**Issue by rnc** [gyunaev/birdtray#122]
**OS**: Fedora 30

**Birdtray version**: GIT Master (1.6.0) 
**Thunderbird version**:68.1.0  
**Birdtray origin**:Source 
**Qt version**: 5.12.4 

**Description**

This is more of an enhancement idea. Could it tie into the notification/toast system (potentially something like https://doc.qt.io/qt-5/qtwidgets-desktop-systray-example.html /  https://doc.qt.io/qt-5/qsystemtrayicon.html ) so that when a new mail arrives a message is shown. Further improvements could be - 

- Click on the toast shows thunderbird
- Could useful information (e.g. account, number of messages etc) be shown in the notification?

**Comment by gyunaev** [comment]
Thunderbird has this option, no?

**Comment by rnc** [comment]
But thats a global notification isn't it (?) - while your monitoring allows for highly specific monitoring. For instance one use-case is that I can then monitor certain work folders and ignore non-work which is very useful for non-distraction during the work-day.
