### ISSUE TITLE
[Windows 10] Unread count not shown

### ISSUE THREAD

**Issue by tooomm** [gyunaev/birdtray#125]
**OS**: Windows 10 Pro 1903 (64bit)
**Birdtray version**: 1.6.1 (64bit)
**Thunderbird version**: 68.1.0
**Birdtray origin**: portable version (downloaded from this repo)

**Description**
Unread count is not shown

**Expected behavior**
Show unread count

**To Reproduce**

1. Enter all relevant mork index files (.msf) from the TB profile and save
2. No unread count shown

**Additional context**
In comparison to https://github.com/gyunaev/birdtray/issues/95, I don't even see a count in the first place.

The other option to use global search didn't work either.
In fact, it made the app crash and misbehave in combination with the "Show red X when Thunderbird is not running" option.

**Comment by gyunaev** [comment]
I don't use Windows and thus don't support this platform at all.

Leaving it open for any Windows dev to pick it up.

**Comment by Abestanis** [comment]
Could it be that you didn't select the correct .msf files? Because that is the mistake I made when I tried to test this:
I selected
`%APPDATA%\Thunderbird\Profiles\`_PROFILE_`\ImapMail\`_name_`.msf`,
but you need to select
`%APPDATA%\Thunderbird\Profiles\`_PROFILE_`\ImapMail\`_name_`\INBOX.msf`.

> In fact, it made the app crash and misbehave in combination with the "Show red X when Thunderbird is not running" option.

Also, could you please open a separate issue for this?

**Comment by tooomm** [comment]
>Could it be that you didn't select the correct .msf files? Because that is the mistake I made when I tried to test this:
I selected
%APPDATA%\Thunderbird\Profiles\PROFILE\ImapMail\name.msf,
but you need to select
%APPDATA%\Thunderbird\Profiles\PROFILE\ImapMail\name\INBOX.msf.

I guess that did the trick. That should be explained better to the user!

**Comment by Abestanis** [comment]
I do agree, the whole process of selecting the mail account could be simplified, but in the meantime we should probably improve the README to better guide the user on how to set it up. Birdtray is open source, so if you want you could help us with that. You can even propose changes to the README right here on Github, no need to download anything.

**Comment by tooomm** [comment]
Thanks for looking into improving the situation for users @Abestanis
