### ISSUE TITLE
Intelligently monitor .sbd

### ISSUE THREAD

**Issue by pablo-blueoakdb** [gyunaev/birdtray#126]
**OS**: Linux 5.2.14-1 / Tumbleweed
**Birdtray version**: 1.6.0
**Thunderbird version**: 68.1.0 (64-bit)
**Birdtray origin**: git
**Qt version**: 4.8.7

**Description**
I am migrating from firetray to birdtray.  What would be ideal is if when adding an .sbd, it is recursed and all .msf's found are monitored.

I have many email filters and a dedicated .sbd with (at the moment) 152 .msf files.  ;)

**Expected behavior**
When monitoring an .sbd, recurse and monitor all found .msf.  I'd suggest not adding all the .msf files but that instead, .sbd is monitored and recursed.  This way should the end-user add another sub-folder, birdtray will auto-magically monitor the new sub-folder.

**Comment by pablo-blueoakdb** [comment]
Hmmm, I don't consider this a bug.  This issue should be marked as an enhancement.  Sorry about that.  I was hasty when I created the issue.  I don't seem to be able to edit the label.

**Comment by gyunaev** [comment]
Monitoring 152 MSF files would make birdtray running full-time on your machine. Basically you'd dedicate at least one CPU core only to this monitoring. If you'd run on battery, forget it too.

Is there a practical reason to monitor so many MSF (and not just a few inboxes)?

**Comment by pablo-blueoakdb** [comment]
In the past when I have tackled these types of problems, I maintain a data structure of objects to inspect and try to minimize by filtering the set at each iteration.

Using the above design pattern, if it were me ... ;), I would track the set of .msf's to monitor and their _last update_ date/time.  At each iteration, I would only inspect those .msf's whose had been updated.  As you know, getting a file's last update date is very light weight.

As for my Use Case, I am a consultant (now semi-retired).  I use my Inbox as a work queue.  I only keep in it the very important, must do messages.  

All other email, is filtered to a parent folder hierarchy with (at the moment) the 150+ children folders.  As clients come and go, I add more folders to track their issues, etc.  As clients come back, I can go to their set of folders and pull context, check old issues, etc.

I also belong(ed) to several mailing lists.  I place their email in their respective folder using filters.  As a side note, at times, it was common for me to receive 200+ email messages a day.

Note, not all 150+ folders receive email at any one time.  In fact perhaps 10-20 (depending on the filters).  What I would prefer is if birdtray works like firetray, I point it to the top-level folder and if it finds any new email in any of the children, it bumps the count up.

Thank you for your consideration.

**Comment by gyunaev** [comment]
I'm using file monitoring implemented at kernel level (i.e. file change notification). But Thunderbird modifies those files as it pleases (and has no reason not to), thus generating lots of updates.

This however is not enough in your case, because it will not detect when you add a new folder (and thus created another MSF) - this would require rescanning the whole directory periodically.

This is not difficult, but I'd like to see if someone else needs this use case, as I honestly don't want to add and maintain code which is useful only to a single user. Appreciate your understanding.

**Comment by pablo-blueoakdb** [comment]
Hi,

Since TBird is stupid about updating the files, perhaps file size can be used.

Thank you for your consideration.

**Comment by pablo-blueoakdb** [comment]
Hi gyunaev,

I wrote a shell script to create the necessary .config entries to monitor all my .sbd's.  

A couple of things:

1. birdtray CPU usage is not crazy.  Of the over 100 .sbd's, a small number are over 1 GiB.  These take a while to crunch but that's expected.
2. I was wondering if there's any interest in creating a directory in the source tree for user contributed software.  Like my shell script.  I figure someone else might be able to benefit from it.  If so, I'll refactor it to be more generic.  If you do not think it is worth doing, that's cool.  

Thanks!

**Comment by gyunaev** [comment]
Yes, this would be helpful. Please create it as contrib/<your script name>/ and put your script and README there. Please describe when one would use the script for, requirements (OS, etc), usage (i.e. shut down birdtray before running it) etc.

**Comment by pablo-blueoakdb** [comment]
To follow up, I've created a shell script that populates the _Account_ entries found under the _Monitoring_ tab.  The script resides in `.../contrib/gen_birdtray_accounts`

**Comment by gyunaev** [comment]
Can you please update your script to generate JSON configuration?

**Comment by pablo-blueoakdb** [comment]
Hi,
Given the new functionality via the GUI, the script is no longer all that useful.  

What do you think?

**Comment by Abestanis** [comment]
I agree, I think you can use the dialog to archive the same effect.
@pablo-blueoakdb Do you still want special support for `.sdb` folders? Like automatically recognizing and watching new or deleted accounts within a folder? Otherwise we can close this issue.

**Comment by pablo-blueoakdb** [comment]
I think we should close this issue and _sunset_ the code I wrote.  It was stop-gap.  It did a job.  

Let me know if there's a preferred way to nuke it.  ;)

Thx!

**Comment by Abestanis** [comment]
@gyunaev already removed the script in f13da8ca6f821855834c346eca9a93d0470efc69 when we switched to JSON-based settings in `1.8.0`, so that is already done. 😃
