### ISSUE TITLE
Monitoring stops working after inbox is compacted

### ISSUE THREAD

**Issue by evmcl** [gyunaev/birdtray#129]
**OS**: Arch Linux
**Birdtray version**: 1.6
**Thunderbird version**: 68.1.1
**Birdtray origin**: AUR

**Description**
After selecting `Compact Folders` from the `File` menu on Thunderbird, the (mork) file monitoring appears to stop working. The count of unread emails does not change when new emails are received or unread emails are read.

**Additional context**
If you compact an inbox that is already compacted (i.e., no gaps of deleted emails in the `msf` file) then monitoring does continue to work. It seems to only stop working if the size of the `msf` file shrinks.

**Comment by gyunaev** [comment]
Not reproduced with 68.1.1 - compacted but still working fine.

**Comment by evmcl** [comment]
Just to double-check you accounted for my additional note about gaps for deleted emails?

Also worth noting I discovered this issue because I use the [Xpunge](https://addons.thunderbird.net/en-US/thunderbird/addon/xpunge/) add-on on a schedule.

**Comment by gyunaev** [comment]
Yes, I indeed checked that I deleted a few emails from Inbox before compacting it, and the inbox file shrinked in size.

**Comment by xdch47** [comment]
i have the same issue with 68.1.2 ->2 out of 3 mailbox are not monitored

**Comment by xdch47** [comment]
Works fine with the current git head.

**Comment by bxabi** [comment]
I also noticed that after compacting a folder a random number of unread emails are shown (usually<10), even though I have them all read.
The workaround which often worked is to select all emails, set them to unread then back to read a couple times, until the unread goes to 0.

**Comment by bxabi** [comment]
I just read in another issue that thunderbird can repair folders if you right click and select Properties. It looks like that fixed the issue this time.

**Comment by Abestanis** [comment]
I wonder if #245 fixes this as well. We had [reports](https://github.com/gyunaev/birdtray/issues/217#issuecomment-580607113) that mork files sometimes contain references to messages that no longer exist. It seems plausible to me that compacting the folder could create such "ghost" references and we know that they can be removed by the Thunderbirds repair functionality. #245 uses a different method to get the unread mail counter and is not affected by these ghost entries. If anyone runs into this again, I would love to see if a Birdtray with the code from #245 reports the correct count.

In any case, if someone has this problem again, please create a copy of the corresponding mork file, remove any personal data from the mork file using [this script](https://github.com/gyunaev/birdtray/tree/master/contrib/anonymizeMork) and upload the the anonymized mork file here with the number of unread messages that are displayed in the Thunderbird user interface for the compacted folder.

**Comment by gyunaev** [comment]
Please provide the feedback whether the latest code fixes this issue, thanks!
