### ISSUE TITLE
Could you please place there compiled version for Win! Idk how to compile it to executable

### ISSUE THREAD

**Issue by SSSNewbie** [gyunaev/birdtray#131]
Could you please place there compiled version for Win! Idk how to compile it to executable

**Comment by Abestanis** [comment]
You can find an installer for Windows here: [https://github.com/gyunaev/birdtray/releases](https://github.com/gyunaev/birdtray/releases)

**Comment by SSSNewbie** [comment]
oh, thnx alot!
