### ISSUE TITLE
QtNetwork does not include OpenSSl libraries on Windows

### ISSUE THREAD

**Issue by Abestanis** [gyunaev/birdtray#137]
I installed Birdtray on a fresh Windows 8.1 vm and noticed that the update was not working. It fails with the error `TLS initialization Failed`. I know I should have done that before submitting the pull request, my apologies. It turns out contrary to my assumptions that QtNetwork is not build with OpenSsl as a static library.

There are two possible solutions for this and I would like your opinion on this:

1. We could bundle the necessary dlls in the installer. But there is a scary paragraph about that on the Qt website: https://doc.qt.io/qt-5/ssl.html#import-and-export-restrictions.
2. We could display a warning in the installer, asking the user to download OpenSsl themselves.

**Comment by gyunaev** [comment]
I am always bundling them with my other software.

**Comment by Abestanis** [comment]
Ok, so we'll go with the first option.
