### ISSUE TITLE
Won't stop showing new message indicator

### ISSUE THREAD

**Issue by geckolinux** [gyunaev/birdtray#14]
Hi there, I loosely organize my life based on the "Inbox Zero" method of task management. That means that messages I need to follow up on are marked as "unread" for a certain amount of time. This appears to confuse Birdtray. After running the Fix for non-zero new message count the icon reset to its normal state. But after I received a few more messages in addition to the previously unread messages, the icon continues to flash the new unread count despite those new messages already being read. Thanks a lot!

**Comment by gyunaev** [comment]
> That means that messages I need to follow up on are marked as "unread" for a certain amount of time.

I'm unsure I understood what it means.

**Comment by geckolinux** [comment]
Sorry for not being clear. Here's an example:

- I currently have 9 messages marked as **unread** because I need to follow up on them. They may stay as **unread** for a few weeks until I get around to finishing them.
- I ran the Birdtray "Fix" for non-zero inbox count, and the icon reset to the normal Thunderbird logo.
- I received 3 new messages. I read them, and now they are in the "read" state.
- The Birdtray icon still shows **3 new** messages. It should show **9**, because that is how many I have marked as **unread**.

**Comment by gyunaev** [comment]
I still don't get it. So you have 9 unread messages, but you use Fix button to mark them read?

In any case, this will not work properly. This is why it says next to Fix button that you should use it when there is a non-zero unread count, but you have zero unread messages. If you do not have zero unread messages, the result is unpredictable.

**Comment by geckolinux** [comment]
Yes, I guess that was a mistake to use the Fix button.

What about an option to make it simply show the count of unread messages since after running the "Fix" button? I would be happy if it only showed me **3** new messages when they arrive, and after I read them it resets back to 0. In other words, don't notice if I later mark a message as un-read. Just how many messages have arrived that I have never read.

**Comment by gyunaev** [comment]
This is not possible using the database interface. It tells me "there are 3 unread messages". It doesn't tell me whether those are new messages, or old messages marked unread.

**Comment by geckolinux** [comment]
Hmm I see. Is there any way to make it work normally now after I inadvertently hit the "Fix" button? I tried marking all of my messages as read, closing Thunderbird, and re-running the "Fix". After opening TB again, it initially starts with the standard icon and no new messages, but any future incoming messages remain in the Birdtray count even after marking them as read.

**Comment by gyunaev** [comment]
To fix it, make all your messages read by right-clicking on each of your folders and choosing "Make folder read". Then **close Thunderbird**, and then press Fix button. 

Using Fix button without closing Thunderbird is another way to wreak havoc with your database.

**Comment by geckolinux** [comment]
Whew, that worked. Thanks a lot!

**Comment by geckolinux** [comment]
Hmm, unfortunately it looks like it's still messed up. A few hours later I received 2 new messages, I read them, but Birdtray won't stop flashing 2 new.

**Comment by geckolinux** [comment]
So upon further testing, it looks like it will only stop showing the unread message account if I Trash the messages, even though they were already marked as read.

**Comment by geckolinux** [comment]
I tried restoring my Thunderbird profile from a backup before I tried Birdtray. Birdtray showed 12,000 new emails, so I closed Thunderbird and then ran the counter Fix. (It took about 15 minutes on a fast SSD disk). Then I re-opened Thunderbird and Birdtray, and it showed no new messages. However, when I received a new message and read it, the 1 new message indicator won't go away in Birdtray unless I moved the message to the Trash.

**Comment by gyunaev** [comment]
Anyone else has the same problem? Wondering if this is setup-specific.

**Comment by gyunaev** [comment]
There are two things addressing the database status (and indicator):

1. With IMAP, the database status is only updated when the status on server is updated. If your'e disconnected from Internet, it will never drop unread status.

2. It can take up to a minute for the unread status to change.

**Comment by JackDinn** [comment]
> Anyone else has the same problem? Wondering if this is setup-specific.

I maintain a very close eye on the project, my version is your latest commit. I rigorously test and use daily on several linux based systems. I have not seen the behaviour described (although i dont really understand exactly what OP is doing/saying exactly) but as far as i can say the indicator has always remained in-sync with my actual number of unread mail regardless of whether i manually mark loads of mail un-read myself & then get even more mail on top of that etc.

_(My 2 cents worth) Why does OP not just use the "star" marking system ?_

**Comment by geckolinux** [comment]
Hi there, thanks for the replies.

I am also using a recent GIT version from 2018-10-03.

I am observing this behavior with a stable internet connection, not offline.

> (My 2 cents worth) Why does OP not just use the "star" marking system ?
That's a good idea. But for now, I marked all my messages as read, and Thunderbird does not show any unread messages. From that point on, after running the unread count Fix button, the Birdtray icon initially shows no new messages, but any future incoming messages continue to flash as unread in Birdtray, even after marking them as read.

**Comment by JackDinn** [comment]
not 100% sure but i think i read somewhere that using the "fix" button whilst TB is still running could possibly mess up the database.

**Comment by geckolinux** [comment]
Working correctly now with SQLite parser and fresh TB profile. 
(Does *not* work with Mork on some accounts.)

**Comment by venomone** [comment]
Sorry to say but no., it does not work correctly at all ... even 6 years later this fuck is still given
