### ISSUE TITLE
Birdtray Icon

### ISSUE THREAD

**Issue by Abestanis** [gyunaev/birdtray#142]
**TL;DR**: Birdtray needs its own icon.

I used a [grayscale image of the Thunderbird icon](https://raw.githubusercontent.com/gyunaev/birdtray/master/src/res/birdtray.ico) for the Windows executable and the installer, but that was just meant as a temporary icon.

In #130, the original Thunderbird icon [was used](https://github.com/gyunaev/birdtray/tree/master/src/res/icons), but I don't think that is a good idea. The icon belongs to Thunderbird and seeing two programs with the same icon will cause confusion.

**Comment by Abestanis** [comment]
@gyunaev This is also a legal issue, as the Thunderbird icon is [a Mozilla trademark](https://www-archive.mozilla.org/foundation/trademarks/policy).
Especially since we are doing one of the `Don't`s:
> Don’t use marks, logos, company names, slogans, domain names, or designs that are confusingly similar to Mozilla trademarks.

[from here](https://www.mozilla.org/en-US/foundation/trademarks/policy/).
I think this needs to be resolved before publishing Birdtray to the flatpak store, @ThanosApostolou.

**Comment by gyunaev** [comment]
This is correct. However since I have no intentions to publish anything in the flatpak store, I'd simply wait until someone submits another icon.

**Comment by Abestanis** [comment]
Ok, I just wanted to make sure that we all understand the issue here. I would create an icon myself if I had the skills. You should tag this issue with the `help wanted` tag.

**Comment by ThanosApostolou** [comment]
Maybe a simple solution would be to use the svg image from the papirus icon theme which is a bit different and it is published as GPL-3.0, so there won't be any legal issues. Here's an exported 512 sized png:

![thunderbird](https://user-images.githubusercontent.com/21288843/69335494-c08e4180-0c65-11ea-89db-e136cc9e0c1a.png)

I don't have much skills with editing images, but maybe I can add an exclamation mark or something at the bottom to indicate that this is an indicator/notification application if you think this is a good idea.

**Comment by ThanosApostolou** [comment]
Ok, I added a bell, rotated to match the envelop, I tried a couple of positions and this looked the best for me. Shall I do a PR adding the svg under **src/res** and replacing the png images under **src/res/icons** ?

![org gyunaev Birdtray2](https://user-images.githubusercontent.com/21288843/69338689-6644af00-0c6c-11ea-9dd7-a707d0c6605b.png)

**Comment by rnc** [comment]
While I am in no way a  designer .... imho the blue looks better. With the bell icon it doesn't look lined up with the bottom of the envelope? Or would it be better to have it vertical with the semi-circular 'bell sounds' (e.g. see https://thenounproject.com/term/ring-bell/2515101/ ). Perhaps the bell should be in a darker blue/colour?

**Comment by Abestanis** [comment]
I think this looks very good. Could you also try a `B` for Birdtray instead of the bell?

**Comment by ThanosApostolou** [comment]
@rnc the image that you sent needs login to be downloaded and it's under CC license which demands that you give credits to the creator and I don't know if the developers want to do that
.
Here are 2 icons with better bell alignment, one with the B letter and one without.

![org gyunaev Birdtray4](https://user-images.githubusercontent.com/21288843/69345916-95621d00-0c7a-11ea-85be-f936b2e183c6.png)

![org gyunaev Birdtray5](https://user-images.githubusercontent.com/21288843/69345926-9b57fe00-0c7a-11ea-8989-b8b444154475.png)

Unfortunately I don't know how to create a calligraphic letter which would look better. But if someone wants to do something better I can send the svg images and try himself. So, tell me if/when you want me to start a PR and for which image.

**Comment by rnc** [comment]
@ThanosApostolou I wasn't suggesting to use that image, just to show how the bell 'sounds' can look.

**Comment by Abestanis** [comment]
I really like the blue one with the Bell and the B. Is that B still visible when the icon is `32x32`?
I also made my own attempt of just adding a B, but I don't think it looks as good as the bell and the B:
![Birdtray-B](https://user-images.githubusercontent.com/6966049/69358061-86816780-0c86-11ea-9130-3602f55b1f4f.png)
![Birdtray-B-Small](https://user-images.githubusercontent.com/6966049/69358071-8a14ee80-0c86-11ea-84e9-3487c2c5cd7f.png)

**Comment by Abestanis** [comment]
@ThanosApostolou Once you do submit a pull request, please also overwrite the [icon file](https://github.com/gyunaev/birdtray/blob/master/src/res/birdtray.ico).
We'll also need to change [the header image used in the windows installer](https://github.com/gyunaev/birdtray/blob/master/installer/assets/header.bmp). Luckily I kept the Gimp project file for that reason:
[BirdTrayHeaderImage.zip](https://github.com/gyunaev/birdtray/files/3875817/BirdTrayHeaderImage.zip)
If you are not comfortable with Gimp, I can take the final svg from your pull request, edit the header myself and the send it to you.

**Comment by Abestanis** [comment]
This is resolved by #179

**Comment by creepertron95** [comment]
I'm probably too late when I found this but, I wanted to propose an application icon for Birdtray.

![birdtray](https://user-images.githubusercontent.com/53346722/107814629-d76ff680-6d37-11eb-8643-8d4673c6a4aa.png)

**Comment by gyunaev** [comment]
Thank you for your effort! The second one looks better to me. @Abestanis, what would you say?

**Comment by Abestanis** [comment]
@creepertron95 Thank you for these, they look very good.

> The second one looks better to me.

@gyunaev I agree, I think the more round the better. Do you prefer this icon over the current one and want me to replace it?

**Comment by creepertron95** [comment]
I have made a small fix to that second icon and I provided a bigger png and an svg.

![birdtray-icon](https://user-images.githubusercontent.com/53346722/108772681-eff3c400-7522-11eb-9b8e-42ff7fca4cde.png)

---

[birdtray-icon.svg.tar.gz](https://github.com/gyunaev/birdtray/files/6025246/birdtray-icon.svg.tar.gz)
