### ISSUE TITLE
Option to check mails for favorite folders

### ISSUE THREAD

**Issue by morfikov** [gyunaev/birdtray#153]
When you have multiple mail accounts (or many labels, ~200), it's a little bit inconvenient to monitor only some them for new messages. Of course, you can add manually 20-30 folders and that will do the job, but what about changing the current set of monitored folders? For instance, sometimes I want to monitor one folder for a specific time (a day, an hour, etc). When the time passes, I simply don't need this folder to be monitored for new messages anymore because the messages aren't that important to me. But at the same time other folders can become more important, and adding/deleting an entry in the `birdtray` settings each time this behavior changes isn't a good thing. In such cases I usually mark a folder as favorite and can filter them in the `thunderbird` view. Is it possible to add such option to `birdtray`?

**Comment by gyunaev** [comment]
The logic you're requesting is too custom for your use case to be worth implementing, sorry. You're welcome to submit a patch.

**Comment by Abestanis** [comment]
I think solving the general problem of watching different mail folders at different times could benefit other users as well.

How about this: Add "Birdtray Profiles". Each profiles has an independent list of mail folders to watch and you can switch between the profiles via the context menu.

@gyunaev Do you think that would be a beneficial addition? If so, I could try to implement this.

**Comment by gyunaev** [comment]
It might be useful addition, but its nightmare to implement (especially from UI side) and test/maintain. Up to you if you want to deal with this :)

**Comment by Abestanis** [comment]
I'd like some other peoples opinion on how beneficial this would be. @morfikov would this solve your problem?

**Comment by morfikov** [comment]
I just use the fav folder feature as it's convenient way to see who sent you emails. Since birdtray notifies about new mails, I think it should take the fav folders into account -- many ppl who have more mail accounts/labels use the fav folders. The idea behind this feature is just to stop messing with birdtray options whenever you want to add/remove folders -- you simply mark a folder you want to watch for mail as favorite and you're done.

**Comment by Abestanis** [comment]
I had a quik look at that and it looks like Thunderbird stores the favourites information in a mork file at `<Thunderbird profile path>/panacea.dat`. I personaly don't think implementing reading this file is a good idea, because it makes us depend on another undocumented behaviour of Thunderbird, that could change at any time and breake this feature.

Using the "Birdtray Profiles" I proposed would at least allow you to easily switch between different monitored files without depending on such an undocumented feature, but if it is of no use to you or anybody else there is no point of implementing it.

**Comment by morfikov** [comment]
I don't think the profiles will be of any use in my case, since I have several hundreds of labels in many mail accounts, and I switch between (mark/unmark) them often. So the the profile feature isn't really for me.

**Comment by Abestanis** [comment]
Is it always a different set of labels that you select? Otherwise, switching between those x labels in whatever accounts would be accomplished by switching the "Birdtray profile", which would only take two clicks.
Or am I missing something?

**Comment by morfikov** [comment]
No, it depends on context -- when I see some interesting mail/thread or whatever I participated in, sometimes I want to notified as soon as possible when someone responds. When the conversation is over, I don't need to pay attention to the label anymore, at least till some other event happens that drag my attention.

**Comment by Abestanis** [comment]
Ok, the Profiles won't work for your scenario. You'll have to submit a patch yourself, as @gyunaev suggested.

**Comment by morfikov** [comment]
I have a question. 

Currently in the `settings` -> `monitoring` you can add accounts/folders you want to monitor. If you want to stop monitoring some account, you have to remove it from the list. Would it be possible to add some `check` column to the list? In this way I could add many folders and just check/uncheck the right positions whenever I want, and only those checked positions would be monitored for new mails.

**Comment by antonrunov** [comment]
I'm also used to use favorite folders with Fire Tray and terribly miss this functionality in Birdtray. I think it should be quite common usecase when yo want to monitor only specific folders in each account. `Settings -> monitoring` allows to select top level folders but not subfolders.

**Comment by gyunaev** [comment]
> I had a quik look at that and it looks like Thunderbird stores the favourites information in a mork file at `<Thunderbird profile path>/panacea.dat`.

I tried to rely on this file before (it also has some unread information). This file doesn't seem to be up to date, and it is unclear at which times it is being updated.
