### ISSUE TITLE
Deleting a message invalidates the ignored messages

### ISSUE THREAD

**Issue by marmistrz** [gyunaev/birdtray#156]
**OS**: Arch Linux
**Birdtray version**: 1.6-1
**Thunderbird version**: 68.2.0
**Birdtray origin**: AUR
**Qt version**: 5.13.2-1

**Description**
1. Ignore unread messages
2. Delete an unread message

**Expected behavior**
Birdtray shows no new messages.

**Actual behavior**
Birdtray shows there are some new messages, their count is probably the count of all unread messages.

**Comment by gyunaev** [comment]
This happens when you delete a message and unread count is zero. This is intentional, as otherwise a current unread count would be "-1" and the next new message won't be shown.

**Comment by marmistrz** [comment]
In such case, the unread count should probably be set to 0 and not reset, i.e. `count = max(count, 0)`.
