### ISSUE TITLE
autostarting twice on kde

### ISSUE THREAD

**Issue by jasmines** [gyunaev/birdtray#157]
I put birdtray in autostart programs.
When I reboot, I see two icons in the tray.
I can quit one, and the other keeps running correctly.
I can't find out why it is loaded twice.

**Comment by rnc** [comment]
For reference, I am using Fedora 31 with KDE Plasma 5.16.5 and I only see one icon when it autostarts. What version are you using? What are your configuration settings for birdtray / kde autostart module?

**Comment by jasmines** [comment]
Solved.
It was due to the fact I set kde to restore previous session instead of an empty one.
Probably birdtray can't handle such behaviour.
