### ISSUE TITLE
To really restore the missing Thunderbird icon

### ISSUE THREAD

**Issue by Eusebius-Florestan** [gyunaev/birdtray#158]
I installed Birdtray when Thunderbird, from version 68 onwards, removed its pretty and expressive white envelope with green arrow from the notification bar, replacing it with a dull and inconspicuous sign (and this without even announcing it in the release notes).
Birdtray is an excellent software, but the only thing it can't do is to restore the envelope icon to announce the arrival of a message!
Indeed, by default, its own icon is precisely this one. But it is present at all times, not when a mail arrives, which is the opposite of its function under Thunderbird. It is true that you can make it blink when a message arrives, but its constant presence is precisely what the Thunderbird user doesn't want.
Only solution: change the Birdtray icon and choose, for unread messages, the envelope icon. But... this is impossible, because the envelope icon, when chosen to announce unread messages, becomes a tiny, invisible dot; it is not understood by the software as an icon but as an image much too small.
Well, it will be argued, it is sufficient to choose a larger file size for this image of the envelope. Yes, but despite hard searches on the Net, I never found this famous icon in any other format than 1k!
My request would be that under the item "different icon if not read" we could place the icon of the Thunderbird envelope, recognized as such by Birdtray. This should be easy for the excellent programmer of this software!

**Comment by gyunaev** [comment]
There is a "different icon when unread" checkbox in Settings, would this work?

**Comment by gyunaev** [comment]
I reread this twice and I'm still unsure what exactly you are asking for. What exactly do you want to do and what exactly doesn't work?

**Comment by Abestanis** [comment]
@gyunaev I think we should close this, there has been no feedback for 4 months.
