### ISSUE TITLE
Compilation errors in Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by MicioMax** [gyunaev/birdtray#16]
Hi,

compiling on above systems (I guess QT 5.9) I get 3 compilation errors in menu->addAction() calls
(bad parameters). Solved like this : 
`
//            menu->addAction( tr("New Email Message"), this, &TrayIcon::actionNewEmail );

			QAction * mMenuNewEmail = new QAction( tr("New Email Message"), this );

			connect( mMenuNewEmail, &QAction::triggered, this, &TrayIcon::actionNewEmail );

			menu->addAction( mMenuNewEmail );
`

`
//    menu->addAction( tr("Settings..."), this, &TrayIcon::actionSettings );

	QAction * mMenuActionSettings = new QAction( tr("Settings..."), this );

	connect( mMenuActionSettings, &QAction::triggered, this, &TrayIcon::actionSettings );

	menu->addAction( mMenuActionSettings );
`

`
//    menu->addAction( tr("Quit"), this, &TrayIcon::actionQuit );

	QAction * mMenuActionQuit = new QAction( tr("Quit"), this );

	connect( mMenuActionQuit, &QAction::triggered, this, &TrayIcon::actionQuit );

	menu->addAction( mMenuActionQuit );
`

(your code commented here)

**Comment by gyunaev** [comment]
Can you please provide the actual error log?

**Comment by MicioMax** [comment]
`trayicon.cpp: In member function ‘void TrayIcon::createMenu()’:
trayicon.cpp:410:87: error: no matching function for call to ‘QMenu::addAction(QString, TrayIcon*, void (TrayIcon::*)())’
    menu->addAction( tr("New Email Message"), this, &TrayIcon::actionNewEmail );
                                                                              ^
In file included from /opt/Qt/5.5/gcc_64/include/QtWidgets/QMenu:1:0,
                 from trayicon.cpp:1:
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:76:14: note: candidate: QAction* QMenu::addAction(const QString&)
     QAction *addAction(const QString &text);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:76:14: note:   candidate expects 1 argument, 3 provided
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:77:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&)
     QAction *addAction(const QIcon &icon, const QString &text);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:77:14: note:   candidate expects 2 arguments, 3 provided
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:78:14: note: candidate: QAction* QMenu::addAction(const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QString &text, const QObject *receiver, const char* member, const QKeySequence &shortcut = 0);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:78:14: note:   no known conversion for argument 3 from ‘void (TrayIcon::*)()’ to ‘const char*’
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:79:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QIcon &icon, const QString &text, const QObject *receiver, const char* member, const QKeySequence &shortcut = 0);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:79:14: note:   candidate expects 5 arguments, 3 provided
In file included from /opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:37:0,
                 from /opt/Qt/5.5/gcc_64/include/QtWidgets/QMenu:1,
                 from trayicon.cpp:1:
/opt/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h:538:10: note: candidate: void QWidget::addAction(QAction*)
     void addAction(QAction *action);
          ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h:538:10: note:   candidate expects 1 argument, 3 provided
trayicon.cpp:451:73: error: no matching function for call to ‘QMenu::addAction(QString, TrayIcon*, void (TrayIcon::*)())’
     menu->addAction( tr("Settings..."), this, &TrayIcon::actionSettings );
                                                                         ^
In file included from /opt/Qt/5.5/gcc_64/include/QtWidgets/QMenu:1:0,
                 from trayicon.cpp:1:
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:76:14: note: candidate: QAction* QMenu::addAction(const QString&)
     QAction *addAction(const QString &text);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:76:14: note:   candidate expects 1 argument, 3 provided
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:77:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&)
     QAction *addAction(const QIcon &icon, const QString &text);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:77:14: note:   candidate expects 2 arguments, 3 provided
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:78:14: note: candidate: QAction* QMenu::addAction(const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QString &text, const QObject *receiver, const char* member, const QKeySequence &shortcut = 0);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:78:14: note:   no known conversion for argument 3 from ‘void (TrayIcon::*)()’ to ‘const char*’
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:79:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QIcon &icon, const QString &text, const QObject *receiver, const char* member, const QKeySequence &shortcut = 0);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:79:14: note:   candidate expects 5 arguments, 3 provided
In file included from /opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:37:0,
                 from /opt/Qt/5.5/gcc_64/include/QtWidgets/QMenu:1,
                 from trayicon.cpp:1:
/opt/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h:538:10: note: candidate: void QWidget::addAction(QAction*)
     void addAction(QAction *action);
          ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h:538:10: note:   candidate expects 1 argument, 3 provided
trayicon.cpp:456:62: error: no matching function for call to ‘QMenu::addAction(QString, TrayIcon*, void (TrayIcon::*)())’
     menu->addAction( tr("Quit"), this, &TrayIcon::actionQuit );
                                                              ^
In file included from /opt/Qt/5.5/gcc_64/include/QtWidgets/QMenu:1:0,
                 from trayicon.cpp:1:
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:76:14: note: candidate: QAction* QMenu::addAction(const QString&)
     QAction *addAction(const QString &text);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:76:14: note:   candidate expects 1 argument, 3 provided
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:77:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&)
     QAction *addAction(const QIcon &icon, const QString &text);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:77:14: note:   candidate expects 2 arguments, 3 provided
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:78:14: note: candidate: QAction* QMenu::addAction(const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QString &text, const QObject *receiver, const char* member, const QKeySequence &shortcut = 0);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:78:14: note:   no known conversion for argument 3 from ‘void (TrayIcon::*)()’ to ‘const char*’
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:79:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QIcon &icon, const QString &text, const QObject *receiver, const char* member, const QKeySequence &shortcut = 0);
              ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:79:14: note:   candidate expects 5 arguments, 3 provided
In file included from /opt/Qt/5.5/gcc_64/include/QtWidgets/qmenu.h:37:0,
                 from /opt/Qt/5.5/gcc_64/include/QtWidgets/QMenu:1,
                 from trayicon.cpp:1:
/opt/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h:538:10: note: candidate: void QWidget::addAction(QAction*)
     void addAction(QAction *action);
          ^~~~~~~~~
/opt/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h:538:10: note:   candidate expects 1 argument, 3 provided

`

**Comment by MicioMax** [comment]
Sorry, my fault... I had an old qt5.5 package installed in OPT, and my system was using it.
