### ISSUE TITLE
Global Search and Indexer must be enabled for birdtray to work

### ISSUE THREAD

**Issue by mihav** [gyunaev/birdtray#18]
Birdtray never displayed any notification at my workstation and after a bit of stracing I concluded this is because I had Global Search and Indexer disabled. Since I have over a million emails stored, enabling this produces >2g sqlite database (which took all night), adds few hundred of ram to Thunderbirds usage and slows down performance quite a bit. I don't need/use GS&I feature and I only want to be notified of new mail in Inbox folders, so this is severe overkill. Is there any other possible way of getting new mail notification status? Maybe directly stating Inbox mbox file or something similar?

Also, probably adding note to documentation that GS&I must be enabled might be useful to someone.

**Comment by MicioMax** [comment]
Ah, that's probably the same issue I posted few minutes ago... I also have global indexing disabled and I've no notifications.

**Comment by gyunaev** [comment]
This is correct. I look things up in the sqlite database, and if there's no database, there is no notification either. #12 would fix it.
