### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gyunaev** [gyunaev/birdtray#192]
@Abestanis do you think its good time to make a release? If so, can you please provide Windows releases and make a release? I've added you as a collaborator.

**Comment by Abestanis** [comment]
Wow, thank you for adding me, that means a lot. I'm working on the warnings as tooltips I described in [#175 (comment)](https://github.com/gyunaev/birdtray/pull/175#issuecomment-555689892), do you thing we should wait and include them? Otherwise, I think this is a pretty good time to create another release. Do you want me to write the changelog for the release or do you want to do that?

**Comment by gyunaev** [comment]
No, I wouldn't wait for it. There was a bunch of important changes already, so its worth the release.

**Comment by Abestanis** [comment]
What about the changelog, do you want me to write it?

**Comment by gyunaev** [comment]
Yes, please - its mostly your and @ThanosApostolou changes there anyway :) please don't forget to credit yourself and @ThanosApostolou.

**Comment by Abestanis** [comment]
Ok, I will do that as soon as #189 is resolved. I think the code for this new release should be `1.7.0`, or do you prefer `1.6.2`?

**Comment by gyunaev** [comment]
1.7.0 is fine.

**Comment by Abestanis** [comment]
Sorry for the delay, I was trying to implement the switch to Github Actions as I proposed in #196, but that will take a bit. I would create a commit that changes the version and push it to the master branch if that is ok with you. After that, I will create a release draft where you can add the Windows installers you generated in your VM. Once we tested everything, I'll let you know here and you can publish the release.

Could you also quickly check if I missed anything for the changelog?

```markdown
This release welcomes some new committers:
* @ThanosApostolou who took on the task of publishing and maintaining Birdtray on Flathub.
* @thunder2 who added portable configuration storage support for the Windows Birdtray version.

Additions:
* Birdtray is now available to download via Flathub thanks to @ThanosApostolou.
* @Abestanis added the ability to display Birdtray in different languages. This release supports English and German. If you want to submit a translation in your language, please do so via the Github repository.
* The Windows installer allows to select which languages are installed with Birdtray. Contributed by @Abestanis.
* @gyunaev added build arguments to set the default thunderbird executable path and arguments.
* The Mork parser gained a new and improved dialog for selecting mail accounts by @Abestanis.
* @Abestanis added a "Blank" entry to the "New Mail" submenu of the system tray context menu.
* Birdtray can now be configured to automatically check for a new version on startup. This can be enabled or disabled in the Birdtray settings and during installation on Windows. There is also an option to ignore a specific release. Contributed by @Abestanis.
* On Windows, Birdtray is able to download and install a new version of Birdtray. Contributed by @Abestanis.
* @Abestanis added an option to draw a border around the number of unread mails in the Birdtray system icon to improve readability.
* @thunder2 added support for reading and storing the Birdtray configuration from the directory of the birdtray executable, which allows portable installations.

Changes:
* @ThanosApostolou created a new icon for Birdtray.
* @gyunaev added support for specifying the Thunderbird executable with arguments
* The Windows installer can now also be displayed in different languages. Currently also supports English and German. Contributed by @Abestanis.
* Birdtray can now wait for the system tray to become available when autostarting before the Desktop UI. Contributed by @gyunaev.
* The Sqlite Parser does no longer work with Thunderbird 68+. @gyunaev Added some warnings for this.
* @gyunaev added support for using svg graphics as Birdtrays system tray icon.
* Better handling when Thunderbird launches its updater and immediately quits after it is started by Birdtray on Windows. Contributed by @Abestanis.
* Fix various bugs.
* Some improvements to the user interface.
```

**Comment by Abestanis** [comment]
Also, @ThanosApostolou, am I supposed to add an entry for the new release to the `<releases>` tag in `com.ulduzsoft.Birdtray.appdata.xml` or should I replace the curren one?

**Comment by ThanosApostolou** [comment]
@Abestanis Add a new entry with the new release, above the last one.

**Comment by Abestanis** [comment]
Thanks for the tip, we should include `appstreamcli` when we add autodeploy to this repository.
There was a warning about the empty `content_rating` tag, but that seems to be [a bug in `appstreamcli`](https://github.com/hughsie/oars/issues/18).

**Comment by Abestanis** [comment]
Ok, I created [a release draft for 1.7.0](https://github.com/gyunaev/birdtray/releases/tag/untagged-4f3e4a104a27b5fa78da), build the installer and tested them and Birdtray on Windows. @gyunaev please have a look and if you don't find anything, you can release the draft and close this issue.
