### ISSUE TITLE
Allow watching subdirectories

### ISSUE THREAD

**Issue by Vexatos** [gyunaev/birdtray#194]
The way my mail directory is set up, my inbox has a bunch of subdirectories where new mails are being moved into based on filters. When new mails appear in those, they won't count towards the number of unread messages in the tray icon when I am telling birdtray to watch the inbox for unread messages, only mails that stay in the inbox directory itself show up. I am currently not able to add the subdirectories separately to count towards it, as they do not appear in the list of directories that can be watched. Only directories in the root appear at all. It would be very nice if you added subdirectories to the list of directories that can be watched, so that I do not miss out on emails that are being sorted into them.

(Info: I am using the latest version compiled from the master branch with Mint Cinnamon 19.2 and Thunderbird 68.2.1)

**Comment by petrskovoroda** [comment]
You can manually add your subdirectories to watchlist in configuration file: `~/.config/ulduzsoft/birdtray.conf`
Like this:
```
account0Color=#0000ff
account0URI=/home/user/.thunderbird/xxx.default/ImapMail/imap.gmail.com/INBOX.msf
account1Color=#0000ff
account1URI=/home/user/.thunderbird/xxx.default/ImapMail/imap.gmail.com/INBOX.sbd/Subdir.msf
```

**Comment by Abestanis** [comment]
@Vexatos Thanks for reporting this. I was actually unaware of the existence of mail subfolders when I created the mail account selection dialog.
You can use the nice workaround described by @petrskovoroda until #195 is merged.

**Comment by Vexatos** [comment]
Thank you very much, I can add subdirectories on master now.
