### ISSUE TITLE
Special characters in directory names displaying wrong

### ISSUE THREAD

**Issue by Vexatos** [gyunaev/birdtray#197]
**Version info**: I am using the latest version compiled from the master branch with Mint Cinnamon 19.2 and Thunderbird 68.2, using the Mork parser.

**Description**
If one of your mail directories contains a special character, It shows up wrong in the settings menu where you select directories to watch.

**To Reproduce**
Create a mail directory on any account in thunderbird with a special character in its name.

**Example**
The character "ä" shows up as "&AOQ-"

**Comment by Abestanis** [comment]
That is strange, it works on my Windows machine:
![mail accounts selection dialog](https://user-images.githubusercontent.com/6966049/69912828-12d21e00-142f-11ea-884f-78dce85b4259.png)
![mail accouns list](https://user-images.githubusercontent.com/6966049/69912831-1e254980-142f-11ea-9127-e3923c285b6a.png)
From a quick test, this also seems to be able to work in a Ubuntu vm:
![Ubuntu](https://user-images.githubusercontent.com/6966049/69912974-b3c1d880-1431-11ea-9ed0-f8c372669d34.png)
Please provide your Qt version. And next time, please fill in the template, it is there for a reason.

**Comment by Vexatos** [comment]
I am using libqt 5.9.5, it looks like this for me
![grafik](https://user-images.githubusercontent.com/4135064/69913163-68f59000-1434-11ea-89ea-a540034cceaa.png)
![grafik](https://user-images.githubusercontent.com/4135064/69913167-7ca0f680-1434-11ea-9b88-f4467bc6ae94.png)

**Comment by gyunaev** [comment]
This is UTF-7 encoding. Is your file system UTF-8? Were your mail folders created recently, or very long time ago?

**Comment by Vexatos** [comment]
A long time ago, but directories I create brand new are also affected.

**Comment by gyunaev** [comment]
Possibly Thunderbird remembered somewhere that your profile used UTF7?

Can you create a totally new profile and see if directories are still created using this encoding?

**Comment by Vexatos** [comment]
Yep, on a new profile this is not an issue.

**Comment by gyunaev** [comment]
Then I guess we gonna leave the current code as-is. Its hard to autodetect UTF7, so if upgrading the profile works, this is a better solution overall.

**Comment by Vexatos** [comment]
I'll try to figure out if that is possible.
