### ISSUE TITLE
couple of errors, cant enter proper profile path & "show TB" does not work.

### ISSUE THREAD

**Issue by JackDinn** [gyunaev/birdtray#2]
Firstly i really appreciate the work on a TB tray integration for linux (especially KDE) so thank you.

I noticed a couple of bugs -
when trying to enter the profile path with the GUI file browser it will not accept the proper profile folder, it rejects it with the message that it must contain global-messages-db.sqlite but it does. I had to put the path in manually (text) it accepts it fine then.

Also the "show thunderbird" from the context menu of tray icon does not do anything even if TB is only minimized.

I am now using Kdocker to iconify, TB's settings to pop-up & sound notify and birdtray to show a persistent tray notification that i have unread/new mail. Its all a bit of a mess but that's mozilla and KDE's fault. Even though i now have to have 2 separate icons for the single app I'm happier than i was before so cheers for the work.

Manjaro KDE

**Comment by gyunaev** [comment]
I have just released 0.2 so you shouldn't be needing KDocker anymore as it now can show/hide in tray. So you can use one icon now :)

"Show thunderbird" and "snooze" were placeholders before. Now they work.

Regarding the path, I fixed it after the 0.2 release - basically you didn't have / after the path. I'm now adding it automatically if not here.

**Comment by JackDinn** [comment]
That works a treat. I think once the fact that this exists gets out a lot of people in the linux sphere are going to be very interested. I shall post on reddit and manjaro.

One last request i have is that it has an option to hide to tray when minimized, That would make it just about everything iv been looking for since TB decided to remove all the addons that i (and a lot of others) needed (firetray & minimize to tray etc).

Thank you.

**Comment by gyunaev** [comment]
I just implemented "minimize to tray". Unfortunately you'd have to remember to minimize Thunderbird as I find no way to disable the close button.

**Comment by JackDinn** [comment]
Perfect (well as far as I'm concerned anyhow) ^^ This puts an end to 4 or 5 months of arsing around with Kmail & akonadi, Evolution, Mail-spring, Kube, Trojita, Geary, Kdocker.... etc etc.

Keep up the great work.
P.S. would you like another niggle iv spotted, should i start another thread.

**Comment by gyunaev** [comment]
Thank you. Yes, please. It is easier to track which issues haven't been implemented if each is in a different thread.
