### ISSUE TITLE
[REQUEST]: Option to remove the TB main window close button.

### ISSUE THREAD

**Issue by tnilzon** [gyunaev/birdtray#201]
To avoid accidentally closing of TB (you don't want to close TB when using Birdtray and with TB in the tray), it would be nice to be able to remove the TB main window close button. Note: Keep close button on all other TB windows opened from TB (e.g. "New Message", "Address Book", etc.).

/Thanks

**Comment by gyunaev** [comment]
This is not possible from an outside app.

**Comment by Abestanis** [comment]
@gyunaev is right, it doesn't look like it is possible. On Windows, if Thunderbird would use the native window bar provided by Windows, it would be possible to control that even from a different process. Unfortunately, Thunderbird does not use the standard window bar, but disabled it and draws the buttons on its own.
However, it might be possible to hide the close button using a Thunderbird theme. This was done [by accident in the past](https://support.mozilla.org/de/questions/1111050).
