### ISSUE TITLE
Birdtray does not detect Thunderbird (i3wm)

### ISSUE THREAD

**Issue by Phitherek** [gyunaev/birdtray#202]
**OS**: Ubuntu 18.04 
**Birdtray version**: 1.7.0 (master) 
**Thunderbird version**: 68.2.1 
**Birdtray origin**: From source 
**Qt version**: 5.9.5 

**Description**

Birdtray does not detect opened Thunderbird window even though the name matches the filter. The icon is crossed out and it constantly tries to start it when the option is checked. wmctrl -l command lists the window normally.

**Expected behavior**

Birdtray detects the existing Thunderbird window.

**To Reproduce**

1. Use i3wm
2. Install and open Birdtray and Thunderbird
3. Configure Birdtray

**Comment by Phitherek** [comment]
Additionally, what seems to work in spite of this bug is detection of new emails (the icon blinks when it's supposed to and debug log shows correct amounts).

**Comment by dalexnagy** [comment]
Same issue with me (Ubuntu 18.04.3, T'Bird 68.2.1).
In addition, I get "Error retrieving accounts: Cannot access the database. If you're using Thunderbird 68+, this method no longer works. Please use the Mork parser." when selecting 'settings'.   Under 'Monitoring', I choose 'using Mork index files', clear accounts (after warning was displayed), but cannot add any because the pull-down on the 'add' menu is empty.

**Comment by Kr1ss-XD** [comment]
On :
- i3wm 4.17.1
- Qt 5.13.2
- Thunderbird 68.2.2
- Birdtray 1.7.0

I don't experience this issue, so this doesn't actually seem to be an i3 problem (at least not applying to the above combination of versions).

**Comment by gyunaev** [comment]
what is the output of `wmctrl -l` for Thunderbird window?

**Comment by Flakebi** [comment]
I have the same problem on NixOS, 1.6 works, 1.7.0 shows the red X. Even for the same running Thunderbird instance, so this seems to be a regression.
As reported above, everything else, also hiding and showing the Thunderbird window, works fine.

Output of `wmctrl -l`:
```
0x00a00010  0 majestix Inbox - Flakebi - Thunderbird Daily
0x01800019  0 majestix …
```

**Comment by gshegosh** [comment]
I think the reason this doesn't work is this - the default setting is "- Mozilla Thunderbird" but wmctrl -l shows "– Mozilla Thunderbird" - note the longer dash – compared to -
I've changed the setting and it works for me on Linux Mint.

**Comment by Phitherek** [comment]
@gshegosh That's it! I've never noticed that the dash is another character there. I know it's not Birdtray's fault but this infomation could be added somewhere to avoid further confusion. Closing this issue now.
