### ISSUE TITLE
Cannot select accounts if using Mork Index

### ISSUE THREAD

**Issue by dalexnagy** [gyunaev/birdtray#203]
**OS**: Ubuntu 18.04.3
**Birdtray version**: 1.7.0
**Thunderbird version**: 68.2.1
**Birdtray origin**: From installer
**Qt version**: _NA_ 

**Description**
I get "Error retrieving accounts: Cannot access the database. If you're using Thunderbird 68+, this method no longer works. Please use the Mork parser." when selecting 'settings'. Under 'Monitoring', I choose 'using Mork index files', clear accounts (after warning was displayed), but cannot add any because the pull-down on the 'add' menu is empty.

**Expected behavior**
I expected to see the two email accounts defined in the profile.

**To Reproduce**
Select 'settings' from BirdTray

**Comment by dalexnagy** [comment]
My error - I was selecting the '.default' file for the profile when I should have only specified the folder containing this file.  This is working now.

**Comment by dalexnagy** [comment]
T'Bird was installed when I installed Ubuntu and I have used it many, many years.  The profile was in a non-standard folder because when I was dual-booting Win7 and Ubuntu, I put my T'Bird and Firefox profile folders on an NTFS volume accessible by both OSes.  In this manner, I could fully access the same up-to-date emails and bookmarks whether I was on Win7 or Ubuntu. 

I removed the Win partition a couple of years ago and now boot only Ubuntu, running Windows10 in a VM when I need it.  I was simply too lazy to remove the NTFS partition until earlier this year when I backed it up, removed it, extended my /home partition into the space, and restored/merged folders.  I just left my Mozilla profiles in the folders they were in.  I guess I need to find out which are the native folders for T'Bird and Firefox and go back to that structure.

All seem to be working now on BirdTray.

Dave

**Comment by Abestanis** [comment]
Ah, ok, thank you for your response. To save you the trouble of searching, [these](https://github.com/gyunaev/birdtray/blob/master/src/utils.cpp#L224) are all the standard locations on Linux that we know of. The first one is probably what you want.

**Comment by codingKerensa** [comment]
I'm having the same issue on Linux Mint 19.2. I wonder if it is because my profile.ini points to a different location. I've tried selecting both ~/.thunderbird and the main thunderbird folder, but the profiles dropbox still remains empty.

Does BirdTray check the profiles.ini for paths to the actual profiles? My ~/.thunderbird basically only has installs.ini and profiles.ini in it. Here's the profiles.ini:

```
[InstallFDC34C9F024745EB]
Default=/home/user/Keep/thunderbird

[Profile0]
Name=default
IsRelative=0
Path=/home/user/Keep/thunderbird
Default=1

[General]
StartWithLastProfile=1
Version=2
```


Or maybe I'm just missing something simple?

**Comment by dalexnagy** [comment]
Have you tried specifying '/home/user/Keep/thunderbird' only for the location of the profiles in BirdTray?

**Comment by codingKerensa** [comment]
I have, yes. Sorry, it was probably a bit unclear above. No result.

**Comment by Abestanis** [comment]
We don't parse the `profiles.ini` at all.
As it says in the dialog, you need to `Select the directory that contains the Thunderbird profiles.`
In case that is still unclear, the default profile is normally located at `~/.thunderbird/xxxxx.profile`, where `xxxxx.profile` is the profile folder and `~/.thunderbird` the folder you need to select.
Your `profiles.ini` suggest that your profile is located at `/home/user/Keep/thunderbird`, so you need to select `/home/user/Keep`.

**Comment by codingKerensa** [comment]
Right, so it was something simple I was missing. Not the most intuitive configuration in my case, but I guess in most cases Birdtray handels it on its own. Thanks!
