### ISSUE TITLE
Please test the new unread notification parser

### ISSUE THREAD

**Issue by gyunaev** [gyunaev/birdtray#21]
I have implemented Mork parser, which implements unread notifications differently, by querying the actual MSF file. This it will work with search disabled, and should work in many other scenarios.

If you'd like to test it, please do the following exactly:

1. Compile new Birdtray and start it.
2. Open Settings, go to Advanced tab, and change the unread parser to Mork. It will clear your account list in Birdtray, and exit it.
3. Start Birdtray again, open Settings, go to Accounts, and add your MSF files to the list.
4. Apply settings.

Now you should be using the Mork parser. Try it by making a message unread in Thunderbird, the counter should adjust immediately.

This should likely fix #19, #18, #17, and #14, and is eventually going to be the preferred method, so please test.

**Comment by DisposaBoy** [comment]
It's working great! Thanks :)

**Comment by JackDinn** [comment]
Yea , looks to be working fine. Cheers.

**Comment by geckolinux** [comment]
Unfortunately it's not working for me. It appears to be showing a massively large number, it's too small to tell:

![screenshot_20181004_131533](https://user-images.githubusercontent.com/2692138/46494159-ca41b500-c7d7-11e8-9431-943526b40c20.png)

**Comment by geckolinux** [comment]
I changed to a different .msf file for a different account, and now it's showing 21 new messages. The account has 0 new messages.

![screenshot_20181004_135151](https://user-images.githubusercontent.com/2692138/46496105-c49a9e00-c7dc-11e8-90ec-21d72ebb2cd6.png)

**Comment by geckolinux** [comment]
OK, it looks like it's working now. I ran the msf repair tool that is built into Thunderbird. After over 12 years on this same profile I imagine it was about time... :-)

Thanks *very much* for providing this tool, looks like it should work well now.

**Comment by mihav** [comment]
Works for me. Thanks!

**Comment by gyunaev** [comment]
You can also just delete the MSF file and restart TB.

**Comment by authreq** [comment]
Perfect! Works great for me.

**Comment by MicioMax** [comment]
Not working for me...
When I added at first inbox.msf the icon was showing many incoming e-mails.
I followed the suggestion and repaired the inbox.msf, then it showed (correctly) no mail.
But, when I receive new mails, it doesn't show anything either.
If I remove and add again this account, it keeps showing incoming e-mails, but there are none.

**Comment by MicioMax** [comment]
Ok... I had some 8000+ e-mails in my incoming folder.
I moved all of them in an archived one, and now it works. Probably the file was too big for your parser!

Thank you again for your work!

**Comment by geckolinux** [comment]
Unfortunately one of my 3 main accounts that I want to receive notifications for simply won't work. I tried to repair it several times in Thunderbird, but Birdtray still continues to flash some long number or text that I can't read due to the small size. I ran Birdtray from the command line, but it's also not showing anything helpful. I can't figure out why this inbox with 5125 messages doesn't work, whereas another account with over 8000 messages does...

**Comment by MicioMax** [comment]
> ....whereas another account with over 8000 messages does...

In my case, with 8000+ messages, it DOESN'T work. I had to move all messages into an archive folder (so removing them from inbox one), and THEN it worked.
I think 8000 messages are too much for the parser.

**Comment by geckolinux** [comment]
@MicioMax Is yours also flashing some unreadable text in the tray icon?

**Comment by authreq** [comment]
MorkParser loads all .msf database in memory and parses _whole_ file for every incoming message. This algo is not optimal for large Inboxes.

**Comment by gyunaev** [comment]
Yeah, but that's the only way to parse this format (it is incredibly weird). Use SQlite parser for huge inboxes, or wait for #12.

**Comment by geckolinux** [comment]
It's just weird that the only one of my four accounts that won't work with Mork is not the biggest one by a long shot. I even tried deleting its MSF files and re-downloading them, but it still flashes something in Birdtray.

**Comment by geckolinux** [comment]
Sorry to spam this thread. I think I finally got the SQL parser to work. I had to start by adding my Gmail accounts to a completely fresh new TB profile. (I also tried Mork with the configured new profile, but the behavior was still as I described before on 1 of the 3 accounts I want to monitor.)

**Comment by gyunaev** [comment]
Seems to be working fine.
