### ISSUE TITLE
Birdtray icon keeps flashing after mail is read

### ISSUE THREAD

**Issue by TheBudda** [gyunaev/birdtray#214]
**OS**:  Windows 10
**Thunderbird version**:  68.3.1 (32-bit)
**Birdtray origin**:  1.7.0
**Qt version**: _NA_ 
**Description**
Birdtray icon keeps flashing after mail is read. Stops flashing when mail is deleted

**Expected behaviour**
Birdtray icon to stop flashing when mail is read not when deleted

**To Reproduce**

1.  install Birdtray and Thunderbird
2.  send mail to Thunderbird and watch the flashing icon when mail is read

**Comment by Hobbix** [comment]
I think this is the same problem.
https://github.com/gyunaev/birdtray/issues/95#issuecomment-567576345

**Comment by Abestanis** [comment]
Does the number on the Birdtray system tray icon change or is it also not updated when you mark the email as read?

**Comment by TheBudda** [comment]
@Abestanis the issue is when the email is read, the icon does not change, keeps flashing telling me I got new mail

**Comment by Abestanis** [comment]
Yes, the question is if Birdtray detects that you have no new mail or if it doesn't. There is a simple way to check that: If it isn't enabled, enable the `Show unread count` in the `General` settings tab. When you get new mail and mark the new mail as read, the counter should go down and the flashing should stop. If the counter does drop, but the flashing continues, then you found this is not the same as #95 and we can investigate further.
If the counter doesn't drop, this is likely the same problem as #95. To make sure, you can open settings dialog while Birdtray is flashing when it shouldn't, and then close the settings dialog with the  `Ok` button. That will force an update of the unread counter and the flashing should stop. If that is the case, please close this issue and subscribe to #95 to keep yourself informed if we ever find a fix for that problem.

**Comment by gyunaev** [comment]
Shall be fixed.
