### ISSUE TITLE
make birdtray usable without using its monitoring capabilities

### ISSUE THREAD

**Issue by sans-c** [gyunaev/birdtray#216]
If you do not configure monitoring (or had it configured but chose to "disable" it again), birdtray keeps asking if you'd like to set up folders for monitoring on startup. Due to a few open issues, I'd like to resort to Thunderbird's notifications entirely and leave monitoring off in birdtray.

If this behaviour is by design, I request to change it, for example ask only once and refer to the settings. If its a bug, you now know about it. :)

**Comment by galneon** [comment]
Please god yes. Every reboot the nag comes up.

**Comment by gyunaev** [comment]
Please dont spam with "me too" or "OMGwhenyougonnafixit". Its free software with published source code - either fix it yourself, or wait until developers have time to fix it.

**Comment by Abestanis** [comment]
@galneon You can use the emoji feature of Github in the top right corner of every comment. Adding a 👍 or a ❤️ will let us know that you want the same thing without generating spam emails or notifications.

**Comment by galneon** [comment]
@Abestanis Done, and apologies. Embarrassing late-night post. ;)
