### ISSUE TITLE
Unread emails count shows wrong number

### ISSUE THREAD

**Issue by nicolamori** [gyunaev/birdtray#217]
**OS**: ArchLinux 64 bit
**Birdtray version**: 1.7.0
**Thunderbird version**: 68.3.0
**Birdtray origin**: ArchLinux's AUR
**Qt version**: _NA_

**Description**
The tray icon shows 4 unread messages event when I have no unread messages. I traced down the problem to the fact that I have 4 email accounts in Thunderbird, and when I configure BirdTray to monitor one of the Inbox folders then the unread count increases. This has not a 1:1 relationship, i.e. I don't get exactly 1 unread message for each Inbox folder, since for one Inbox I get 0 and for another I get 2. All the inboxes are on IMAP servers. The button for fixing the unreaad message count in the General tab of the BirdTray Settings dialog is disabled so I cannot try it to fix the problem.

**Comment by nicolamori** [comment]
I have been able to partially fix the problem by marking all the messages in the inboxes as unread and then all as read. This reduced the number of unread to 1, and I was not able to further reduce it. So I removed all the monitored folders and then added them again, and now I have no unread message, as it ought to be.
I don't understand what happened exactly; also, during the process the unread count went up with no apparent reason. I'll keep this issue open for a while in case this happens again.

**Comment by nicolamori** [comment]
The problem appeared again some minutes ago. One of my inboxes makes the unread count number grow by 1 even if there's no unread email in that inbox. I tried again to mark all as unread and then as read, to no avail. Also removing the monitoring of the inbox and then re-adding it had no effect, so none of my workarounds fixes the problem this time.

**Comment by ampped101** [comment]
Same exact issue on Windows x64

**Comment by dochdoch** [comment]
Same exact thing here on Mint 19.3 (64-bit) Thunderbird 68.4.1 (64-bit) Birdtray 1.7.0 QT 5.9.5

Three accounts, all IMAP. Randomly the unread counter raises to 1, but there are no unread mails. The fix button is greyed out. Every time I open the settings dialog I am presented with a pop-up error message: Error retrieving accounts: Cannot access the database. If you're using Thunderbird 68+, this method no longer works. Please use the Mork parser.

I already have the Mork parser setup properly. I have repeatedly removed and added the accounts again, the error message still pops up every time I open the settings and the unread count is almost never correct.

**Comment by nicolamori** [comment]
@dochdoch I don't get the error dialog about the Mork parser.
Recently the behavior has been correct for quite a while, with wrong email count appearing randomly from time to time when I get new messages, but not often, and seemingly being self-fixed after a while. In this moment I am getting the correct count.

**Comment by RYRNRY** [comment]
Windows 7 - 64 bit 
Birdtray version 1.7.0 compiled at Dec  3 2019 22:57:14.

Birdtray does not update the Count once Emails are read.  
Sometimes Clicking...  
   Birdtray -> Settings -> General -> OK button  
will update the Counter, but not always.

**Comment by rkfg** [comment]
Same here, on 1.7.0 from Debian testing. I always see 1 unread message upon start though all messages are marked read. A temporary workaround is to right click the tray icon and then click `Ignore unread emails`. Unfortunately, it's not preserved between restarts but it works fine during the session. New messages will be shown correctly and the number will go to zero when you read them, everything is as is should be. The `Fix` button is also disabled for me, I wonder why (didn't dig into the code yet).

**Comment by Abestanis** [comment]
Could you guys please test if #245 fixes the problem for you?
Otherwise we need the debug output (Start Birdtray with the `--debug` command line option).
And thank you for reporting this.

**Comment by ampped101** [comment]
> Could you guys please test if #245 fixes the problem for you?
> Otherwise we need the debug output (Start Birdtray with the `--debug` command line option).
> And thank you for reporting this.

Worked for me! Much thanks to everyone on this project.

**Comment by rkfg** [comment]
@Abestanis well, now it doesn't show any unread emails. I sent myself a message and the icon was unchanged, even after a restart.

**Comment by rkfg** [comment]
Log from unpatched version when no unread emails present:
```
Triggering the unread counter update
Window ID found: 0
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/192.168.180.2/INBOX.msf: 0
Window ID found: 0
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 1
unreadCounterUpdate 1
Window ID found: 0
Window ID found: 0
Starting Thunderbird as '/usr/bin/thunderbird '
Window ID found: 0
Window ID found: 0
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 1
Window ID found: 2600010
Window removed from taskbar
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/192.168.180.2/INBOX.msf: 0
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 1
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 1
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 1
```
Patched version (no mail):
```
Triggering the unread counter update
Window ID found: 0
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/192.168.180.2/INBOX.msf: 0
Window ID found: 0
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 0
Window ID found: 0
Window ID found: 0
Starting Thunderbird as '/usr/bin/thunderbird '
Window ID found: 0
Window ID found: 2600010
Window removed from taskbar
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 0
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 0
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/192.168.180.2/INBOX.msf: 0
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 0
```
Marking one mail unread:
```
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 0
Triggering the unread counter update
Unread counter for /home/rkfg/.thunderbird/zk6ta3fz.default/ImapMail/imap.gmail.com/INBOX.msf: 0
```

**Comment by rkfg** [comment]
I added row dump like this:
```diff
diff --git a/src/unreadmonitor.cpp b/src/unreadmonitor.cpp
index 84cb727..e903071 100644
--- a/src/unreadmonitor.cpp
+++ b/src/unreadmonitor.cpp
@@ -301,20 +301,26 @@ int UnreadMonitor::getMorkUnreadCount(const QString &path)
         {
             MorkCells cells = rit.value();
 
+            QMap<QString, QString> row;
             for ( int colid : cells.keys() )
             {
                 QString columnName = parser.getColumn( colid );
-
+                QString val = parser.getValue(cells[colid]);
+                row[columnName] = val;
                 if ( columnName == "unreadChildren" )
                 {
                     bool correct;
                     unsigned int value = parser.getValue(cells[colid ]).toUInt( &correct, 16 );
-
                     if ( correct )
                         unread += value;
                     else
-                        Utils::debug("Incorrect Mork value: %s", qPrintable( parser.getValue(cells[colid ]) ));                }
+                        Utils::debug("Incorrect Mork value: %s", qPrintable( parser.getValue(cells[colid ]) ));
+                }
+            }
+            for (auto k: row.keys()) {
+                Utils::debug("Row[%s] = %s", qPrintable(k), qPrintable(row[k]));
             }
+            Utils::debug("-----------------");
         }
     }
     else
```
The unread children row for me is:
```
Row[children] = 9
Row[threadFlags] = 0
Row[threadId] = 3513
Row[threadNewestMsgDate] = 5cacaa96
Row[threadRoot] = 3513
Row[unreadChildren] = 1
```
However, I couldn't find any messages with thread id 3513. It might be a bug or database corruption in Thunderbird (a ghost thread or something). What helped me is: right click `Inbox` (or whatever folder you monitor) ⇒ Repair Folder. After that it redownloads messages and seemingly fixes the inconsistensies.

**Comment by Abestanis** [comment]
@rkfg Thank you for testing the patch and for the detailed analysis. Did repairing the `Inbox` folder also fix the unread counter with the patch in #245?

@dochdoch Do you still have the issue with the error dialog? If so, I have trouble reproducing it, could you please open a separate issue and if possible include your [config file](https://github.com/gyunaev/birdtray#linux-package-installation)?

**Comment by abenjak** [comment]
My easy fix, just in case:

(BirdTray 1.7.0, TB 68.5.0, Linux Mint 19.1)
I had exactly the same problem as posted above: Mork-monitoring `inbox` of 4 IMAP accounts, of which one account started to show 2 unread messages recently (FYI, it was not my Gmail). In Thunderbird tried to `select all messages` --> `mark as read` to no avail. Tried the same from the Outlook server over the Internet browser to no avail.

Fix: in Thunderbird, right-click on the problematic inbox folder in the `Folder Pane` on the left, then choose `Mark Folder Read`. And _voilà_, the unread ghost messages disappeared from Birdtray instantly.

**Comment by abenjak** [comment]
`Birdtray 1.7.0, Linux Mint 19.1, TB 68.7.`
Same problem as above, 1 out of 3 inboxes erroneously showing 2 unread messages (not a gmail). **Repairing the problematic folder in TB fixed the problem!**

1. temporarily uncheck `Check for new messages every ... minutes` in the Server setting, just in case.
2. right-click on the inbox folder -> `Properties` --> `Repair Folder`.

**Comment by snowbound** [comment]
This is still an ongoing issue with TB 102.5.1. If you have ignored a thread the taskbar new message count still shows any posts to that thread. I have to tell TB to check for new mail for the email account again to get the new mail message count to remove these counts. This has been a problem for years and the repair folder is not going to solve it permanently it is simply going to come back the next time that ignored thread gets another post to it.
