### ISSUE TITLE
Unable to configure monitoring on Windows

### ISSUE THREAD

**Issue by PRSoftware** [gyunaev/birdtray#218]
**OS**: Windows 7
**Birdtray version**: 1.7.0 32 bits
**Thunderbird version**: 60.9.2 
**Birdtray origin**: From installer

**Description**

In the "Monitoring" tab, I select the method "using Mork index file". 
When I click on the "Add" button, a popup ask to select the Thunderbird profile but nothing is proposed in the list and I cannot pass this step of configuration.
My TB profile is not located on the "standard" directory but on D:\Tools\Thunderbird\Profile which is correctly indicated in the file C:\Users\Xxx\AppData\Roaming\Thunderbird\profiles.ini.

**Expected behavior**

Please, let me know how to configure BirdTray.

**Screenshots**

![PrtScr capture](https://user-images.githubusercontent.com/59197612/71407995-f8115480-263c-11ea-9678-291d5515918c.jpg)

**Comment by Abestanis** [comment]
Use the back button in the top left corner. That will take you to the page where you can select the directory which contains the Profile folders. In your case, I assume `Profile` is the profile folder, so you want to select `D:\Tools\Thunderbird`.

**Comment by PRSoftware** [comment]
Ok, it's all good :-)

Thanks a lot.
