### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Peter2121** [gyunaev/birdtray#219]
**OS**:  FreeBSD 11.3-RELEASE-p5
**Birdtray version**: 1.7.0
**Thunderbird version**: 68.1.0
**Birdtray origin**: Built from sources
**Qt version**: 5.12.2

**Description**
Birdtray was started with Thunderbird. Then I closed Thunderbird and locked the screen (Birdtray remains open). After 3 days I unlocked the PC - the RAM (16GB) and the SWAP (8GB) were 100% used, at the top of the list was Birdtray. After killing it the RAM was free again.

**Comment by Abestanis** [comment]
Thank you for reporting this. Could you please test #227 to make sure it fixes the leak you were experiencing?
