### ISSUE TITLE
Changing the font weight of unread counter shows no effect

### ISSUE THREAD

**Issue by s-m-e** [gyunaev/birdtray#22]
First of all, thanks a lot for this great add-on. The concept is good - it's actually less of an add-on and more a Thunderbird babysitter ;)

# Expected behavior

Changing the font weight of the unread counter should allow to make the text bold.

# Actual behavior

Changing to to any value greater than 100% ... 120% ... 200% ... does not show any effect. Font remains "slim". 

# Workaround

Use a font, which is bold by design.

# Platform

* Birdtray, compiled from commit 322ede18c392f57316ee6dbf782481b9e23c4ed7 (latest commit in `master` as of writing this bug report), using the Mork parser
* Thunderbird 60
* Qt 5.6.2
* Xorg 7.6
* Linux 4.4.143 x86_64 with KDE

(This is a default openSUSE Leap 42.3 system, highest patch level.)

**Comment by gyunaev** [comment]
Is it limited to a specific font, or it doesn't work with any font?

**Comment by s-m-e** [comment]
I tried about 10 of my "default" fonts (the Noto family, Sans, some standard MS fonts) - none of them worked.
