### ISSUE TITLE
Birdtray-1.7.0-Win-x64 faild to start on win10-x64

### ISSUE THREAD

**Issue by Harreth** [gyunaev/birdtray#220]
After the installation of Birdtray-1.7.0-Win-x64.exe
win10 x64 Version 1909 (OS Build 18363.535)
Thunderbird V68.3.1 X64 installed on system
launching the installed birdtray app results to this error:
(birdtray.exe - System Error
The code execution cannot proceed because 
VCRUNTIME140_1.dll was not found. Reinstalling the program 
may fix this problem.)
I Tryed to re install for all users, current user, run with compatibility, ended up with the same error message. 

thanks

**Comment by MarkFirewhal** [comment]
This was closed before an answer was reported:
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

You should be able to fix this problem by downloading them directly from Microsoft.
