### ISSUE TITLE
Settings dialog does not ask for Profiles folder when addind first Mork account

### ISSUE THREAD

**Issue by GerhardPehland** [gyunaev/birdtray#229]
**OS**: 
**Birdtray version**: 
**Thunderbird version**: 
**Birdtray origin**: 
**Qt version**: _NA_ 

**Description**

**Expected behavior**

**To Reproduce**

1. 
2. 
3. 
4. 

**Additional context**

**Comment by GerhardPehland** [comment]
Sorry, I messed up, had it all as comments




**OS**: -- Windows 10 Professional, 64 Bit
**Birdtray version**: --1.7.0
**Thunderbird version**: 68.3.1 32 Bit
**Birdtray origin**: From installer
**Qt version**: _NA_  Only fill this, if you compiled Birdtray yourself

**Description**
When I create monitoring accounts using Mork, I am not asked about the profiles folder. I did the same on another machine and could select the profiles path. I did a fresh install on this machine and have no opportunity to select the profiles folder. This is ThunderBird Portable, so the profiles path is not standard, but somewhere in a folder tree along with the binaries and everything else. As a result the Settings dialog shows no email accounts/folders for me to select for monitoring and I am stuck.

**Expected behavior**
Ask me for a profiles folder, when adding the first email account and display all email accounts/IMAP folders found there.

**To Reproduce**
I am using the german version, so some of these button names etc. may be different
1. Do a fresh install of BirdTray
2. go to Settings/Monitoring
3. select Mork from drop down list
4. Click Add

**Additional context**
As I said, it worked before on another machine, but there the sequence was a little different. I had Thunderbird 60 installed, set BirdTray to use SQLite and added accounts, then updated Thunderbird to V68, switched to Mork and was asked for the profiles folder when adding the first account. All works well there This is the same Thunderbird install on a removeable drive (hence the portable version). I tried using SQlite first and then switch to Mork this machine, but no luck, it simply won't ask for the profiles folder.

**Comment by Abestanis** [comment]
Same problem as #218. You can use the back button in the top left corner to select the profiles folder.

**Comment by GerhardPehland** [comment]
Thank you, back button worked indeed.

**Comment by Abestanis** [comment]
To explain what is happening: There are two pages of that dialog which are skipped in your case. The first lets you select the directory that contains the profiles folders, the second one lets you select a profile. Your system must have an empty Thunderbird profile at the standard path, so we skipped the first two pages and autoselected the empty profile.

**Comment by GerhardPehland** [comment]
Makes sense, on this machine I once had a standard Thunderbird install many moons ago before switching to the portable version on the external drive.

Tkank you once again!
