### ISSUE TITLE
Stopped working recently

### ISSUE THREAD

**Issue by chrisgraham** [gyunaev/birdtray#242]
**OS**: Linux chrisgraham-iMac 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Birdtray version**: Latest from git as of a few minutes ago (but also from months ago, same issue)
**Thunderbird version**: 68.4.1
**Birdtray origin**: From source
**Qt version**: Using Qt version 5.12.4 in /usr/lib/x86_64-linux-gnu

**Description**
No new message updates show on tray icon

**Expected behavior**
Tray icon shows number when there are new unread messages

**To Reproduce**
Receive an email (e.g. send one to yourself)

**Additional context**
I've had this for a few days, I figure most likely it came in when my thunderbird package updated 10 days ago...
thunderbird:amd64 (1:68.2.2+build1-0ubuntu0.19.10.1, 1:68.4.1+build1-0ubuntu0.19.10.1)

I can workaround the problem by having it scan the smart mailboxes inbox.
Note I was very careful to confirm the files behind the real mail boxes I was monitoring (and failing to get results for) did have updated messages coming through and updated mtimes on the filesystem.

**Comment by Wizzard033** [comment]
I have the same issue, but I'm on Windows x64 using Thunderbird 68.4.2 (32-bit) and using the latest 1.7 release build instead of the latest nightly build

**Comment by chrisgraham** [comment]
I recently tried https://github.com/Abestanis/birdtray/tree/fix/wrong_num_unreads as I needed that patch. That patch worked for me, but I wanted to pass on the information it doesn't make any change to this bug here.

I also wanted to note I get an unread count of '2' when I have just one unread email in my inbox when monitoring the smart mailbox. I can live with that though.

**Comment by Abestanis** [comment]
This might be the same as #95.

**Comment by chrisgraham** [comment]
> This might be the same as #95.

I doubt it. I messed a lot with the settings and closing and reopening everything, to no avail.

**Comment by chrisgraham** [comment]
> I also wanted to note I get an unread count of '2' when I have just one unread email in my inbox when monitoring the smart mailbox. I can live with that though.

To be clear, this is unrelated to the `wrong_num_unreads` pull request. I am just remarking the minor issue with monitoring smart folders, as per my original workaround.

I sent myself an email and from debug I get...

```
Triggering the unread counter update
Unread counter for /home/chrisgraham/.thunderbird/7f98moaj.default/Mail/smart mailboxes/Inbox.msf: 2
unreadCounterUpdate 2
```

And to be completely sure it's not an issue with the commit, I ran my regular build and did the same...

```
Triggering the unread counter update
Unread counter for /home/chrisgraham/.thunderbird/7f98moaj.default/Mail/smart mailboxes/Inbox.msf: 2
unreadCounterUpdate 2
```

**Comment by Abestanis** [comment]
We have created a script that can remove personal information from mork files. You can find it [here](https://github.com/gyunaev/birdtray/tree/master/contrib/anonymizeMork).
If you still have the issue that Birdtray detects the wrong number of unread emails, please anonymize the corresponding mork file using the script and upload it here. Please also specify how many unread emails are shown in the Thunderbird user interface for that mail folder.
Maybe we can then find out where the wrong number comes from.

**Comment by chrisgraham** [comment]
Actually it looks like #95 does fix this. I did a noob thing... cloned your fork but forgot to checkout the fix branch. Doing that now, and recompiling, it seems to have fixed this issue. So I'll close for now.
If I get issues again in the future I'll proceed as advised. Thanks for doing what you're doing.
