### ISSUE TITLE
Ability to select which display that birdtray displays notifications on.

### ISSUE THREAD

**Issue by CForChrisProooo** [gyunaev/birdtray#243]
**Description**
When Gaming or Recording my screen I'd like to be able to have my notifications appear on a second monitor as to not disturb me.

**Example**
An option in birdtray settings to select the display or position on screen that notifications appear.

**Comment by Abestanis** [comment]
Are you referring to the notification that is send by Thunderbird when new mail arrives? If so we unfortunately have no control over that. You might want to watch #226 or #122, if we implement that we might be able to provide a configuration for your request.
