### ISSUE TITLE
"Fix the unread message count" functionality unclear

### ISSUE THREAD

**Issue by chrisgraham** [gyunaev/birdtray#246]
The "Fix the unread message count"'s "Fix" button is always greyed out. Checking the code it's because it won't work on the mork method.
However, the mork method is practically mandatory now.
I suggest either just removing the legacy method stuff, or at least putting a note on the "Use this tool if..." string saying it doesn't work with the mork method.

**Comment by Abestanis** [comment]
I totally agree with you, it is confusing. Removing the sqlite parser was already proposed in #181, but got rejected because
> It is possible that they'd reverse the change [that breaks the sqlite parser] in future Thunderbird.

@gyunaev Do you want to revisit that?
As an alternative, we could hide the button, if the mork entry is selected.

**Comment by atroxix** [comment]
How should this unread count be fixed without that?

**Comment by atroxix** [comment]
> How should this unread count be fixed without that?

Sorry, found it here:
https://github.com/gyunaev/birdtray/issues/217#issuecomment-579705447

**Comment by gyunaev** [comment]
Removed it in new PR.

**Comment by Abestanis** [comment]
#294
