### ISSUE TITLE
Double click not opening TB

### ISSUE THREAD

**Issue by Kev7274** [gyunaev/birdtray#248]
I have the box ticked to open TB when it's doubled clicked,but nothing happens.

**Comment by Abestanis** [comment]
We can't help you if you don't give us any information. Please fill out the issue template if you want to get help.

If you are on Ubuntu, the system actually forces the context menu on a click, so we can't change that (see #103).

**Comment by Abestanis** [comment]
Without information from you, there is nothing we can do.
