### ISSUE TITLE
Permanent message to setup birdtray

### ISSUE THREAD

**Issue by snIP3r23** [gyunaev/birdtray#249]
**OS**: WIN 10 64
**Birdtray version**: 1.7.0
**Thunderbird version**: 68.4.2
**Birdtray origin**: from installer Birdtray-1.7.0-Win-x64.exe

**Description**
Permanent message to setup birdtray. After installation, every time i start birdtray i get the message 
Would you like to set up Birdtray?
You have not yet configured any email folders to monitor. Would you like to do it now?
This message window appears every time i start birdtray, no matter what i choose (yes or no)

**Expected behavior**
No setup message appears after i clicked no.

**To Reproduce**
Install birdtray and start it afterwards. Then, after every start the Message appears.

**Comment by Abestanis** [comment]
You will be happy to here that we added a `Don't ask again` button in #222. This will be in the next version. Until the new version is released, just configure Birdtray to watch any one email folder.
