### ISSUE TITLE
compile error in Ubuntu 18.04

### ISSUE THREAD

**Issue by jeremyj** [gyunaev/birdtray#25]
Hello,

I'm getting a compile error in Kubuntu 18.04.
```
/usr/lib/qt5/bin/moc -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jeremy/Build/birdtray/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include trayicon.h -o moc_trayicon.cpp
usr/include/c++/7/bits/stl_relops.:67: Parse error at "std"
Makefile:452: recipe for target 'moc_trayicon.cpp' failed
make: *** [moc_trayicon.cpp] Error 1
```
Any idea what the problem could be?

Thanks

**Comment by aamadis** [comment]
I'm also getting this same error, but on 16.04.

**Comment by aamadis** [comment]
Finally got this to compile. Tried many times to install a qt version that was 5.6 or higher but the upgrade never "took" in Ubuntu 16.04. "qmake --version" always showed 5.5.1 in usr/lib/x86_64-linux-gnu. Seems higher versions of qt don't automatically install in that folder, so I manually copied qt 5.9 files into that folder and deleted the original qt 5.5.1 files. Finally the compile worked, But . . . . when I ran the executable birdtray, the settings dialog appeared, but not the actual systray icon. And now that I have picked my settings and closed that dialog window, I have nothing happening when I run birdtray. The System Monitor shows it is running but no icon at all. I use tint2. Don't know if that is the problem or not.

**Comment by gyunaev** [comment]
Some window managers hide icons unless you force them to show explicitly. This is the case with KDE, for example. Maybe with tint too?

**Comment by gyunaev** [comment]
> I'm getting a compile error in Kubuntu 18.04.

What is the output of `qmake-qt5 -v` ?

**Comment by jeremyj** [comment]
> > I'm getting a compile error in Kubuntu 18.04.
> 
> In my case using kubuntu 18.04, I found out that both the latest stable package and master branch had a pre-created hidden .qmake.stash file under src/ with links to suse paths. I just deleted this file before invoking qmake, and everything worked (after I manage to install all needed packages, of course).

Thanks @hmorley that fixed it.

**Comment by MrMcX** [comment]
@hmorley's solution solved it for me too, thank you
