### ISSUE TITLE
Auto option in KDE - may it work

### ISSUE THREAD

**Issue by leonpollak** [gyunaev/birdtray#252]
I am running FC30 KDE and installed birdtray - works perfect,a lot of thanks!
A small possible enhancement: there is an option in KDE plasma tray to show an icon "automatically", i.e. only when it is active/needed.
If set to AUTO, the KMail notifier's icon was shown only when there was an unread message. Otherwise the icon was hidden.
It will be really great if this option will work with BirdTray too.
Many thanks again!!!

**Comment by Abestanis** [comment]
Thank you for your feedback! ❤️

This was already requested in #96 and was recently implemented in #233, so this feature will be available in the next release.

**Comment by Abestanis** [comment]
Since #233 was merged into master and what you requested will be available in the next release, I'm going to close this issue.

**Comment by fabianski7** [comment]
This function is really great for those who use plasma kde, but I think the icon should still be in the system tray, no?

Just like the notification icon, if there is one unread [it is displayed with priority](https://upload.vaa.red/wo1Eh#UzUSIbG1Uj1yTaIuAaPAQUxEZW4lBhAz), if not [it is grouped together with the others](https://upload.vaa.red/2twZr5#ou7lfjAxP9gAqE92iRGwtKbzB6szPOBA).
