### ISSUE TITLE
Birdtray causes high idle cpu on KDE

### ISSUE THREAD

**Issue by tnilzon** [gyunaev/birdtray#26]
This is on Manjaro KDE and birdtray-git (latest).
When Birdtray is running (just sitting in the tray and no notification) the system idle cpu usage rises to a constant level of about 5-6% for process 'kwin_x11' and about 3-5% for process 'plasmashell'. When Birdtray is killed the idle cpu settles down to almost 0%. There must be some cpu leakage with Birdtray? Note: The Birdtray cpu is as described above regardless of if Thunderbird is running or not.
Really hope there is a fix for this.

Birdtray is running:
![birdtray running](https://user-images.githubusercontent.com/6920015/46689955-61a46f00-cc01-11e8-9b3c-4737dace0072.png)

Birdtray NOT running:
![birdtray not running](https://user-images.githubusercontent.com/6920015/46689963-69fcaa00-cc01-11e8-9e02-28aa253396b0.png)

**Comment by gyunaev** [comment]
The blinker indeed puts pressure on kwin; disable blinking in settings and please let me know.

Also 171756d should improve the CPU usage.

**Comment by JackDinn** [comment]
hmm, yes it does use 5 to 7% cpu. not when its flashing or indicating it's when its idle, all the time. I had checked the system usage of birdtray before but never realized that the extra cpu usage of kwin_x11 & plasmashell was due to birdtray but i had noticed it.

No improvement with latest commit unfortunately.

**Comment by tnilzon** [comment]
Yes, just to be clear. The cpu issue is with Birdtray in "idle" condition, just sitting in the tray and **not** blinking.

**Comment by JackDinn** [comment]
its still high (7% ish, and thats just plasmashell) for me anyhow. 
I have made a really quick version. It works for me and iv got the cpu usage down to next to nothing. if @tnilzon might want a look at my repos you will see it. Its fine for me on KDE.

**Comment by tnilzon** [comment]
Great news, thanks!
