### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by zoof** [gyunaev/birdtray#260]
**OS**:  Debian Buster 64 bit
**Birdtray version**: 
Current release.
**Thunderbird version**:  68.5.0
**Birdtray origin**:  Trying to compile.
**Qt version**:   5.11.3+dfsg1-1+deb10u3

**Description**

Dependencies according to README.md installed but compilation fails.

    cmake -DCMAKE_BUILD_TYPE=Release ..

works fine but

    cmake --build .

results in compilation errors.

    <snip>
    [ 45%] Building CXX object CMakeFiles/birdtray.dir/src/dialogsettings.cpp.o
    /home/tct/birdtray/src/dialogsettings.cpp: In constructor ‘DialogSettings::DialogSettings(QWidget*)’:
    /home/tct/birdtray/src/dialogsettings.cpp:83:5: error: ‘onlyShowIconOnNewMail’ was not declared in this scope
         onlyShowIconOnNewMail->setChecked(settings-    >onlyShowIconOnUnreadMessages);
         ^~~~~~~~~~~~~~~~~~~~~
    /home/tct/birdtray/src/dialogsettings.cpp: In member function ‘virtual void DialogSettings::accept()’:
    /home/tct/birdtray/src/dialogsettings.cpp:197:46: error: ‘onlyShowIconOnNewMail’ was not declared in this scope
         settings->onlyShowIconOnUnreadMessages = onlyShowIconOnNewMail-    >isChecked();
                                                  ^~~~~~~~~~~~~~~~~~~~~
    /home/tct/birdtray/src/dialogsettings.cpp: In member function ‘void DialogSettings::onCheckUpdateFinished(bool, const QString&)’:
    /home/tct/birdtray/src/dialogsettings.cpp:262:9: error: ‘noUpdateIndicator’ was not declared in this scope
             noUpdateIndicator->setVisible(!foundUpdate);
             ^~~~~~~~~~~~~~~~~
    /home/tct/birdtray/src/dialogsettings.cpp:262:9: note: suggested alternative: ‘UpdateDialog’
             noUpdateIndicator->setVisible(!foundUpdate);
             ^~~~~~~~~~~~~~~~~
             UpdateDialog
    /home/tct/birdtray/src/dialogsettings.cpp: In member function ‘void DialogSettings::activateTab(int)’:
    /home/tct/birdtray/src/dialogsettings.cpp:513:9: error: ‘noUpdateIndicator’ was not declared in this scope
             noUpdateIndicator->hide();
             ^~~~~~~~~~~~~~~~~
    /home/tct/birdtray/src/dialogsettings.cpp:513:9: note: suggested alternative:     ‘UpdateDialog’
             noUpdateIndicator->hide();
             ^~~~~~~~~~~~~~~~~
             UpdateDialog
    make[2]: *** [CMakeFiles/birdtray.dir/build.make:326: 
    CMakeFiles/birdtray.dir/src/dialogsettings.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/birdtray.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2

**Expected behavior**

Expect birdtray to be built.

**To Reproduce**

1.  cd birdtray
2.  git pull
3. cd build
4. cmake -DCMAKE_BUILD_TYPE=Release ..
5. cmake --build .

**Additional context**

The last time I tried to build an update on a Debian Stretch system I had no problems. I recently upgraded to Buster and now the build fails.

**Comment by Abestanis** [comment]
Could you try installing `qtbase5-dev-tools` and see if it fixes the problem. If not, please post the output of `git status` and the full Cmake output.

**Comment by zoof** [comment]
Sure.

```
~/birdtray/build$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
~/birdtray/build$ cmake --build .
[  2%] Automatic MOC and UIC for target birdtray
[  2%] Built target birdtray_autogen
[  5%] Generating translations/main_en.qm
Updating '/home/tct/birdtray/build/translations/main_en.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 203 untranslated source text(s)
[  8%] Generating translations/main_de.qm
Updating '/home/tct/birdtray/build/translations/main_de.qm'...
    Generated 203 translation(s) (203 finished and 0 unfinished)
[ 11%] Building CXX object CMakeFiles/birdtray.dir/src/dialogsettings.cpp.o
/home/tct/birdtray/src/dialogsettings.cpp: In constructor ‘DialogSettings::DialogSettings(QWidget*)’:
/home/tct/birdtray/src/dialogsettings.cpp:83:5: error: ‘onlyShowIconOnNewMail’ was not declared in this scope
     onlyShowIconOnNewMail->setChecked(settings->onlyShowIconOnUnreadMessages);
     ^~~~~~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp: In member function ‘virtual void DialogSettings::accept()’:
/home/tct/birdtray/src/dialogsettings.cpp:197:46: error: ‘onlyShowIconOnNewMail’ was not declared in this scope
     settings->onlyShowIconOnUnreadMessages = onlyShowIconOnNewMail->isChecked();
                                              ^~~~~~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp: In member function ‘void DialogSettings::onCheckUpdateFinished(bool, const QString&)’:
/home/tct/birdtray/src/dialogsettings.cpp:262:9: error: ‘noUpdateIndicator’ was not declared in this scope
         noUpdateIndicator->setVisible(!foundUpdate);
         ^~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp:262:9: note: suggested alternative: ‘UpdateDialog’
         noUpdateIndicator->setVisible(!foundUpdate);
         ^~~~~~~~~~~~~~~~~
         UpdateDialog
/home/tct/birdtray/src/dialogsettings.cpp: In member function ‘void DialogSettings::activateTab(int)’:
/home/tct/birdtray/src/dialogsettings.cpp:513:9: error: ‘noUpdateIndicator’ was not declared in this scope
         noUpdateIndicator->hide();
         ^~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp:513:9: note: suggested alternative: ‘UpdateDialog’
         noUpdateIndicator->hide();
         ^~~~~~~~~~~~~~~~~
         UpdateDialog
make[2]: *** [CMakeFiles/birdtray.dir/build.make:262: CMakeFiles/birdtray.dir/src/dialogsettings.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/birdtray.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Abestanis** [comment]
Sorry, that was unclear, I also meant the output of the `cmake -DCMAKE_BUILD_TYPE=Release ..` command. And could you please delete the contents of the build folder before you run the Cmake commands, so Cmake recompiles everything?

**Comment by zoof** [comment]
```
~/birdtray/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tct/birdtray/build
```

**Comment by Abestanis** [comment]
Thank you, could you also post the output of `cmake --build .` after you cleared the build directory and  run `cmake -DCMAKE_BUILD_TYPE=Release ..`. It might contain more information than the snippets you posted above.

In general, we need you to give us as much information as possible, even if you don't think it will be important. I don't have a system with Debian Buster so I can't replicate the problem, which is why I need any information you can provide.

After you run the Cmake commands, there should be a file at `birdtray_autogen/include/ui_dialogsettings.h` in the build folder. Can you please upload that?

**Comment by zoof** [comment]
```
~/birdtray/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tct/birdtray/build
~/birdtray/build$ cmake --build .
[  2%] Automatic MOC and UIC for target birdtray
[  2%] Built target birdtray_autogen
[  5%] Generating ../src/translations/main_de.ts
Updating '../src/translations/main_de.ts'...
    Found 203 source text(s) (203 new and 0 already existing)
[  8%] Generating qrc_resources.cpp
[ 11%] Generating ../src/translations/main_en.ts
Updating '../src/translations/main_en.ts'...
    Found 203 source text(s) (203 new and 0 already existing)
[ 14%] Generating translations/main_en.qm
Updating '/home/tct/birdtray/build/translations/main_en.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 203 untranslated source text(s)
[ 17%] Generating translations/main_de.qm
Updating '/home/tct/birdtray/build/translations/main_de.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 203 untranslated source text(s)
[ 20%] Generating translations/dynamic_en.qm
Updating '/home/tct/birdtray/build/translations/dynamic_en.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
[ 23%] Generating translations/dynamic_de.qm
Updating '/home/tct/birdtray/build/translations/dynamic_de.qm'...
    Generated 8 translation(s) (8 finished and 0 unfinished)
Scanning dependencies of target birdtray
[ 26%] Building CXX object CMakeFiles/birdtray.dir/src/colorbutton.cpp.o
[ 29%] Building CXX object CMakeFiles/birdtray.dir/src/databaseaccounts.cpp.o
[ 32%] Building CXX object CMakeFiles/birdtray.dir/src/databaseunreadfixer.cpp.o
[ 35%] Building CXX object CMakeFiles/birdtray.dir/src/dialogaddeditaccount.cpp.o
[ 38%] Building CXX object CMakeFiles/birdtray.dir/src/dialogaddeditnewemail.cpp.o
[ 41%] Building CXX object CMakeFiles/birdtray.dir/src/dialogsettings.cpp.o
/home/tct/birdtray/src/dialogsettings.cpp: In constructor ‘DialogSettings::DialogSettings(QWidget*)’:
/home/tct/birdtray/src/dialogsettings.cpp:83:5: error: ‘onlyShowIconOnNewMail’ was not declared in this scope
     onlyShowIconOnNewMail->setChecked(settings->onlyShowIconOnUnreadMessages);
     ^~~~~~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp: In member function ‘virtual void DialogSettings::accept()’:
/home/tct/birdtray/src/dialogsettings.cpp:197:46: error: ‘onlyShowIconOnNewMail’ was not declared in this scope
     settings->onlyShowIconOnUnreadMessages = onlyShowIconOnNewMail->isChecked();
                                              ^~~~~~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp: In member function ‘void DialogSettings::onCheckUpdateFinished(bool, const QString&)’:
/home/tct/birdtray/src/dialogsettings.cpp:262:9: error: ‘noUpdateIndicator’ was not declared in this scope
         noUpdateIndicator->setVisible(!foundUpdate);
         ^~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp:262:9: note: suggested alternative: ‘UpdateDialog’
         noUpdateIndicator->setVisible(!foundUpdate);
         ^~~~~~~~~~~~~~~~~
         UpdateDialog
/home/tct/birdtray/src/dialogsettings.cpp: In member function ‘void DialogSettings::activateTab(int)’:
/home/tct/birdtray/src/dialogsettings.cpp:513:9: error: ‘noUpdateIndicator’ was not declared in this scope
         noUpdateIndicator->hide();
         ^~~~~~~~~~~~~~~~~
/home/tct/birdtray/src/dialogsettings.cpp:513:9: note: suggested alternative: ‘UpdateDialog’
         noUpdateIndicator->hide();
         ^~~~~~~~~~~~~~~~~
         UpdateDialog
make[2]: *** [CMakeFiles/birdtray.dir/build.make:262: CMakeFiles/birdtray.dir/src/dialogsettings.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/birdtray.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by zoof** [comment]
birdtray_autogen/include/ui_dialogsettings.h is at: https://www.dropbox.com/s/72qjj45tbpswrbk/ui_dialogsettings.h?dl=0

**Comment by Abestanis** [comment]
Well, that is strange. The header file you send clearly defines the `onlyShowIconOnNewMail` field, just as it should. This could be a compiler bug.

To find out which compiler cmake chose, you can examine the examine the file at `CMakeFiles/CMakeOutput.log` relative from your build directory. It should contain a line that starts with `Compiler: ` and ends with the path to the c++ compiler that was used (e.g. `/usr/bin/c++`).
Run the compiler with `--version` as the argument and post the output here.

We could also try switching the compiler. If the current compiler is `gcc`, you could try to use `clang` and vice versa. Make sure you delete the build folder and reconfigure cmake if you switch the compiler.

If that also doesn't help, try reconfiguring cmake with verbose makefiles: Add the parameter `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` to the first Cmake command when building and post the output of both commands here.

**Comment by zoof** [comment]
```
$ c++ --version
c++ (Debian 8.3.0-6) 8.3.0
```

I will try clang.

**Comment by zoof** [comment]
Interesting -- clang works.  Is there any problem uninstalling gcc?  That way I don't have to `export CXX=/usr/bin/clang++` every time I want to update birdtray.

**Comment by Abestanis** [comment]
On Ubuntu, you could use `update-alternatives`, but I don't know if that works on Debian. But you can always add the `export` to your `.bashrc`.

I'm glad we figured the problem out. I should warn you though, while researching for this problem, I read that Debian Buster switched to use Wayland instead of X11. Unfortunately, Birdtray currently does not support Wayland.

**Comment by zoof** [comment]
Thank you, `update-alternaties` worked great!

I'm actually using a Debian alternative, Bunsenlabs, which does not use Wayland but thanks for the warning.
