### ISSUE TITLE
Birdtray doesn't launch Thunderbird

### ISSUE THREAD

**Issue by arnauldb** [gyunaev/birdtray#267]
**OS**: Linux Mint Sylvia 18.3
**Birdtray version**: 1.7.0
**Thunderbird version**: 68.5.0 64
**Birdtray origin**: Installed from flathub

**Description**
When launching Birdtray it doesn't launch Thunderbird. I have Thunderbird in a folder on my desktop. I have to launch Thunderbird manually. Except this Birdtray is working fine once both Birdtray and Thunderbird are launched.

**Expected behavior**
See above

Thank you.

**Comment by Abestanis** [comment]
You can edit the command that is used by Birdtray to start Thunderbird via the `Thunderbird command line:` setting in the `Advanced` tab in the settings dialog.

Be aware that you installed Birdtray from Flathub and Flatpak apps are very restricted in what they can see and do on your computer. Birdtray might not be able to find Thunderbird in the folder on your desktop, even if you specify the path correctly. In that case, it might work using the `flatpak-spawn` command like this: `flatpak-spawn --host /path/to/thunderbird`

**Comment by arnauldb** [comment]
Thank you, it worked.

**Comment by Abestanis** [comment]
Awesome! I'm going to close this issue then. Out of curiosity, was the `flatpak-spawn` command needed?

**Comment by arnauldb** [comment]
> was the flatpak-spawn command needed?

This is what I had in `Thunderbird command line:` before changing anything:
`/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird`

And I changed it for:
`/usr/bin/flatpak-spawn --host /home/arnauld/Desktop/thunderbird/thunderbird` (where the last 'thunderbird' is the executable)

Thks for Birdtray.

**Comment by raffaelj** [comment]
I had a similar behavior with a different OS, so for completeness and to give others a search result:

**OS:** openSUSE Tumbleweed 20200416, KDE Plasma 5.18.4
**Birdtray version:** 1.7.0
**Thunderbird version:** 68.7.0 (64-Bit) with Minimize on Close plugin 1.0.0.1
**Birdtray origin:** Installed from flathub

Solution in Advanced tab for Thunderbird command line:
`/usr/bin/flatpak-spawn --host /usr/bin/thunderbird`

And after using Birdtray for an hour, I already love it. Thanks for this tool.
