### ISSUE TITLE
Incorrect unread count with Mork

### ISSUE THREAD

**Issue by dvalter** [gyunaev/birdtray#269]
**OS**: Arch Linux
**Birdtray version**: 6636ee9 (master as of 2020.02.29)
**Thunderbird version**: 68.5.0
**Birdtray origin**: From source
**Qt version**: 5.14.1-1

**Description**
Mork parser finds fake unread letters

**Expected behavior**
No unread messages in Birdtray when I have none in Thunderbird

**To Reproduce**

1. Start Birdtray
2. Check unread count in Thunderbird and Birdtray

**Additional context**
Changes in 9faac5a3 break parsing in some cases (3 errors among 40+), likely messing up with processing of scopes `0x80` and `0x9A`.

This patch reverts incorrect behavior in my case.
```patch
diff --git a/src/morkparser.cpp b/src/morkparser.cpp
index deb0d0d..cc8e882 100644
--- a/src/morkparser.cpp
+++ b/src/morkparser.cpp
@@ -552,12 +552,6 @@ inline void MorkParser::setCurrentRow( int TableScope, int TableId, int RowScope
     {
         RowScope = defaultScope_;
     }
-    
-    if (!TableId) {
-        QPair<int, int> rowMapping = rowMappings.value(abs(RowId)).value(RowScope, {0, 0});
-        TableScope = rowMapping.first;
-        TableId = rowMapping.second;
-    }
 
     if ( !TableScope )
     {
```

In addition mentioned above code has changed mork dumps for some files including `tests/res/6_Unread_Inbox.msf` and `tests/res/1_Unread_Filter.msf`.

There's one of my files, anonimized with anonymizeMork.py and in addition with timestamps changed to some nonsense.
[anon.msf.gz](https://github.com/gyunaev/birdtray/files/4272260/anon.msf.gz)

**Comment by Abestanis** [comment]
Thank you for providing the test case. The current master indeed parses a `1` out of it, but that is because it uses the `unreadChildren` attribute of the mork file. We had many reports that the attribute is unreliable, which is why we are testing a new parsing method at #245.

The new parsing code on that branch correctly parsed `0` unread Emails. If you are able, could you test your other mork files with that branch?

**Comment by dvalter** [comment]
Looks like code from [this branch](https://github.com/Abestanis/birdtray/tree/fix/wrong_num_unreads) parses unread count correctly on my mailboxes.

**Comment by Abestanis** [comment]
That is great news, thank you for testing!

**Comment by dvalter** [comment]
I don't think it's worth reopening/creating new issue, but in some cases `numNewMsgs` is 0 or (probably, I have not backed up that msf) absent, whereas `unreadChildren` values sum up to a correct unread count.
I hope this file may help: [anon2.msf.gz](https://github.com/gyunaev/birdtray/files/4393903/anon2.msf.gz)

By the way Thunderbird's `Repair Folder` option fixed this for this inbox.

**Comment by Abestanis** [comment]
@dvalter Thank you for reporting this and for making it so easy to reproduce the problem. This is actually a bug in the current parser, so I created #292.
