### ISSUE TITLE
Build on Windows?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [gyunaev/birdtray#27]
This seems fairly straightforward to build on a UNIX sys but a little more problematic on a Windows env. Is there any kind of recipe or cookbook for building this on Windows? Thanks, as I would LOVE to give this a try

**Comment by gyunaev** [comment]
At this moment it is not Windows-compatible. Some Windows-specific code has to be written. Windows developers are welcome to implement wintools_mswin.cpp and send a pull request.

**Comment by mfreeman-xtivia** [comment]
If thats the case then the line on your README that says...
"
_Birdtray is a free, cross-platform (Linux/Windows/OS X) system tray notification for new mail for Thunderbird."_

should probably be updated to reflect that. Bummer.

**Comment by gyunaev** [comment]
Yes, you're right. Funny that it **used to be** fully cross-platform. But the window-specific stuff is not.

**Comment by Abestanis** [comment]
As of #58, the window-specific part should work on Windows as well.

**Comment by gyunaev** [comment]
Released.

**Comment by LinuxOnTheDesktop** [comment]
Hello! Compiling on Windows is not fun - and I'm not setup to do it. I am set up to do it on Linux. If I build the xpi module on Linux, can I just copy it to Windows and use it there too? I suppose there is one way to find out . .
