### ISSUE TITLE
Allow birdtray working as singleton

### ISSUE THREAD

**Issue by M4shy** [gyunaev/birdtray#270]
Sorry if i missed a previous conversation about this.

Is there any foresen implementation in case of excluding multiple instances of thunderbird ?  ie : If I checked the corresponding option 'only one instance' from birdtray, it will not allow any other instances into memory.

**Comment by Abestanis** [comment]
Sorry, but I'm not sure if I understand your question. Are you asking about only allowing one instance of Birdtray or are you asking about only allowing one instance of Thunderbird?

**Comment by M4shy** [comment]
Well, i'm arriving a bit late as I didn't received any notifications about your response. Maybe should I set some options somewhere on github. I've just updated birdtray today and it seems to be ... fixed ? My question was related to the fact that birdtray was instanciated many time from my taskbar. Maybe that my post was mostly related to another feat/bug.

**Comment by M4shy** [comment]
Well, i'm arriving a bit late as I didn't received any notifications about your response. Maybe should I set some options somewhere on github. I've just updated birdtray today and it seems to be ... fixed ? My question was related to the fact that birdtray was instanciated many time from my taskbar.

**Comment by M4shy** [comment]
Nice job btw !

**Comment by M4shy** [comment]
Nice product btw !

**Comment by Abestanis** [comment]
Thanks! Yeah, this was implemented in #224 back in January and is included in the new release. 😄

**Comment by Abestanis** [comment]
By the way, we do provide [release notes](https://github.com/gyunaev/birdtray/releases/tag/1.8.0), if you are wondering what else changed.

**Comment by M4shy** [comment]
Totally out of scope... Is there any setup note for windows development environment ?

**Comment by M4shy** [comment]
... Is there any setup note for windows development environment ?

**Comment by Abestanis** [comment]
That is unfortunately still on my TODO list, but you should be able to use #277 as a starting point. You can ignore my comment about the `sqlite3` library there, that is no longer needed.

**Comment by M4shy** [comment]
Hello! It's absolutely out of topic but since my update today, thunderbird seems having the minimize on tray option by default.
Are you already aware of ? Did you merge some code with mozilla ? 
Regards.

**Comment by Abestanis** [comment]
Thanks for letting us know. We are aware of it (at least I am). We din't merge any code with Mozilla, it looks like they recognized that there was a demand in the community. Their system tray icon is not as capable as Birdtrays thought, for example it can't display the number of unread mails and it has no context menu. So at least for the moment, Birdtray still has value, but it is awesome that they are developing in that area and listening to the community.

**Comment by gyunaev** [comment]
> Hello! It's absolutely out of topic but since my update today, thunderbird seems having the minimize on tray option by default.

Only on Windows, I guess.

**Comment by Abestanis** [comment]
You might not have the latest version. I think this was added in `78.3.1` or maybe `78.3.0`.

**Comment by M4shy** [comment]
>= 78.3.1 I think. I'm still convinced that Moz. has the potential but why so long for this kind of feature ?  
I think that they were a bit 'envious' of what it has been done here ;). You're doing the trick guys!
