### ISSUE TITLE
BirdTray cannot load SVG icon

### ISSUE THREAD

**Issue by MaxAlekseyev** [gyunaev/birdtray#275]
I tried to load pure svg icon of free size and Illustrator generated 64x64. I got "Could not load icon form this file" error in the both cases. What's wrong?

**OS**: 
Win 10x64 1809 LTSC
**Birdtray version**: 
Birdtray version 1.7.0 compiled at Dec  3 2019 22:57:14.
**Thunderbird version**: 
68.6.0
**Birdtray origin**: 
Installer x64
**Qt version**: _NA_ 

**Description**

**Expected behavior**

**To Reproduce**

1.  Try to upload and pure vector SVG
2.  Get standard Windows error notification

**Screenshots**

**Additional context**

**Comment by gyunaev** [comment]
@Abestanis do we package SVG engine in the installer?

**Comment by MaxAlekseyev** [comment]
Don't know, just run x64 installer for this page: https://github.com/gyunaev/birdtray/releases/tag/RELEASE_1.7.0

**Comment by MaxAlekseyev** [comment]
Normal icons at last. Looking well, but PNG.
[img]https://i.imgur.com/e1O6ORv.png[/img]

**Comment by Abestanis** [comment]
> do we package SVG engine in the installer?

No, we don't. Good catch, @MaxAlekseyev! We allowed svgs in 10bb9bb, which was after the installer was added.

**Comment by MaxAlekseyev** [comment]
Looks like the 1.80 version should be the miracle. Working as just the tray icon for now.

**Comment by serovar** [comment]
I get this issue on Fedora 32 with the 1.8.1 flatpak.

**Comment by Abestanis** [comment]
I think you need to have `qt5-qtsvg` installed. @ThanosApostolou is maintaining the Flatpak version, do you want to add this as a dependency?

**Comment by serovar** [comment]
I have it already installed.

**Comment by ThanosApostolou** [comment]
Qt5-svg is part of the kde runtime that flathub birdtray is build against. If we're talking about using a different icon using "General" tab in settings I cannot reproduce any error with some different svgs. Maybe you can share the svg that has the problem?

**Comment by serovar** [comment]
Problem solved, I was selecting some icons from the Papirus icon pack (in particular the panel ones) that the file selector showed as actual svg files, but opening the folder from the file manager shows that lots of them are actually shortcuts (a strange behavior indeed). If I select svg files that are not shortcuts, they work flawlessly. Sorry for the trouble!
