### ISSUE TITLE
Clarify build requirements

### ISSUE THREAD

**Issue by prof7bit** [gyunaev/birdtray#29]
Please clarify what packages I need to have installed to be able to compile this on Kubuntu 18.04:

$ qmake
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

$qmake-qt5
Der Befehl 'qmake-qt5' wurde nicht gefunden, meinten Sie:
  Befehl 'qmake-qt4' aus dem deb qt4-qmake
Versuche: sudo apt install <deb name>

$ sudo apt install qt5-qmake
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  qt5-qmake-bin
Die folgenden NEUEN Pakete werden installiert:
  qt5-qmake qt5-qmake-bin
0 aktualisiert, 2 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 1.118 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 4.388 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] 
Holen:1 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 qt5-qmake-bin amd64 5.9.5+dfsg-0ubuntu1 [938 kB]
Holen:2 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 qt5-qmake amd64 5.9.5+dfsg-0ubuntu1 [180 kB]
Es wurden 1.118 kB in 1 s geholt (2.074 kB/s).
Vormals nicht ausgewähltes Paket qt5-qmake-bin wird gewählt.
(Lese Datenbank ... 334305 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../qt5-qmake-bin_5.9.5+dfsg-0ubuntu1_amd64.deb ...
Entpacken von qt5-qmake-bin (5.9.5+dfsg-0ubuntu1) ...
Vormals nicht ausgewähltes Paket qt5-qmake:amd64 wird gewählt.
Vorbereitung zum Entpacken von .../qt5-qmake_5.9.5+dfsg-0ubuntu1_amd64.deb ...
Entpacken von qt5-qmake:amd64 (5.9.5+dfsg-0ubuntu1) ...
qt5-qmake-bin (5.9.5+dfsg-0ubuntu1) wird eingerichtet ...
qt5-qmake:amd64 (5.9.5+dfsg-0ubuntu1) wird eingerichtet ...
Trigger für man-db (2.8.3-2) werden verarbeitet ...

$ qmake
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

$ sudo apt install qt4-qmake  
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  qt4-qmake
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 1.366 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 5.335 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 qt4-qmake amd64 4:4.8.7+dfsg-7ubuntu1 [1.366 kB]
Es wurden 1.366 kB in 0 s geholt (2.940 kB/s).
Vormals nicht ausgewähltes Paket qt4-qmake wird gewählt.
(Lese Datenbank ... 334943 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../qt4-qmake_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
Entpacken von qt4-qmake (4:4.8.7+dfsg-7ubuntu1) ...
qt4-qmake (4:4.8.7+dfsg-7ubuntu1) wird eingerichtet ...
Trigger für man-db (2.8.3-2) werden verarbeitet ...

$ qmake
Project MESSAGE: Warning: unknown QT: x11extras

$qmake-qt5
Der Befehl 'qmake-qt5' wurde nicht gefunden, meinten Sie:
  Befehl 'qmake-qt4' aus dem deb qt4-qmake
Versuche: sudo apt install <deb name>

$ sudo apt install x11extras-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket x11extras-dev kann nicht gefunden werden.

$ sudo apt install libx11extras-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket libx11extras-dev kann nicht gefunden werden.

-------------

What am I supposed to do?

**Comment by gyunaev** [comment]
Unfortunately I don't understand German, so this is meaningless to me. If you report command line errors, please make sure you switch the output to English before logging, by executing:

`export LANG=en_US.UTF-8`

in your console.
Regarding packages, you need Qt5 development packages, Qt5 build tools and x11extra. Development packages could have either -dev or -devel suffix depending on distro and maintainer preferences, so there is no standard here.

**Comment by prof7bit** [comment]
The errors actually mean there is no such package. There is no x11extras-dev and also there is no libx11extras-dev.

The other strange thing is your build script is trying to use /usr/lib/x86_64-linux-gnu/qt4/bin/qmake instead of the one from qt5. This is a brand new Kubuntu installation with very recent KDE Plasma 5 on it, there should not be much (if any) qt4 stuff around on it.

**Comment by gyunaev** [comment]
There is no build script there; qmake file is supposed to be interpreted with qmake. This line from your output is particularly strange:

```
$ qmake
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

```

apt-cache search qt5 ?

**Comment by gyunaev** [comment]
I suggest `make distclean` instead of `make clean`, as this one also removes qmake-generated files.
