### ISSUE TITLE
Make 1.8.0 release

### ISSUE THREAD

**Issue by gyunaev** [gyunaev/birdtray#297]
Tag pushed, @Abestanis please test the Windows version, and we should be ok to release. Linux is fine.

**Comment by Abestanis** [comment]
Shouldn't this be the 1.8.0 release? Also, can we include #296? We also promised the translators to notify them two weeks in advance. Do you want to do that?

**Comment by gyunaev** [comment]
Yes, you're right, 1.8.0 it is. Updated the title.

Translators, please update the translations if needed. After April 2 until release we will no longer merge pull requests for 1.8.0 which adds new strings or changes existing ones (removal is ok though). I understand everyone is busy, so we gonna give everyone a week to come back and tell us if they need more time; we will make a decision on April 9th whether to proceed with the release.

#296 has conflicts, so yes, we should include that indeed once resolved.

**Comment by Abestanis** [comment]
> #296 has conflicts, so yes, we should include that indeed once resolved.

They have been resolved.

**Comment by Abestanis** [comment]
We should remove the `v1.7.0` tag and the draft release. Did you send the translators an email? Otherwise we should at least `@` mention them, so they get notified.

**Comment by gyunaev** [comment]
I don't have their emails. Shall we ask, or just notify here?

**Comment by Abestanis** [comment]
I think it is best if we mention them here, they should get an email from Github.

**Comment by gyunaev** [comment]
Pinging @Vistaus and @albanobattistella for the feedback.

**Comment by Abestanis** [comment]
Since we are creating a new release soon, we might want to clean up some old stale issues. We have a few open issues that might have been fixed by changes we made since the last release, but the original reporters haven't given any feedback in months (namely #109, #129, #158, #166 and #240). Can we close those?

**Comment by gyunaev** [comment]
Yep. Asked for feedback/closed.

**Comment by Abestanis** [comment]
As a reminder to ourselves; We must not forget to update the version in `src/res/com.ulduzsoft.Birdtray.appdata.xml` and `contrib/rpm/birdtray.spec`.

**Comment by Abestanis** [comment]
@albanobattistella Can we please get a status update from you? Do you need more time to update the Italian translation or are you not going to be able to update the translation?

**Comment by Abestanis** [comment]
@gyunaev We are just missing the `1.8.0` git tag.

**Comment by Abestanis** [comment]
I created the tag and tested the Windows installers. Do you want me to create the changelog as well?

**Comment by gyunaev** [comment]
You can even make a release ;)

**Comment by Abestanis** [comment]
The release is published. 🎉

**Comment by gyunaev** [comment]
Thank you!
