### ISSUE TITLE
Closing down (quitting) issue.

### ISSUE THREAD

**Issue by JackDinn** [gyunaev/birdtray#3]
If you use the icon context "quit" to intend to close down TB + birdtray it does not. It does end the birdtray process but leaves TB running and unreachable.

**Comment by gyunaev** [comment]
Quit is supposed to only quit Birdtray. Thunderbird is reachable if you start it again from command-line. But it probably worth making sure it is not hidden when we quit. Will fix.

**Comment by JackDinn** [comment]
I would say that seems a little odd, If you are using this as default (i have set my launcher for TB to run this) then you have a single TB tray icon that woks as expected and clicking the context/quit would be expected to close TB. No big problem though and of course its you're project.

**Comment by gyunaev** [comment]
I'll think of a good way to implement this.

**Comment by gyunaev** [comment]
@JackDinn can you please test 00da32a? Exit thunderbird on quit is now a setting and should work.
