### ISSUE TITLE
Hook point for external script/program

### ISSUE THREAD

**Issue by rnc** [gyunaev/birdtray#304]
**Description**

This is related to #122 and #226.

I had an idea that it might be a useful 'first step' to provide a hook point to execute an external program once new mail is detected. It could pass some useful variables (like e.g. http://tjeb.nl/Projects/Mailbox_Alert/Manual/index.html does). This way users on either Windows or Linux could run their own choice of script/program once mail is detected. It would potentially be a 'quicker' method than implementing a full notification system. For instance on Linux using `libnotify` something like 
```
/usr/bin/notify-send --icon=/usr/share/icons/hicolor/48x48/apps/thunderbird.png  -a "%server : %originalfolder"  "%subject from %sendername"
```

**Comment by Maboroshy** [comment]
I want that too. I'd use it to update Thunderbird icon's "badge" at the dock to show the number of unread messages. All the extensions that did it are outdated now.

**Comment by gyunaev** [comment]
Committed.

**Comment by Maboroshy** [comment]
Thanks. I can now use this feature to update a badge at Latte Dock by putting in

`dbus-send --dest=com.canonical.Unity --type=method_call /Latte org.kde.LatteDock.updateDockItemBadge string:"thunderbird" string:"%NEW%"` command 

or `update-badge thunderbird %NEW%` with [this shell script wrapper](https://github.com/Maboroshy/latte-dock-badge-updater).

**Comment by pztrn** [comment]
For docks and taskbars that supports libunity API.

Save somewhere and `chmod +x` it:

```
#!/usr/bin/env bash

COUNT=$1

if [ ${COUNT} -gt 0 ]; then
        gdbus emit --session --object-path / --signal com.canonical.Unity.LauncherEntry.Update "application://betterbird.desktop" "{'count': <int64 ${COUNT}>, 'count-visible': <true>}"
else
        gdbus emit --session --object-path / --signal com.canonical.Unity.LauncherEntry.Update "application://betterbird.desktop" "{'count': <int64 0>, 'count-visible': <false>}"
```

Add to settings like:

```
/path/to/script.sh %NEW%
```
