### ISSUE TITLE
Build failure - references to decodeIMAPutf7

### ISSUE THREAD

**Issue by scottfurry** [gyunaev/birdtray#306]
Latest from git repo( hash# 383f0593d2f72984bbe13d7d6af0996b4bffa1e6 ) results in build failure.

Build will abort and flag `src/settings.cpp` [Line 413](https://github.com/gyunaev/birdtray/blob/383f0593d2f72984bbe13d7d6af0996b4bffa1e6/src/settings.cpp#L413) and [Line 419](https://github.com/gyunaev/birdtray/blob/383f0593d2f72984bbe13d7d6af0996b4bffa1e6/src/settings.cpp#L419) with message that `error: ‘decodeIMAPutf7’ is not a member of ‘Utils’`.

I believe these are unhandled residual statements from previous commit that removed function.

**Comment by gyunaev** [comment]
Yes. Reverted.
