### ISSUE TITLE
export ENV var before launch thunderbird

### ISSUE THREAD

**Issue by asarubbo** [gyunaev/birdtray#313]
**Description**

Would be great if there will be something that let you export some env variables.
The need comes from the fact that if you are using a dark theme, thunderbird will be unreadable, so I'm exporting GTK_THEME before launch thunderbird
Thanks

**Comment by Abestanis** [comment]
I don't know if that is worth doing in Birdtray. Couldn't you use a wrapper shell script to archive that?

**Comment by asarubbo** [comment]
Hi, sure I can use a wrapper and this is something I'm already doing. But if this is something done by a lot of people it may worth..

**Comment by gyunaev** [comment]
You don't even need a wrapper, just export those variables before starting birdtray. It should inherit the environment and pass it to children processes.

**Comment by gudvinr** [comment]
This is really useful though. You can just use `env GTK_THEME=theme thunderbird` from `.desktop` file (or application menu entry) but you can't do that from birdtray so you should introduce different launch script or make copy of `.desktop` file to use custom script which sounds just like workaround but not a handy solution.

**Comment by Abestanis** [comment]
> So only necessary thing to solve this issue is to correctly handle launch string because it seems like right now birdtray treats it like whole path to thunderbird executable rather than command.

@gudvinr That doesn't sound right, did you actually test that? The last time I checked, we did support entering a full command in the advanced tab.

**Comment by gudvinr** [comment]
@Abestanis how would I know that otherwise?

Yes, I did test that and it didn't work. I get an error:
```
Error starting Thunderbird as '/home/{username}/env GDK_DPI_SCALE=0.5 /usr/bin/thunderbird':

execvp: No such file or directory
```

If I use launch command as `env GDK_DPI_SCALE=0.5 /usr/bin/thunderbird`.

But it works if I run `/usr/bin/env GDK_DPI_SCALE=0.5 /usr/bin/thunderbird` though it is neither convenient nor obvious.

**Comment by Abestanis** [comment]
> how would I know that otherwise?

Sorry, I'm not a native speaker, do you mean how you could verify that it works or not? You seem to have figured it out.

> If I use launch command as env GDK_DPI_SCALE=0.5 /usr/bin/thunderbird

This doesn't work, because we don't search for the program on the `PATH`. You need to specify the full path to the program.

> But it works if I run /usr/bin/env GDK_DPI_SCALE=0.5 /usr/bin/thunderbird

Exactly like this. 😄👍 

> though it is neither convenient nor obvious.

That might be true, but it is a working workaround. We could either document it in the README so it is more obvious, or we could add an extra field to the settings page, which would make it more convenient. If you wan't to take a stab at it, go for it. Pull requests are always welcome.

**Comment by gyunaev** [comment]
> But it works if I run `/usr/bin/env GDK_DPI_SCALE=0.5 /usr/bin/thunderbird` though it is neither convenient nor obvious.

Why isn't it obvious? This is a standard way to launch binaries with changed environment.

**Comment by gudvinr** [comment]
> Why isn't it obvious

Because every other place in the system knows about `PATH` variable. I meant `/usr/bin/` part and not using `env`

**Comment by gyunaev** [comment]
> Because every other place in the system knows about `PATH` variable.

Actually only your shell knows about PATH variable, and PATH evaluation is shell-specific thing.
