### ISSUE TITLE
New emails reported when there are no new emails

### ISSUE THREAD

**Issue by asarubbo** [gyunaev/birdtray#317]
See the screenshot attached.
I see '1' when in the practice there are no new emails.

Version: Birdtray 1.8.0 compiled on Apr 17 2020 20:12:57.
Os: Gentoo x86_64

![Screenshot_20200418_130028](https://user-images.githubusercontent.com/4741819/79636002-fc75f600-8174-11ea-9017-fa7670ef37fb.png)

**Comment by Abestanis** [comment]
Please use the log viewer to find out which `msf` file Birdtray thinks has an unread mail. Use the [anonymizeMork script](https://github.com/gyunaev/birdtray/tree/master/contrib/anonymizeMork) to anonymize the file and upload it here

**Comment by IanBlakeley** [comment]
FWIW I have seen this happen when my drafts folder is monitored, i.e. I am in the middle of composing a message that gets saved, when the message is sent Thunderbird removes the draft but for some reason Firetray is not updated.
