### ISSUE TITLE
Email Notifier does not show the correct count after email has been read

### ISSUE THREAD

**Issue by RYRNRY** [gyunaev/birdtray#322]
Setup:
Birdtray version 1.8.0 compiled at Apr 19 2020 10:18:35.
Thunderbird 68.7.0 (32 bit)
Windows 7 Pro SP1
--------------------------
Birdtray notifier count is usually 1 higher than the actual unread count.  When I mark emails as unread, count does get updated almost immediately.  However, when I mark them as READ, count stays at the highest number.

If I were to open the SETTINGS panel and just close it, it gets RESET back to ZERO.

**Comment by RYRNRY** [comment]
![image](https://user-images.githubusercontent.com/32840664/79875350-261a6180-83af-11ea-874e-92b56304d2f5.png)
Debug Log Viewer does show 'UnRead Counter Update' running every 5 secs.

**Comment by Abestanis** [comment]
I can confirm that the forced update does not actually recognize a changed mork file.
@gyunaev could you take a look at this? Does this happen on a Linux machine too or is this a Windows only bug?

**Comment by gyunaev** [comment]
Just pushed e10963f..e584674

**Comment by Abestanis** [comment]
@gyunaev This might actually be a big deal for many users. Should we create a `1.8.1` release?

**Comment by gyunaev** [comment]
Yes, unless we introduced new strings

**Comment by Abestanis** [comment]
> Yes, unless we introduced new strings.

I don't believe we did.

**Comment by RYRNRY** [comment]
Many many thanks for addressing this issue to everyone in your team.
