### ISSUE TITLE
Logged error: Failed to load translation for en_US

### ISSUE THREAD

**Issue by lsteeger** [gyunaev/birdtray#333]
**OS**: Linux 5.4.33-1-MANJARO xfce4
**Birdtray version**: Birdtray version 1.8.0 compiled at Apr 22 2020 05:37:29.
**Thunderbird version**: 68.7.0 (64-bit)
**Birdtray origin**: From package manager AUR http://aur.archlinux.org/packages/birdtray
**Qt version**: 5.14.2-1

**Description**
From log:
2020-04-22 00:58:22 Birdtray version 1.8.0 started 
2020-04-22 00:58:22 Failed to load translation for en_US 

Inspite of this error message there is no apparent external problem with the interface appearing in English.

**Expected behavior**
No error message

**To Reproduce**
1. Start birdtray
2. Immediately go to Settings > Advanced > Show log window
3. First two messages shown above.

**Additional context**
Wed 04-22-2020 01:04
===> declare -p ${!LA*}
declare -x LANG="en_US.UTF-8"

Wed 04-22-2020 00:49
===> declare -p ${!LC*}
declare -x LC_ADDRESS="en_US.UTF-8"
declare -x LC_COLLATE="C"
declare -x LC_IDENTIFICATION="en_US.UTF-8"
declare -x LC_MEASUREMENT="en_US.UTF-8"
declare -x LC_MONETARY="en_US.UTF-8"
declare -x LC_NAME="en_US.UTF-8"
declare -x LC_NUMERIC="en_US.UTF-8"
declare -x LC_PAPER="en_US.UTF-8"
declare -x LC_TELEPHONE="en_US.UTF-8"
declare -x LC_TIME="en_US.UTF-8"

**Comment by Abestanis** [comment]
The English translation is compiled within the Birdtray executable and is used as a default. That is why this doesn't really affect anything. But this does mean, that Birdtray is probably not able to find any translations.

We don't actually maintain the AUR package ourselves. Could you please report a bug at [the AUR package site](http://aur.archlinux.org/packages/birdtray) and point them to this bug report. It is possible that they don't package the translations.

**Comment by lsteeger** [comment]
After talking to jonathan, the AUR supporter, it has been determined that my system did not have 'qt5-translations' package installed.  Installing this package has eliminated this error message.

jonathan at AUR has added 'qt5-translations' as an optional package to the birdtray AUR package.

**Comment by Abestanis** [comment]
Awesome, thank you for the report.
This might affect other packaging formats as well.
Pinging @ThanosApostolou to check if this needs to be done for the Flatpak version
and @raven-kg to check if the [`birdtray.spec` file](https://github.com/gyunaev/birdtray/blob/master/contrib/rpm/birdtray.spec) should include the dependency as well.

**Comment by ThanosApostolou** [comment]
@Abestanis sorry for taking so long to reply, the issue was that qt5-qttranslations were missing from the KDE runtime that the flatpak is built against. I had contacted the devs and it was recently added, so now this is fixed for the flatpak version as well.
