### ISSUE TITLE
Unable to install on Xenial

### ISSUE THREAD

**Issue by NginUS** [gyunaev/birdtray#34]
I see this is only meant to be installed on Bionic & up, & being on Xenial poses a problem. I don't really want to go through reinstalling my whole system just to get new Thunderbird with Birdtray working.

If need be I can revert to Thunderbird 38.x & keep using FireTray, but that'd be less than ideal. So am checking here in case there's a solution.

**Comment by gyunaev** [comment]
"Unable to install" tells me nothing, unfortunately. What is the exact issue?

**Comment by NginUS** [comment]
Immediately after I add the PPA, it displays birdtray as one of 2 new packages. But if I do 'aptitude search', 'aptitude show', or 'aptitude install' birdtray the package is not found.

**Comment by gyunaev** [comment]
I do not build any of those packages, so I cannot help here. Please submit the issue in the Xenial package list.

**Comment by NginUS** [comment]
I was eventually able to, with the PPA maintainer's help, get a FireTray build installed which works with Thunderbirds >62.x. So now I have system tray functionality in Xenial without the need for a BirdTray package to install. Thanks for pointing me in the right direction.
