### ISSUE TITLE
Translation INBOX.msf

### ISSUE THREAD

**Issue by KOV70** [gyunaev/birdtray#344]
Hello everybody!
Thanks for the great program.

I have a question about translating "INBOX" in dynamic_xx.ts
In profile, he is like "Inbox".
Therefore, in the settings, it remains untranslated.
![11](https://user-images.githubusercontent.com/45202680/80190111-63375b80-861c-11ea-90e9-3a0d0ebc8a6f.png)

If you change to "Inbox", the translation appears.
![12](https://user-images.githubusercontent.com/45202680/80190146-74806800-861c-11ea-962a-9525ecfcbf41.png)

Checked on several Linux computers and one Windows - everywhere "Inbox"
(Xubuntu screenshot)
![10](https://user-images.githubusercontent.com/45202680/80190444-fd979f00-861c-11ea-9b4a-ba86b394e399.png)

**Comment by Abestanis** [comment]
Thank you for the report.
Interesting, my inboxes are all uppercase:
![Inbox files](https://user-images.githubusercontent.com/6966049/80235669-4c175e80-865a-11ea-9ea5-7fa00c77b4b7.png)
Should be easy enough to support both.
