### ISSUE TITLE
Ignored ignored threads

### ISSUE THREAD

**Issue by yjfguhd** [gyunaev/birdtray#345]
It appears that Birdtray does not (cannot?) take into account new messages to ignored threads. In Thunderbird, you can right click or otherwise highlight a message, and choose "Ignore Thread" (default shortcut is "K"), whereupon subsequent new mails to the threads won't pop up a notification. Birdtray, however, still counts new mails to the ignored thread, and flashes its own "new mail" notification in the system tray. I can see in the log that it saw the new mail in the INBOX.msf.

I'm using Thunderbird 68.7.0 and have seen this with Birdtray 1.8.0 and 1.7.0.

**Comment by gyunaev** [comment]
No, it cannot - there is no information about ignored threads in the MSF files.
