### ISSUE TITLE
start up and shutdown hiding 

### ISSUE THREAD

**Issue by dango345** [gyunaev/birdtray#349]
DISTRO : ARCH
DE : KDE
BIRDTRAY : LATEST GIT

when setting hide Thunderbird when birdtray starts , Thunderbird shows in taskbar and flashes up for a second even when set to 0 secs to hide in settings of bird tray, same when you set if Thunderbird closed restart Thunderbird in birdtray settings

is it possible to hide Thunderbird flashing up and be completely silent and not show in taskbar or flashup for any period of time and only be displayed in the taskbar tray

**Comment by gyunaev** [comment]
No, this is not possible - the window must register in the X before Birdtray can pick it up.
