### ISSUE TITLE
Birdtray does not start

### ISSUE THREAD

**Issue by mikail0** [gyunaev/birdtray#357]
**OS**: Arch 
**Birdtray version**: I can not open the app. I have installed birdtray from the AUR 
**Thunderbird version**:68.7 
**Birdtray origin**: AUR 
**Qt version**: _NA_ 

**Description**

I have installed birdtray on GNOME Wayland, tried to start it, but nothing happened.
After 1-2 minutes, I got an error message, that the status/system bar can not be be controlled by this addon. It also says that a protocol were written in the file /tmp/log.txt, but there is no with that name.

**To Reproduce**

1. Install birdtray from the aur on GNOME Wayland.
2. Try to start it

Edit:
Tried to start it on GNOME Xorg. Still the same issue.

**Comment by patjgardner** [comment]
> Can confirm this problem on Fedora 32 Gnome Wayland. Installed via flatpak.

@Sirtz I'm using the flatpak on Fedora 31 Gnome Wayland, and a fix is to run:

`sudo flatpak override --env=QT_QPA_PLATFORM="xcb" com.ulduzsoft.Birdtray`

and then try running Birdtray.

**Comment by neoh4x0r** [comment]
@mikail0 I get the same problem on Debian 9 (Stretch) / birdtray 1.8.0 / Cinnamon 3.2.7
However, for me I only get that message when logging in `"status/system bar can not be be controlled by this addon"`
Although once I am logged in, I can start birdtray manually without recieveing that error.

I have checked out the latest source 3541386a08ea570cc9640a450558b30a2f297b2f
I will be seeing if I can debug this issue.

```
$ /usr/bin/birdtray --version
birdtray 1.8.0

$ /scripts/get_release 

          Distribution: Debian 
               Version: 9 (debian version: 9.12)
     Support Lifecycle: N\A
              Codename: 9 (stretch) 
              Fullname: Debian GNU/Linux 9 (stretch) 

           Kernel Name: Linux
        Kernel Release: 4.19.0-0.bpo.8-amd64
        Kernel Version: #1 SMP Debian 4.19.98-1~bpo9+1 (2020-03-09)
  Machine Architecture: x86_64
      Operating System: GNU/Linux
              Hostname: desktop1

$ cinnamon --version
Cinnamon 3.2.7
```

**Comment by neoh4x0r** [comment]
It seems that birdtray fails to start because it was calling `ensureSystemTrayAvailable()` which will timeout after 60 seconds.
There isn't a need to call ensureSystemTrayAvailable() because QSystemTrayIcon will automatically add the icon once the system tray becomes available and is visible.

@mikail0 If you can build from source you might want to test out this commit c75759cb75008788f211cb6db58a38e8366bf88b
It is from the PR I just posted.

**Comment by Cherkah** [comment]
OS: manjaro
Birdtray version: 1.9.0 (AUR)
Qt version: 5.15.1

Description

birdtray crash plasma wayland launch and  do not launch as well. 

To Reproduce

    Install birdtray from the AUR on plasma Wayland (manjaro).

**Comment by gyunaev** [comment]
Wayland is not supported.

**Comment by Cherkah** [comment]
ok but in this case could you add this info to the "Troubleshooting" section in the README.md.
+ as well, if the wayland support is planify in the future or not at all?!!! (like this some people can push this feature to the mozilla/thunderbird dev team....)

regards

**Comment by gyunaev** [comment]
https://github.com/gyunaev/birdtray/issues/426

**Comment by gyunaev** [comment]
Note that you're using an old version; if you build it from source it won't crash, but show/hide won't work.

**Comment by Cherkah** [comment]
@gyunaev thanks i didn't seen the issue #426 .
regards
