### ISSUE TITLE
Need to remove qmake.stash

### ISSUE THREAD

**Issue by phobi4n** [gyunaev/birdtray#36]
You need to remove .qmake.stash. It causes compile errors on Neon. It introduces a number of include paths that simply don't exist on other distros and causes a problem with: usr/include/c++/7/bits/stl_relops.:67: Parse error at "std".
At the very least, build instructions should be: make distclean; qmake; make.

**Comment by gyunaev** [comment]
You're right, I didn't even notice until now it got into repo. Fixed in 5223b04.
