### ISSUE TITLE
Linux Mint: Lightning Calendar gets freezed by Birdtray

### ISSUE THREAD

**Issue by lowersaxon** [gyunaev/birdtray#363]
When Thunderbird once is hided (in german function is called: "Thunderbird ausblenden") by Birdtray, the Lightning Calendar will stay on the same day.
The date only can be actualized by closing and restarting Thunderbird.

Linux Mint 19.3 Cinnamon (64-bit)
Thunderbird 68.7.0 (64-bit)
Mozilla Lightning Version 68.7.0
Birdtray-Version 1.8.1, kompiliert am Apr 30 2020 08:44:09

**Comment by gyunaev** [comment]
See #425
