### ISSUE TITLE
Thunderbird does not automatically minimize on startup in i3wm

### ISSUE THREAD

**Issue by Kryszak** [gyunaev/birdtray#365]
**OS**:Manjaro Linux 64-bit
**Birdtray version**: 1.8.1
**Thunderbird version**:68.8.0
**Birdtray origin**: From package manager

**Description**
I'm using birdtray on i3wm window manager. Birtray is set up to start with windows manager, and thunderbird is set to start with birdtray and then minimize. I have thunderbird bound to workspace not focused on startup. Because of this, thunderbird is not mimized by itself - I have to switch to workspace with thunderbird and only then it will minimize. After that, I do not have to be on workspace with thunderbird to minimize it with birdtray.

**Expected behavior**
Thunderbird should be minimized on startup without manual workspace focus.

**To Reproduce**
1.Bind thunderbird to i3wm workspace that is not active on session startup.
2. In birdtray, set thunderbird to start with birdtray and minimize after start
3. Switch to workspace other than assigned to thunderbird
4. Start birdtray

**Comment by tlawrencem** [comment]
Why was this closed? It doesn't seem to be resolved? Any workarounds?

**Comment by Kryszak** [comment]
I didn't find one and sadly I live with this behavior...

**Comment by gyunaev** [comment]
From readme:

> Generally Birdtray expects a spec-compliant desktop manager. If you're using a barebone or non-standard/light/simple desktop manager, it is very likely that some features of Birdtray will not work properly.

**Comment by Kryszak** [comment]
The only solution for i3wm that might work is to use "spotify workaround":
https://wiki.archlinux.org/title/i3#Default_workspace_for_Spotify
I didn't test it, but that may help
