### ISSUE TITLE
Thunderbid window is not fully maximised when open from the tray icon

### ISSUE THREAD

**Issue by saaj** [gyunaev/birdtray#367]
Description
-----------
When Thunderbird window is open from Birdtray's tray icon, it's not maximised, even if it was maximised when it was hidden via click on the icon. Visually it's hard to tell the difference, but it has one annoying consequence. 

- Steps to reproduce: throw mouse pointer to the most right top position on the screen
- Expected behaviour: click closes/hides Thunderbird window
- Actual behaviour: window resize cursor is active
- Workaround: well, turn your hand into high-precision mode to move the cursor a couple pixels bottom-left to hover the close button and click, or right click and maximise and repeat the steps to reproduce, or right click and minimise
- Environment: Linux Mint 18.3 Cinnamon

**Comment by gyunaev** [comment]
Mint 18.3 has many issues with its desktop manager. See for example #132. Can you try 19.3?
