### ISSUE TITLE
Documentation: how to build birdtray openSUSE

### ISSUE THREAD

**Issue by indigoxela** [gyunaev/birdtray#37]
To build birdtray on openSUSE, following packages including their dependencies are needed:

- libqt5-qtbase-devel
- libqt5-qtx11extras-devel   
- sqlite3-devel

Then (as an unprivileged user) download or clone birdtray to somewhere in your home dir. Then:

```
cd src
qmake-qt5
make
```

After compiling start birdtray compiled in this folder to add some setting:
`./birdtray`

**Comment by gyunaev** [comment]
Please submit patch to BUILD.MD and I will include it into documentation :)

**Comment by geckolinux** [comment]
- https://build.opensuse.org/package/show/home:sb56637:misc/birdtray
- https://forums.opensuse.org/showthread.php/533282-Trouble-packaging-a-Qt5-app-quot-File-not-found-quot

**Comment by gyunaev** [comment]
Added some info into README
