### ISSUE TITLE
Auto hide in kde plasma system tray

### ISSUE THREAD

**Issue by fabianski7** [gyunaev/birdtray#371]
The implementation of this function was done (#233) but I think it could be improved.

Currently, if there was no new email and the hide option is active, birdtray won't have its system tray icon anywhere, not even where the other apps with lower priority are grouped.

Hiding it completely doesn't seem to be ideal behavior, since the birdtray icon has useful functions, like writing a new email. But if it's completely hidden, then that won't be possible.

His behavior could be the same as the notification icon, if there is one unread [it is displayed with priority](https://upload.vaa.red/wo1Eh#UzUSIbG1Uj1yTaIuAaPAQUxEZW4lBhAz), if not [it is grouped together with the others](https://upload.vaa.red/2twZr5#ou7lfjAxP9gAqE92iRGwtKbzB6szPOBA).

#96 #252

**Comment by gyunaev** [comment]
This would require compiling/linking with KDE.
