### ISSUE TITLE
Move BT settings to new pc

### ISSUE THREAD

**Issue by ampped101** [gyunaev/birdtray#374]
Trying to move BT to another pc with current settings. Tried to use entire dir but it didn't work. Where does it save the settings and watch folders?

Windows 10 64

**Comment by Abestanis** [comment]
I am assuming you have the latest version of Birdtray, version [`1.8.1`](https://github.com/gyunaev/birdtray/releases/tag/1.8.1).
In that case the settings are stored in `%LocalAppData%\ulduzsoft\birdtray\birdtray-config.json`, as it is documented in our [README](https://github.com/gyunaev/birdtray/tree/1.8.1#configuration-file-location). You should be able to copy them from your old PC to your new one and put them at the exact same location. If you started Birdtray on your new computer, it will have created a new settings file at that location. You can simply replace the new config file with your old one.

For future reference, please fill out the template, so we don't have to guess your Birdtray version and other information.
