### ISSUE TITLE
No tray icon on debian buster with Mate desktop

### ISSUE THREAD

**Issue by robyf** [gyunaev/birdtray#376]
**OS**: Debian Linux 10 (buster), 64 bit, Mate 1.20.4
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.8.1
**Birdtray origin**: From source
**Qt version**: 5.11.3

**Description**
Birdtray starts but nothing happens. The process is there and I can see in the logs that it scans the mailbox files and correctly counts the unread messages, but no icon in tray. No errors in the log.

**Expected behavior**
An icon is displayed in the system tray.

**To Reproduce**
Open the app.

**Additional context**
I tried also building a backport of the package from Debian Sid, same result.

**Comment by gyunaev** [comment]
Do other Qt applications show system tray icons? For example if you run qbittorrent, does it show a tray icon?

**Comment by robyf** [comment]
Looks like there's something weird going on with qt5 built applications and gtk+ based panels. If I start the application normally no icon but if I start it via dbus-launch (aka `dbus-launch birdtray`) then it works fine. Weird.

**Comment by gyunaev** [comment]
System tray communication is via dbus, so this may explain it.

**Comment by robyf** [comment]
Yes, but nice inconvenience of qt. Anyway I would say this is not a birdtray bug so closing.

**Comment by gyunaev** [comment]
You can also check if you have dbus running before starting birdtray AND that dbus session is available (i.e. DBUS_SESSION_BUS_ADDRESS variable is set). If it is not running, you need to start it. If it is running, but the variable is empty, you may want to submit an issue into Mate bug tracker.

**Comment by robyf** [comment]
dbus is running and the DBUS_SESSION_BUS_ADDRESS variable is properly set.

**Comment by gyunaev** [comment]
Interesting. Then I'd definitely ask Mate devs.
