### ISSUE TITLE
Flatpak immediately crashes on Fedora 32 GNOME.

### ISSUE THREAD

**Issue by oaksisfolks** [gyunaev/birdtray#379]
**OS**: Fedora 32, GNOME, kernel 5.6.15-300.fc32.x86_64
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.8.0
**Birdtray origin**: Flathub
**Qt version**: _NA_ 

**Description**

Birdtray crashes when opened. 

When I run `flatpak run com.ulduzsoft.Birdtray` it says,
`QSocketNotifier: Can only be used with threads started with QThread.`

GnomeAbrt says that birdtray was killed with SIGSEGV.

**Expected behavior**

birdtray opens to be configured.

**To Reproduce**

1. Install from flathub.
2. Launch birdtray

**Comment by gyunaev** [comment]
Unfortunately unless you can reproduce the issue from the source version, there is nothing I can do. I do not build those flatpacks and I will not support them.
