### ISSUE TITLE
Add thunderbird folder not available in settings in latest dev

### ISSUE THREAD

**Issue by indigoxela** [gyunaev/birdtray#38]
At least I couldn't find it anywhere in the dialog (latest commit ab86e29d3b8d621d165bdf6d1edddf41e06e8d06).

My workaround was to add the thunderbird base folder in an older version (1.1)

**Comment by gyunaev** [comment]
Adding Thunderbird folder only makes sense if you use sqlite backend. By default now Mork backend is used, and you add individual MSF files. If you want to use sqlite backend, switch the parser to Sqlite in Advanced settings tab.

**Comment by indigoxela** [comment]
> Adding Thunderbird folder only makes sense if you use sqlite backend.

Ah, got it. Then it would be helpful, if the first setup after install wouldn't pretend, that this is a required step, including an error message and the monitoring settings keeping disabled. ;)

Hm... garbage, seems I can't upload screenshots in github now.

It's a workflow issue - you still require setting a Thunderbird folder, although not necessary anymore.
Try it on a fresh setup.
