### ISSUE TITLE
Add ability to delete incoming mail right from notification UI

### ISSUE THREAD

**Issue by serj-p** [gyunaev/birdtray#380]
**Description**

After GNotify extension was abandonned because of changes in recent versions of thunderbird I started looking for an alternative and found this a the best option.

It however doesn't implement killer feature of the mentioned GNotifier, more specically the ability to delete or archive incoming messages right from notification GUI. I am using gnome3, but depending on the library implementing notification for birdtray it may work on another OS/DEs. 

![68747470733a2f2f7261772e6769746875622e636f6d2f6d6b696f6c2f474e6f7469666965722f6d61737465722f6d6973632f676e6f6d652e706e67](https://user-images.githubusercontent.com/2565455/84017305-c12ac300-a97e-11ea-95d1-e06191cf33f2.png)

**Example**

**Comment by gyunaev** [comment]
Not possible.
