### ISSUE TITLE
Birdtray brings TB forward once per a couple of seconds

### ISSUE THREAD

**Issue by Ri0n** [gyunaev/birdtray#383]
**OS**: Gentoo 
**Birdtray version**: latest master 3541386
**Thunderbird version**: 79a1
**Birdtray origin**: from gentoo portage
**Qt version**: 5.15

**Description**
That's weird. Whatever I do (minimize,close,switch to another window), TB will be started (if necessary) and brought forward. Basically this make the app unusable.

**Expected behavior**
Never bring forward if not explicitly asked to do that.

**To Reproduce**

1. Unpack TB nightly in any directory
2. Setup path to TB binary in birdtray setting
3. set a tick "Start TB in BT start"

**Screenshots**

![изображение](https://user-images.githubusercontent.com/52379/85072289-8831f000-b1c1-11ea-9ad8-6c61f18a62d4.png)

**Comment by gyunaev** [comment]
Could you please build the latest version and post the log output (settings -> advanced -> show log -> copy from the console)?

**Comment by Ri0n** [comment]
not reproducible with latest master
