### ISSUE TITLE
No Tray Icon - Windows 7

### ISSUE THREAD

**Issue by MrSmite** [gyunaev/birdtray#387]
**OS**: Windows 7 Pro x64
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.9.0 (x86)
**Birdtray origin**: From installer, downloaded from this repo
**Qt version**: _NA_

**Description**

BirdTray starts when I boot windows and per settings also starts Thunderbird. There is no icon created in the notification tray or in the "show hidden icons" area.

**Expected behavior**

The icon should show up in the tray.

**To Reproduce**

1. Install 
2. Run Setup
3. Run BirdTray

**Screenshots**

_NA_

**Additional context**

At first, when I clicked "show hidden icons" and then "customize", BirdTray is listed but the tooltip says "this notification icon is not active". I tried removing the registry entries from the following registry key but that resulted in completely removing the BirdTray option from the "show hidden icons / customize" dialog.

HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify

**Comment by MrSmite** [comment]
Update:

So after performing the registry clean mentioned in my OP, I uninstalled and reinstalled BirdTray (also removing settings). After the initial setup and choosing the settings again, it launhed Thunderbird and the icon is not available.

**Comment by Abestanis** [comment]
I am a bit confused by your last post. Was the problem fixed by reinstalling Birdtray?

**Comment by MrSmite** [comment]
> I am a bit confused by your last post. Was the problem fixed by reinstalling Birdtray?

Sorry, that was a typo. It should say "is now available"
