### ISSUE TITLE
Ubuntu 20.04 LTS no new mail count on tray icon

### ISSUE THREAD

**Issue by dawidpstrak** [gyunaev/birdtray#388]
as in topic it also no blinking.

Greetings

**Comment by gyunaev** [comment]
Yes, it looks like the latest KDE ignores alpha on system tray icons.

**Comment by bamyasi** [comment]
Me too (Kubuntu 20.04.1 LTS installed here).

I don't care about blinking but the tray icon does not show new/unread messages count at all, unless I snooze/unsnooze birdtray from the options menu. Kind of defies the purpose...

**Comment by zoof** [comment]
I'm also seeing this with `tint2`.

**Comment by gyunaev** [comment]
Interestingly the same KDE Plasma systray applet doesn't blink on Intel graphics, but blinks on NVidia graphics.
