### ISSUE TITLE
Birdtray flatpak unable to start thunderbird

### ISSUE THREAD

**Issue by Zzombiee2361** [gyunaev/birdtray#389]
**OS**: KDE Neon 5.19
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.10.0
**Birdtray origin**: Flatpak

**Description**
I enabled Start thunderbird when Birdtray starts and Restart thunderbird if it was closed option and thunderbird just won't start. I added 2 second delay and checked both hide option. Both thunderbird and birdtray is installed from flatpak.

**Expected behavior**
Thunderbird is not started at all

**To Reproduce**
1. Start birdtray, and thunderbird won't start as well
2. Manually start thunderbird
3. Close thunderbird
4. Thunderbird is not restarted

**Screenshot**
![image](https://user-images.githubusercontent.com/37852137/86884358-a71b0680-c11d-11ea-99e1-663932c9845b.png)

**Additional context**
On the debug log, this repeats until thunderbird is manually started
```
2020-07-08 13:05:02 Window ID found: 0 
2020-07-08 13:05:02 Starting Thunderbird as '/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird' 
2020-07-08 13:05:03 Window ID found: 0 
2020-07-08 13:05:03 Starting Thunderbird as '/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird' 
2020-07-08 13:05:04 Window ID found: 0
2020-07-08 13:05:04 Starting Thunderbird as '/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird'
```

**Comment by gyunaev** [comment]
And running `/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird` manually starts Thunderbird?

**Comment by Zzombiee2361** [comment]
I can't, there is no such file on my system. I assumed that executable is only available/visible inside flatpak sandbox, cause afaik you can't access `/usr/bin` or any other location if you don't allow it (which isn't by default except maybe home)

**Comment by gyunaev** [comment]
The command line you specify in Thunderbird settings should be the one to run Thunderbird. Unfortunately Birdtray cannot magically determine how to start Thunderbird on your system. How do you start it manually?

**Comment by Zzombiee2361** [comment]
It's already pre-filled with that after I installed it from flathub. I tried changing it with `flatpak run` but no luck. Did you test the flatpak version? I don't really know how does flatpak app starts another flatpak app.

**Comment by gyunaev** [comment]
I don't build the flatpac version, so I don't know anything about it unfortunately.

**Comment by Zzombiee2361** [comment]
Oh I thought you build them yourself. Alright then, I'll open an issue on flathub repo.

**Comment by Zzombiee2361** [comment]
Fixed by simply changing thunderbird command line to `/usr/bin/flatpak-spawn --host flatpak run org.mozilla.Thunderbird`. This should be changed in the default setting

**Comment by gyunaev** [comment]
Please let the maintainer know, as they are the one who put this string into the configuration.

**Comment by Zzombiee2361** [comment]
Yes, I also commented that on the flathub repo. Hopefully they see it and fix it soon

**Comment by premier69** [comment]
> 

do you have any idea why that line i just copied into the command line field gets me an error message?  no such file or dir.
