### ISSUE TITLE
Notifications/counter not working Win 8.1

### ISSUE THREAD

**Issue by narcolepticinsomniac** [gyunaev/birdtray#391]
Birdtray version 1.8.1
Thunderbird 78.0.1 32bit
Win 8.1 64bit

Since I'm not seeing any similar reports, I'm gonna assume this is OS specific, seeing as how 8.1 isn't all that popular. Either that, or I'm doing something spectacularly stupid, which is also entirely possible. I've enabled monitoring for the only account inbox, and I've yet to see a single counter or notification, even though they're also enabled.

Only change I've sporadically seen happen, is enabling the blinking systray icon, but it's also very unreliable. When I've seen it work, it shows up late, and remains blinking long after all messages are marked read, then eventually stops. When a new message arrives, more often than not, it doesn't work at all either.

All the non-notification settings work flawlessly, and those really do fix most of Thunderbird's shortcomings to the point where it's actually usable. It'd be really sweet to get the rest of it working though, if at all possible.

**Comment by gyunaev** [comment]
Please enable Settings -> Advanced -> Force index file reread checkbox and let me know.

**Comment by narcolepticinsomniac** [comment]
I found this setting while troubleshooting, but didn't think it was worth mentioning since it seems like a less than ideal approach. Only improvement is to the flashing systray icon - it becomes far more reliable. Still no counter, or any notification. IDEK what to call notifications, because I've never seen one.

**Comment by gyunaev** [comment]
Please post the debug log - make some emails unread in Thunderbird and then back read again and post the log. Please mask any paths, usernames or other personal information, if any.

Just to make it clear, Birdtray only shows the count. **It does not show, and is not supposed to show any notifications**.

**Comment by narcolepticinsomniac** [comment]
>It does not show, and is not supposed to show any notifications

Alright. The "New Mail Notification" header threw me off, but I guess the counter being the notification makes sense. 

So the absent counter is the only issue. Logs show the same couple lines every second when "force re-read" is enabled to that interval. 

```
2020-07-28 19:59:13 Unread counter for C:/Users/USERNAME/AppData/Roaming/Thunderbird/Profiles/ID_STRING.default-release/ImapMail/imap.gmail.com/INBOX.msf: 2 
2020-07-28 19:59:14 Triggering the unread counter update 
```

`INBOX.msf: 2 ` updates reliably to however many unread emails there are. "Show unread count" checkbox is ticked. No counter at all though.

**Comment by gyunaev** [comment]
Standard icon is used? Resonable notification font  and size? Account notification color is not set to white or something?

**Comment by narcolepticinsomniac** [comment]
> Standard icon is used?

Yep.

>Resonable notification font and size? Account notification color is not set to white or something?

Font seems to be the issue. Default didn't work, so I test a few others in the dropdown, which I knew were installed, but no dice. Just switched to reliable old Arial, and the counter showed up. 

Appreciate the assist. Any hope of it working reliably without forcing re-read? Probably negligible difference resource-wise, but in my head, it seems like using an infinite setInterval loop over a mutation observer.
