### ISSUE TITLE
Icons get reset to default after restart (Win10)

### ISSUE THREAD

**Issue by pizzapls** [gyunaev/birdtray#392]
**OS**: Windows 10 64-bit Build 19041.423
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.11.0 64-bit
**Birdtray origin**: From installer

**Description**
After Birdtray is closed and started again, if the icon and/or the icon for unread messages were changed, both get reset to their default.

**Expected behavior**
I expect those changes to be saved.

**To Reproduce**
1. Make those changes again.
2. Close and restart the application.

**Additional context**
I have saved those custom icons in "C:\Program Files\Birdtray". Both are png files with 256x256 pixels and 32 bit depth.

**Comment by Abestanis** [comment]
Hi, sorry for the late response. This looks like the same problem as #356. Your icon may have been saved with an invalid color profile. This causes some problems with Birdtray when saving the image in the settings, so starting with the next version Birdtray will detect these images and display a warning when you select them in the settings.
The solution is to re-save the file, maybe try a different image format. It should be noted that the `Windows Paint` program doesn't fix the issue, but for example [Gimp](https://www.gimp.org/) does.

If that doesn't fix the problem or if you are unable to convert the image, please upload it here.
