### ISSUE TITLE
Cant locate profile

### ISSUE THREAD

**Issue by andreluizmg** [gyunaev/birdtray#393]
**OS**: <Win10 2004>
**Birdtray version**: <1.8.1>
**Thunderbird version**: <78.1.1 (32-bit)>
**Birdtray origin**: <"From installer">

**Description**
<Cant find my profile since i moved location from C:\Users\andre\AppData\Roaming\Thunderbird\Profiles\tzp97utj.default-release\ImapMail\imap.gmail.com to E:\Arquivo de Programas\gmail.default   for storage space reasons...>
tried to to point to or find the new location but did not work
Thanks

![image](https://user-images.githubusercontent.com/26634756/90437764-46ca9d80-e0a9-11ea-8a11-e88c7acee61c.png)
![image](https://user-images.githubusercontent.com/26634756/90437813-59dd6d80-e0a9-11ea-8f63-931ae19be220.png)
![image](https://user-images.githubusercontent.com/26634756/90536122-06732a00-e152-11ea-8e22-6b6c88fb7a0d.png)

**Comment by Abestanis** [comment]
Sorry for the late response.

Birdtray expects the accounts to be in the default folder structure that Thunderbird uses. This means there should be a folder for the Thunderbird profile (in your case that was `tzp97utj.default-release`), which contains a folder indicating the type of the mail account (usually `ImapMail`), which then contains the folder for the mail account (in your case that was `imap.gmail.com`). So if you create a folder structure like this `E:\Arquivo de Programas\Thunderbird Profile\ImapMail\gmail.default` and point Birdtray to `E:\Arquivo de Programas\Thunderbird Profile`, it will find your mail account.

There is also a second option, though it is a bit more advanced: If you hold the keys <kbd>Ctrl</kbd> and <kbd>Shift</kbd> when clicking the `Adicionar` button, you get a file chooser dialog where you can directly choose the `.msf` files to watch.

**Comment by therob84** [comment]
> There is also a second option, though it is a bit more advanced: If you hold the keys Ctrl and Shift when clicking the `Adicionar` button, you get a file chooser dialog where you can directly choose the `.msf` files to watch.

That was the solution for my problem: I was not able to point Birdtray under Linux Mint 20 (Ubuntu 20.04) to a maybe non-standard profile folder of Thunderbird Portable created and used in parallel under Windows 10. But thanks to the tip I could directly choose the .msf file.
**My suggestion**: make a tooltip/label/description of the button in the program to document this function. I needed some time to find this thread.

**Comment by Abestanis** [comment]
@andreluizmg I hope I could help you solve the problem. Please reopen, if you still have an issue.

@therob84 Yeah, it was not easily discoverable. In the latest version of Birdtray the `Add` button has a tooltip that mentions the information (See #354).
