### ISSUE TITLE
Birdtray should normalize TB on left click, move settings and the like to right click menu

### ISSUE THREAD

**Issue by adefaria** [gyunaev/birdtray#395]
During normal usage, the most common action is that you receive an email and you want to normalize Thunderbird to read the new email. Thus this action should require the least number of clicks/actions. This is not currently the case. When an email comes in you are alerted and you left-click on the tray icon and a menu appears. You then have to select Show Thunderbird. I would suggest instead that a single left click does the most frequent action - show me Thunderbird. 

Also, I would think that if TB is not minimized but rather say behind another window, TB is surfaced to the top. As it stands now if you have a full-screen app and TB is underneath it, when you left-click the icon you'll see a Hide Thunderbird. I don't want to hide it then have to left-click the icon again and then click Show Thunderbird. I just want to left-click the icon and Thunderbird should appear so I can see it.

Then move all the other menu entries to a more infrequently used right-click option.

Now I see that birdtray runs in the tray which for me is Indicator Applet Complete. And it seems that all right-clicks merely bring up the About menu item for Indicator Applet Complete so perhaps this is not doable. I don't know if there's an option to have an applet running in Indicator App Complete to be able to override the right-click or if there's an option to allow say Ctrl-left-click for the menu.

Finally, I might add that the icons in the icon tray are rather small and do not resize when gnome-panel resizes. I exaggerated my gnome-panel size to show how application icons do resize but the Indicator Applet Complete does not resize with it. Is there a way for birdtray to not be confined to the tray?

![indicator](https://user-images.githubusercontent.com/2692127/91366895-d9f68800-e7b9-11ea-8962-aaa7b45899bc.png)

**Comment by gyunaev** [comment]
This is the problem with your desktop manager. In KDE left click normalizes Thunderbird, and right click shows menu.

**Comment by adefaria** [comment]
I use Gnome. Are you saying you don't wish to support Gnome?

**Comment by gyunaev** [comment]
The application *works* on Gnome, it just doesn't work as you'd like it to work. And this seem to be a Gnome problem. Are there any other Gnome systray applications which work as you describe (i.e. pop up menu on right click)?

**Comment by adefaria** [comment]
Sorry, never got an email indicating that you posted.

No, everything in the indicator-complete applet that contains the systray only shows "About" when right-clicked and the About talks only about the version of indicator-complete. Perhaps this could be implemented as something that runs outside 
of systray? Inside of the systray, the icon also looks really small (have 4k monitors with high res). I mady my top gnome-panel large to show that the icons in the systray on the right are still small.

![systray](https://user-images.githubusercontent.com/2692127/93119359-88ce0b80-f676-11ea-9928-ce616317efb0.png)

I  know, systray is the natural place for this to be but apparently, it has some limitations (right-click, icon size).

Yes, it works on Gnome but not exactly like I'd like. Still seems to be the best solution for mail notification for TB though. Thanks.
