### ISSUE TITLE
Support for multiple instances running / thunderbird profiles

### ISSUE THREAD

**Issue by quizilkend** [gyunaev/birdtray#396]
Hey,

I have two thunderbird profiles (work/private) and would like to use birdtray for both of them.
Is this possible at the moment?

Best wishes.

**Comment by gyunaev** [comment]
You'd need two configurations of birdtray.

**Comment by quizilkend** [comment]
Thanks for your reply. Is there a command line option for birdtray to use a specific config file?

**Comment by gyunaev** [comment]
Kinda. If you launch Birdtray and there is a config file birdtray-config.json in the same directory as Birdtray, it will use this file.

**Comment by quizilkend** [comment]
Cool, thanks. That resolves my issue!
