### ISSUE TITLE
Problem with context menu and red X

### ISSUE THREAD

**Issue by ampped101** [gyunaev/birdtray#397]
I am on the latest. I have been using this since release. 

Windows 10 Newest.

Starting a little while ago all birdtray will show is the red x and will not bring up TB. There is no right click menu on the icon and I have to force close the app and try to restart it. When I do restart it, it will show notification for new mail but same issue with the red x and no menu. 

I tried to uninstall via removing settings and reset it up but same issue.

**Comment by ampped101** [comment]
Fixed finally! I had been removing accounts from TB. If you remove an account from TB and do not remove it from Birdtray watch first..it will cause this issue. I went into the config file and removed it manually.

Thanks @gyunaev  for the work on this.

**Comment by Abestanis** [comment]
Ok, I just tested this and this is definitely a bug. It doesn't even show an icon for me, because it hangs in an infinite loop. Thank you for reporting this.
