### ISSUE TITLE
Problem with unread Mails in Maildir format

### ISSUE THREAD

**Issue by quizilkend** [gyunaev/birdtray#398]
**OS**: Debian Buster 64x
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.12.0
**Birdtray origin**: From Source
**Qt version**: 5.11.3

**Description**

Add a folder to be monitored. Birdtray shows a wrong number of Mails, even if the folder is repaired in Thunderbird.
I noticed that the errorneous folder is the only folder in maildir format.

**Expected behavior**

Birdtray should show the correct number of unread Mails.

**To Reproduce**

See description.

**Comment by gyunaev** [comment]
Maildir support in Thunderbird is still buggy and not recommended for daily use.

Can you do the following:

- Create an empty maildir box;
- add a couple of emails there **from your spam folder** (make sure they are not flagged unread);
- exit thunderbird
- make a copy of the .msf file for this folder as 1.msf
- open thunderbird and make one of emails unread;
- exit thunderbird
- make a copy of the .msf file for this folder as 2.msf
- post 1.msf and 2.msf here?

**Comment by quizilkend** [comment]
Hey,
I'm very sorry. I was just about to follow your steps, as I saw that my profile folders are pretty messed up (because of the migration from icedove to thunderbird in debian).
I fixed my profile folder and now it works like a charm - even with maildir.

Will it be helpful for you if I send you the requested msf files nevertheless?

**Comment by gyunaev** [comment]
Thank you for letting us know. No, at this moment no need to send those files as maildir seem to use the same format.
