### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by gdfox** [gyunaev/birdtray#4]
I compiled and get the following when I run ./birdtray.

QWidget::insertAction: Attempt to insert null action
UnreadCounter generated an error: Error opening sqlite database: unable to open database file

I am running Manjaro KDE.

Thanks...

**Comment by JackDinn** [comment]
sounds a bit like its not finding your thunderbird sqlite DB , did you point it to your ~/.thunderbird/_profile_.default/ folder in the settings? Check there is a global-messages-db.sqlite file in their too.

**Comment by gdfox** [comment]
Where do I set the TB folder settings? and yes, there is a global-messages-db.sqlite file in the directory.

**Comment by JackDinn** [comment]
so when you run ./birdtray do you get the tray icon anywhere at all? (it might be a hidden icon on your tray) it should have a big red cross on it. right click it and goto settings.

**Comment by gdfox** [comment]
Yes. I found it. It was in the hidden part of my system tray. I set it to the directory and it seems to be working. Thanks again.

**Comment by JackDinn** [comment]
NP :-)

**Comment by gdfox** [comment]
Just ran into another issue.

After setting, I restarted. It restarted, but I left clicked on the icon, it disappeared. When I restarted it, I get the following:

$ ./birdtray
QWidget::insertAction: Attempt to insert null action
List of all IDs: 

It is show running in KSysGuard, but no icon in the tray.

**Comment by JackDinn** [comment]
Hmm, not sure. If you are sure both TB and birdtray are both closed and then when you run birdtray you get your error. 
I would prob start again. delete the birdtray folder and everything in it. maybe even delete /home/user/.config/ulduzsoft folder, git clone it again, build it again etc.

Might also try setting the tray icon to be "shown" in the kde system tray settings (thats how mine is so i just guessing at anything here).

Im using Manjaro KDE too and its working for me so if a re-install does not solve it you might need the dev to have a look.

**Comment by gdfox** [comment]
I recompiled it. I also move birdtray app to the .thunderbird directory. It is working now. I have also set it to "shown" in the tray. 

Thanks.

**Comment by JackDinn** [comment]
o yea and dont forget there is a KDE bug in the system tray settings if you do change the icon to be "shown" it will probably bugger up the tray. you might have to reset plasma with `kquitapp5 plasmashell & kstart5 plasmashell` or logout and back in.

**Comment by JackDinn** [comment]
good good, glad you got it working as there was nothing more annoying than spending the last 5 months trolling through all the mail clients ^^

**Comment by gyunaev** [comment]
Fixed "QWidget::insertAction: Attempt to insert null action" as well.
