### ISSUE TITLE
Feature Request: Iconify on close

### ISSUE THREAD

**Issue by trizt** [gyunaev/birdtray#40]
I have recently installed BirdTray and tested it and one feature I feel is missing is that when pressing the close application in the window decoration, I wish it could iconify to the tray like FireTray does.
I know you can almost get it by enable the "restart thunderbird if it was closed", but if flashes on the screen and also you would loose what you are doing at the moment.

**Comment by gyunaev** [comment]
This is not possible from an external application.

**Comment by trizt** [comment]
You have xprop, could remove the _NET_WM_ACTION_CLOSE for the window in question

**Comment by gyunaev** [comment]
It doesn't have any effect.
