### ISSUE TITLE
Release 1.9.0 is coming on Oct 10 - translators, please update!

### ISSUE THREAD

**Issue by gyunaev** [gyunaev/birdtray#400]
String freeze as of today - no PRs which add/modify strings will be merged in the next two weeks.

Please make sure the translations are up-to-date, and new strings are added.

**Comment by Abestanis** [comment]
@gyunaev We need to add the username of the translators, otherwise they won't get notified. I don't think they subscribed to get notifications for all issues from this repository.

**Comment by Abestanis** [comment]
Hi translators

@Vistaus
@albanobattistella
@igorruckert
@KOV70
@eson57

We are creating a new release of Birdtray. If you have the time, please make sure the translations are up-to-date, and new strings  are added. We notify you because you indicated in [translators.md](https://github.com/gyunaev/birdtray/blob/master/src/res/translators.md) that you want to be notified.

**Comment by gyunaev** [comment]
Understood. Let's move the release date one week ahead then?

**Comment by Abestanis** [comment]
Yeah, I think that is a good idea.

**Comment by albanobattistella** [comment]
OK..this W/E.
________________________________
Da: Abestanis <notifications@github.com>
Inviato: martedì 29 settembre 2020 20:26
A: gyunaev/birdtray <birdtray@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [gyunaev/birdtray] Release 1.9.0 is coming on Sep 30 - translators, please update! (#400)


Yeah, I think that is a good idea.

**Comment by gyunaev** [comment]
Oct 10 then.

**Comment by gyunaev** [comment]
If anyone needs more time, please let us know here.

**Comment by Abestanis** [comment]
Looks like #399 and #419 need a bit more time.

**Comment by Abestanis** [comment]
Ok, so the only translations which still need updates are the Turkish translation, for which we don't have an active maintainer, and the Swedish translation. @eson57 Could you please let us know if you will be able to update the Swedish translation during the week?

**Comment by eson57** [comment]
Sorry, I can't continue translate the app any more. To much work ahead of me.

**Comment by Abestanis** [comment]
Ok, no problem. Do you think you will have time again for the release after that or do you want as to remove you from the active maintainers list, so we don't notify you in the future?

**Comment by albanobattistella** [comment]
I'm ready fo help you!

Regards,

Albano
________________________________
Da: Abestanis <notifications@github.com>
Inviato: lunedì 12 ottobre 2020 21:57
A: gyunaev/birdtray <birdtray@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [gyunaev/birdtray] Release 1.9.0 is coming on Oct 10 - translators, please update! (#400)


Ok, no problem. Do you think you will have time again for the release after that or do you want as to remove you from the active maintainers list, so we don't notify you in the future?

**Comment by Abestanis** [comment]
@albanobattistella My bad, the question was directed at @eson57, I should have addressed him directly. I realize that this is is probably not easy to see if you only follow this thread via mail. Thanks again for updating the Italian translation.

> I'm ready to help you!

Or do you mean that you want to help updating the Swedish translation? I'm a bit unsure on how to interpret your message, sorry.

**Comment by Abestanis** [comment]
Better late than never: `1.9.0` is [released](https://github.com/gyunaev/birdtray/releases/tag/v1.9.0) now.

**Comment by gyunaev** [comment]
Thank you very much @Abestanis and everyone who contributed to this release!
