### ISSUE TITLE
Thunderbird window does not hide on login

### ISSUE THREAD

**Issue by Voczi** [gyunaev/birdtray#415]
**OS**: Windows 10 x64 v2004
**Birdtray version**: 1.8.1
**Thunderbird version**: 78.3.1
**Birdtray origin**: From installer
**Qt version**: _NA_ 

**Description**
The Thunderbird window shows up on login, even if you have set it to hide on tray when it starts.

**Expected behavior**
The Thunderbird window should hide upon login.

**To Reproduce**
1. Make sure that Birdtray is set to start up on login, by creating a shortcut to the Birdtray in shell:startup.
2. Set Birdtray to start Thunderbird 0 seconds after it has launched and hide it in the tray.
3. Log into your user account.
4. Thunderbird window shows up even if it was set to be hidden in the tray.

**Additional context**
This bug happens roughly one third of the times logging in.

**Comment by gyunaev** [comment]
Might need to change 0 seconds to 5+ seconds if you do it on login.

**Comment by Voczi** [comment]
> 
> 
> change 0 seconds to 5+ seconds

Set it to 5 seconds. Not sure why half of the Birdtray features require workarounds to be used reliably. This behavior on a clean install indicates that there is something inherently wrong with the code, rather than some incompatibility with third-party applications.

**Comment by gyunaev** [comment]
This means you shouldn't be using Birdtray, sorry. Please uninstall it and forget about it.

**Comment by Abestanis** [comment]
> This behavior on a clean install indicates that there is something inherently wrong with the code, rather than some incompatibility with third-party applications.

I guess you could have phrased that differently. You are more than welcome to help us improve the code, but this comment neither helps us nor you. We do appreciate feedback and it is ok to criticize, but please use constructive criticism.
And also keep in mind that we are doing this in our free time, we are not getting payed and there isn't a big company working on this, so please manage your expectations accordingly.

To diagnose this problem, I'm going to need more information. Can you please share your configuration on the `Hiding` tab. Also, can you please try and see if the problem also happens if you close and open Birdtray manually, or if it only happens directly after login.

**Comment by Abestanis** [comment]
> Make sure that Birdtray is set to start up on login, by creating a shortcut to the Birdtray in shell:startup.

As a side note: Did you know that the installer has an option to configure Birdtray to automatically start on login?

**Comment by Voczi** [comment]
> 
> 
> I guess you could have phrased that differently. You are more than welcome to help us improve the code, but this comment neither helps us nor you. We do appreciate feedback and it is ok to criticize, but please use constructive criticism.
> And also keep in mind that we are doing this in our free time, we are not getting payed and there isn't a big company working on this, so please manage your expectations accordingly.

Yes, I completely understand that. But as seen in this issue, and then issue #414 and #416, @gyunaev took these bug reports as a personal problem and just closed 2/3 of them. My issue is only with him and his attitude.

> 
> Can you please share your configuration on the `Hiding` tab.

This is the "normal" configuration that I always used with Birdtray.
![birdtray_9dDIGhbusX](https://user-images.githubusercontent.com/62214162/95168913-506fa800-07b2-11eb-85a9-d22facaca58a.png)

>
> Also, can you please try and see if the problem also happens if you close and open Birdtray manually, or if it only happens directly after login.

It only happens after login, I've never really had any issues with opening Birdtray manually.

> 
> As a side note: Did you know that the installer has an option to configure Birdtray to automatically start on login?

I didn't actually know that it had that option in Windows, I just put a shortcut to the program in shell:startup. But thank you! I thought that the feature was only available on Linux.

**Comment by gyunaev** [comment]
> Yes, I completely understand that. But as seen in this issue, and then issue #414 and #416, @gyunaev took these bug reports as a personal problem and just closed 2/3 of them. My issue is only with him and his attitude.

I'm unsure whether you understood the above, but you are using free software which we develop in our free time. Considering that and your attitude, I do repeat my suggestion that you should not be using birdtray in the first place.

**Comment by Voczi** [comment]
> 
> You are essentially asking someone else to spend their free time to fix _your_ issues.

I have never asked anything of you, or the contributors, to fix _**anything**_. I am simply providing bug reports for issues that exist in _**your**_ project.

> 
> Considering that and your expectations - which fit better in the commercial software world - I do repeat my suggestion that you should not be using birdtray in the first place.

And to clarify, yet again, my expectations were never that my issues would be solved. Just that I wouldn't have to wait until the second time around to have someone display very, very basic human decency to me.

Worthless to continue on this back and forth, there are obviously some outside .. _issues_ .. unrelated to this matter.
