### ISSUE TITLE
Clicking the icon when Thunderbird is not running does nothing

### ISSUE THREAD

**Issue by geekley** [gyunaev/birdtray#420]
### Clicking the icon when Thunderbird is not running should start it
**Description**
When Thunderbird is not running (red X), clicking the icon should start it. That is, the default context menu action should be "Start Thunderbird" instead of a disabled "Hide Thunderbird". This way, you have the option to disable settings like "Restart Thunderbird if it was closed" and "Start Thunderbird when Birdtray starts".

**Comment by gyunaev** [comment]
> When Thunderbird is not running (red X), clicking the icon should start it.

I totally don't see why it should. Could you please elaborate?

**Comment by Abestanis** [comment]
I think I understand. When using Birdtray you are used that Thunderbird will show up if you click the system tray icon. This currently doesn't happen, nothing happens instead. Adding this feature would give the user more control on when we start Thunderbird and would allow to close it (for example to prevent receiving new mails during a presentation or something along those lines) without going into the settings and disabling `Restart Thunderbird if it was closed`.

In my opinion, this is a great suggestion. 👍 
If I have some time I will definitely look at this after the release.

**Comment by geekley** [comment]
It seems Birdtray already has the ability to start Thunderbird (since you can set the path in settings), but only by auto-starting or auto-fixing "accidental" closing. But, like Abestanis said, closing might not always be accidental.
That's why there is the option to let Birdtray run without Thunderbird running, and even detect this situation.
So, since Birdtray can detect this problem, and it's easily fixable (by starting the program) it's only natural for users to expect that clicking the icon would make Thunderbird show up, without worrying about whether or not it's running.

Here's an analogy. Think about the app launchers in a phone. When you click the icon, do you want to have to think about whether or not the app is running? No need, the app starts if it wasn't running, otherwise it's brought back to foreground. This is especially true for single-instance apps or services meant to be left running in background, like an email app.

@gyunaev So to answer your question, it's for consistency with the fact that:
- you already make Thunderbird appear by clicking (why should it be only when it's running?);
- no other action would make sense to happen by clicking in this state (like opening settings, that would be inconsistent);
- you have the option to let Birdtray run separately from Thunderbird, judging by the available settings;
- a good extension to a program is one that makes you feel as if it was a native feature;
  So you wouldn't want to have to think too much of Thunderbird and Birdtray as 2 separate programs. That means users think of the Birdtray icon as "the Thunderbird icon". With this perspective, it makes sense that "the email service isn't running" makes you expect an easy action to fix this situation.

BTW, I was thinking that "Start Thunderbird" action should already bring it to foreground (app launcher behavior), but you might also make it so it just starts the app hidden in background (service behavior) and let users decide if they want to click again to show the window. Either implementation is fine: first is more consistent, while second provides better usability.
