### ISSUE TITLE
Improvements on unread mail notifications (allow making only important folders blink)

### ISSUE THREAD

**Issue by geekley** [gyunaev/birdtray#421]
### Option to use colored dot instead of number for unread notifications
**Description**
You could add an option to display unread notifications as a colored dot in the corner of the icon, instead of a number. This way you can make use of the current feature of being able to set it to be a different color if the unread email is, for example, in a Spam folder. I suggest it be a circle with white border and filled with the chosen color, so it stands out on any BG icon; and place it in lower right corner, with a size like 25% of width and height.

### Display unread numbers in the hover tooltip on systray
(Particularly useful if previous feature is implemented) (Desktop: KDE Plasma)

**Description**
You can make it so that hovering the icon on systray shows the unread count on each folder that has unread mail; and show "Thunderbird" instead of "birdtray", so it feels more like a native feature of Thunderbird. If necessary, you can add a field to associate folders with the email account name.

**Example**
> **Thunderbird**
> example1<span>@</span>gmail.com /INBOX (2)
> example2<span>@</span>gmail.com /[Gmail]/Spam (1)

Or, if you could set custom account names:
>**Thunderbird**
> Personal /INBOX (2)
> Work /[Gmail]/Spam (1)

**Comment by gyunaev** [comment]
1. "Use colored dot instead of number for unread notifications" could be done already:

- Get a current Birdtray icon from Git;
- Modify it with your favorite editor and put a dot of it with whatever color, size etc you'd like;
- Birdtray Settings -> Checkbox "Different icon when unread" -> set your icon;
- Uncheck "show unread count".

2. Modification of tooltip notification is only supported on some platforms, and generally would require desktop manager-specific code.

**Comment by Abestanis** [comment]
Hang on, this is not entirely true.

> "Use colored dot instead of number for unread notifications" could be done already:

I think he is requesting that the color of the dot matches the selected color of the folder in the setting. That is currently not possible.

> Modification of tooltip notification is only supported on some platforms, and generally would require desktop manager-specific code.

This is also not true, see [here](https://github.com/gyunaev/birdtray/blob/master/src/trayicon.cpp#L320). But this feature has already been requested in #163, so @geekley subscribe to that thread if you want to get updates on it.

**Comment by gyunaev** [comment]
Yeah, then I'd rather allow setting a different icon for a different folder than creating a "dot designer" allowing to specify the dot size, position and gradient, for which everyone would like it differently.

The code to set tooltips is there, but whether or not they will be shown depends on desktop manager. For example, the current code shows nothing on KDE, I just see standard "Birdrtay" tooltip.

**Comment by Abestanis** [comment]
> I'd rather allow setting a different icon for a different folder

Wow, that is an awesome idea! It has a lot more potential, let's do that.

> Windows is the only platform where system tray tooltips are shown consistently.

Ah, I see. Well, there is not much that we can do about it. Hopefully Qt will find some solution in the future that works for more desktop managers.

**Comment by gyunaev** [comment]
It's not just Qt - the system tray Linux standard doesn't have support for tooltips, so everyone is doing it differently. To show them on KDE, need to use KDE APIs, on Gnome use Gnome APIs etc.

**Comment by gyunaev** [comment]
> Wow, that is an awesome idea! It has a lot more potential, let's do that.

And another icon when there are multiple emails from several folders. Gonna be painful to setup.

**Comment by geekley** [comment]
> "Use colored dot instead of number for unread notifications" could be done already [...] Checkbox "Different icon when unread"

Yeah, that workaround is what I intended to do initially, before changing it to blink instead. Thanks @gyunaev !

> I'd rather allow setting a different icon for a different folder
> It has a lot more potential
> And another icon when there are multiple emails from several folders. Gonna be painful to setup.

I agree, but I think that might be an overkill.
Actually, you guys just made me think of an idea that might be better for the use case of "separating spam/personal email from important/work email". Instead of making every folder's override be a separate icon, you can make it so blinking is doable based on folder. So, each folder would simply have a boolean field for blinking. If there is unread email on any important folder (one set to blink) the icon blinks, in addition to current behavior (like changing icon or number/color).

This way you could make it so, for example, INBOX blinks while Spam just changes icon discreetly.
Or one could make Work/INBOX blink, while keeping the numbers and colors to differentiate other folders.
I think with this, you can do more utility with less implementation.

**Comment by geekley** [comment]
> creating a "dot designer" allowing to specify the dot size, position and gradient, for which everyone would like it differently
> I think he is requesting that the color of the dot matches the selected color of the folder in the setting. That is currently not possible.

Sorry if I wasn't clear, my bad. That's also true, but the main reason I suggested the colored dot with white border was mostly so it stands out on any BG icon. I suggested that because it's a problem the current numbers have: they don't look good on most icons. The number is big in the center, and thin without a border so the color "touches" the BG icon.

It's not quite that I think you should make a "dot designer" because everyone could like it differently. It's more about making it stand out on any icon without covering the icon in a way that doesn't fit well.

Think about how browser extensions (like adblockers and userscripts) show a number next to the icon. It's a colored square with the number in black or white to make contrast on the color. That's more like what I had in mind. With a proper implementation you don't even need customization.
Browser extensions display numbers that cover the icon only partially, so you can still identify the icon and it doesn't break layout:
Example on Firefox: ![Firefox extensions example](https://user-images.githubusercontent.com/38332912/95805500-f011c680-0cdb-11eb-89c7-45d6a7e7237c.png) Dot on KDE Plasma systray: ![Dot notification example on KDE Plasma](https://user-images.githubusercontent.com/38332912/95806927-53e9be80-0cdf-11eb-8cf9-aab193ef76cd.png)

Of course, in the case of browser extensions, you can see that they actually have more space than the icon size.
So I suggested the dot because it's a simpler version of that (and for some use cases, the number itself isn't that important, because it doesn't tell you whether or not you have important mail). I suggested a dot for simplicity (and personal preference) and because it's easily identifiable, but the ideal would be to also improve the number display to make it a little more like browser extensions (though it might be impossible to do it well without that additional space, like in browsers).

**Comment by gyunaev** [comment]
Well, the problem with drawing a single dot - which I agree is very easy - is that pretty soon we gonna be asked to add more options, such as "my desktop manager XYZ uses smaller notification dots and centers them over the icon". So we'd end up with a "dot editor", allowing the users to change the dot size, position, transparency, etc. Then someone says "let's have a bigger dot when there are more unread emails"... and we will end up with a "dot editor" looking like Gimp.
