### ISSUE TITLE
Settings UI: Blinking speed is reversed

### ISSUE THREAD

**Issue by geekley** [gyunaev/birdtray#422]
**OS**: Kubuntu 20.04; KDE Plasma
**Birdtray version**: 1.8.0 compiled at Apr 20 2020 00:31:15.
**Thunderbird version**: Not applicable
**Birdtray origin**: "From package manager"; APT version for birdtray: 1.8.0+ds-1

**Description**
In settings UI, the blinking speed field is reversed.
Off: No blinking, OK
Off +1: Fast blinking
Max (it says "Fastest"): Slow blinking

**Expected behavior**
Adjusting the slider should go from slow to fast; or the max end should say "slowest" instead of "fastest".

**To Reproduce**
1. Open settings
2. Try different positions in the slider

**Comment by Abestanis** [comment]
Hi, thank you for the report. This was already fixed in #359 and will be included in the next release, which should happen in the next few days.

**Comment by geekley** [comment]
OK, thanks!
