### ISSUE TITLE
BirdTray struggles to restart ThunderBird

### ISSUE THREAD

**Issue by n1ce-0ne** [gyunaev/birdtray#427]
**OS**: Windows 10 x64
**Birdtray version**: Birdtray version 1.9.0 compiled at Oct 20 2020 23:00:56 using Qt 5.14.1. [started just before this version]
**Thunderbird version**: 78.3.3 (32-bit)
**Birdtray origin**: From installer
**Description**
when i close thunderbird it used to restart again no problem but now throws this error 1st

**Expected behavior**
just restart without the error window like it used to

**To Reproduce**
open thunderbird from tray icon to read messages then close so birdtray can reset itself

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/67670512/97161596-f68d4d00-1775-11eb-9a16-7fc689cccb85.jpg)

**Comment by Abestanis** [comment]
Hi, out of curiosity, did you close this because it only happened one time? The error message indicates that Thunderbird has crashed right as you closed it. If it would have ended normally, this dialog would not have popped up.

**Comment by n1ce-0ne** [comment]
hey, no i closed it simply because im not 100% sure if its a BirdTray issue or Thunderbird issue.

it happens every time i close thunderbird so BirdTray can reset itself back no 'no new messages'

correct me if im wrong but im sure i have to do that[close tb after ive read new emails] to keep BirdTray updated

**Comment by gyunaev** [comment]
> open thunderbird from tray icon to read messages then close so birdtray can reset itself

Settings -> Advanced -> [X] Force index reread every 3 seconds

should help you here.

**Comment by n1ce-0ne** [comment]
Excellent thank-you very very much, ive enabled that setting now & set to 5 seconds, im more than happy at 5.

when i set this up i didn't realise what 'index file' actually did,

may i suggest a rename to 'force status re-fresh'

it may help others in the future, if not its all good, much appreciated gyunaev
