### ISSUE TITLE
Birdtray won't boot with windows 10

### ISSUE THREAD

**Issue by Radiolaredo** [gyunaev/birdtray#431]
Hallo!!!

I have a problem. I include the Birdtray shortcut in the windows startup folder to boot into the system, but it doesn't work. I have tried with my user boot and also all users boot. Could you help me? Thank you very much.

My Windows version is: Windows 10 Pro 19042.572

**Comment by Abestanis** [comment]
Hi, which version of Birdtray are you using? What is the full path of the startup folder in which you placed the shortcut? Is Birdtray running in the background (do you see it in the task manager)?

If you installed Birdtray with the installer, there is an option in the installer to configure Windows to start Birdtray after login. Did you try using that?

**Comment by n1ce-0ne** [comment]
also did you manually run the shortcut to check it works correctly.

thats how i start BirdTray on win10 home edition, shortcut in startup folder.
"C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"

works great on my setup.

**Comment by Radiolaredo** [comment]
Abestanis & n1ce-0ne, Thanks for your help. Fixed problem. I uninstalled and reinstalled. I hadn't seen the option the first time.
Cheers

**Comment by Abestanis** [comment]
I'm glad it worked for you.
