### ISSUE TITLE
cannot connect to server

### ISSUE THREAD

**Issue by genfixo** [gyunaev/birdtray#438]
when thunderbird starts it checks for connection , if no connection found it send a pop up notification "failed to connect to server"

is there any way to disbale this popup , so bascially let thunderbird autodetect if offline or online

**Comment by gyunaev** [comment]
> when thunderbird starts it checks for connection , if no connection found it send a pop up notification "failed to connect to server"

You mean when Birdtray starts? This is not Thunderbird bug tracker.
