### ISSUE TITLE
Unable to read from .msf after folder repair 

### ISSUE THREAD

**Issue by L-U-T-i** [gyunaev/birdtray#439]
OS: CentOS 7.9 - linux

Linux Desktop Manager: mate desktop 1.16

Birdtray version: 1.8.1, self built

Thunderbird version: 78.4.0-1.el7.centos.x86_64

Birdtray origin: self built RPM (no errors / warnings during built process)
Qt version: Qt_5.9 (64bit) - qt5-qtbase-5.9.7-4.el7.x86_64

Description
After certain folder repair in Thunderbird, an exclamation mark appears over the unread messages counter in tray icon, and tooltip says "Unable to read from ... msf" for that file (.msf file corresponding to that folder). It doesn't happen if Inbox (or, Sent or any other not monitored folder of course...) is repaired, but when some subfolder of Inbox (or a subfolder within Inbox) which is monitored for new messages and doesn't have any further subfolders below is repaired.

This didn't happen before recent updates, but can not say weather it was introduced with the last Birdtray update(s) (less probable) or with the latest Thunderbird update (more probable by my opinion). In any case, this didn't happen before. Restarting Thunderbird doesn't help, but after Birdtray restart everything went to normal.

Expected behavior
Folder repair within Thunderbird doesn't cause Birdtray to be unable to read a corresponding .msf file until restart.

To Reproduce
1. Have Thunderbird 78.4.0 installed
2. Have Birdtray 1.8.1 installed
3. Have some subfolder structure below (within) an Inbox with those subfolders being monitored by Birdtray (for example: Inbox with TEST1 and TEST2 subfolders, and TEST3, TEST4 and TEST5 subfolders within TEST2) - select all those subfolders to be monitored by Birdtray for new messages
4. In Thunderbird, (right) click "Properties" for TEST1 or any of TEST3÷TEST5, and choose "Repair Folder" - you should see an exclamation mark over the tray icon now; repairing folder for Inbox or TEST2 shoouldn't trigger that by my observation...)

Screenshots
![Screenshot at 2020-11-18 12-08-06](https://user-images.githubusercontent.com/50832205/99523324-358a7900-2997-11eb-9a61-08513289ddd6.png)

**Comment by gyunaev** [comment]
In this case you have to delete the monitored accounts, and re-add them - should work again.

**Comment by L-U-T-i** [comment]
Do you mean to delete .msf file, or a line in birdtray settings?

And, shall it be like that by design, or is it a kind of workaround? In any case, it is more simple to restart birdtray, isn't it?

In any case, I've just reported it because I don't think it is an intentional behavior...

**Comment by gyunaev** [comment]
In Birdtray settings. Or restard birdtray.

**Comment by Abestanis** [comment]
To clarify: The warning was added by Birdtray and it notifies you of an actual problem, in your case it can't couldn't open the mork file to read the amount of unread emails. In that case it reports `0` unread emails, which could be wrong, hence the warning. Previous versions of Birdtray just ignored the this.

The warning should go away as soon as Birdtray successfully reads the mork file again. So you need to trigger a re-read of the mork file, either by changing the file (Thunderbird does that when you receive a new mail or change the unread status of a mail) or you can open the Birdtray settings and close them again via the `Ok` button.
