### ISSUE TITLE
birdtray constantly re-adds unwanted folders into `accounts to monitor`

### ISSUE THREAD

**Issue by sapiens-sapide** [gyunaev/birdtray#44]
I set birdtray to monitor 3 smartfolders within 3 accounts of mine, but birdtray will always add …/…/INBOX.msf to the `accounts to monitor` list on its own… I end with too much folders monitored and incorrect unread count.  
Each time I `remove`…/…/INBOX.msf folders, they are re-added by birdtray after I close the settings window.

**Comment by gyunaev** [comment]
This is strange. Birdtray does not add any "default" monitored accounts. Can you show the content of the [accounts] section of file ~/.config/ulduzsoft/birdtray.conf ?

**Comment by sapiens-sapide** [comment]
```
cat ~/.config/ulduzsoft/birdtray.conf 
[accounts]
account0Color=#ef2929
account0URI=/home/stan/.thunderbird/hqbjrtov.default/ImapMail/box.mailden-1.net/INBOX.msf
account1Color=#ef2929
account1URI=/home/stan/.thunderbird/hqbjrtov.default/ImapMail/box.mailden-1.net/recents.msf
account2Color=#ef2929
account2URI=/home/stan/.thunderbird/hqbjrtov.default/ImapMail/box.mailden.net/recents.msf
account3Color=#ef2929
account3URI=/home/stan/.thunderbird/hqbjrtov.default/ImapMail/box.mailden-2.net/INBOX.msf
account4Color=#ef2929
account4URI=/home/stan/.thunderbird/hqbjrtov.default/ImapMail/box.mailden.net.msf
account5Color=#ef2929
account5URI=/home/stan/.thunderbird/hqbjrtov.default/ImapMail/box.mailden.net/INBOX.msf
account6Color=#ef2929
account6URI=/home/stan/.thunderbird/hqbjrtov.default/Mail/smart mailboxes/Inbox.msf
count=3
```

**Comment by sapiens-sapide** [comment]
`recents.msf` are « smart » folders. I did want `INBOX` folders but, even if I delete these, there are added again by birdtray.

**Comment by gyunaev** [comment]
Strange, I just checked and deletion works correctly. Can you delete ~/.config/ulduzsoft/birdtray.conf and configure it again from scratch?

**Comment by atomGit** [comment]
i can confirm this with Manjaro, KDE - seems the problem may occur only with the smart folders - once one is added and deleted, BT adds it back again - seems you have to delete the config file to get it working again, else it will always indicate new mail (which it too often does regardless of this issue even with no unread mail)

**Comment by gyunaev** [comment]
Should be fixed now. What happened was Birdtray used a map to store the accounts, meaning the order of them changed. So if you added inbox1, inbox2 and smart, and deleted the third, you'd be deleting inbox2 instead of smart. Now the order is remembered as added, please let me know if issue reoccurs.
