### ISSUE TITLE
Birdtray tray icon size

### ISSUE THREAD

**Issue by L-U-T-i** [gyunaev/birdtray#441]
I need to set a bigger panel size (48) in Mate Desktop for visibility issues. All other tray icons are bigger now, but I just can't make Birdtray icon to be resized accordingly. Tried to choose 48x48 icon, doesn't work. It seems Birdtray icon size is set to a fixed value somewhere...

![screenshot](https://user-images.githubusercontent.com/50832205/100204146-cca98080-2f03-11eb-952f-b872307c800a.png)

It would be convenient if the tray icon would be resized together with a tray size. Or, to have an option to set the size manually (within the limits of the tray size of course).

**Comment by gyunaev** [comment]
I suspect it is Mate problem, which doesn't scale app icons at all. Those you have in tray are Mate's own icons, they are part of tray.

Do any other icons from the 3rd party apps (like Slack or Skype) which are not part of Mate Desktop scale up properly?

**Comment by L-U-T-i** [comment]
Other icons as Skype or VLC seem to scale, Skype even too much (as much as I know Mate icons have 1px padding, while Skype icon seem to me like being stretched over the whole tray height; VLC icon seem to be exactly as expected):

![screenshot-2](https://user-images.githubusercontent.com/50832205/100347374-8d536080-2fe5-11eb-8daa-66e7ac53071c.png)

By the way, I've tried to increase the size of ICON_SIZE (from 128 to 192) in settings.h, no difference. Is there anything else I can try to change to get a bigger icon?

**Comment by gyunaev** [comment]
Did you recompile the whole app after changing settings.h AND then replace the icon with 48x48?

**Comment by therob84** [comment]
For Linux Mint 20 Cinnamon 64 Bit it looks like this and seems well scaled to full size:
![grafik](https://user-images.githubusercontent.com/15350793/103924721-ba338100-5116-11eb-87ea-664680d2ece4.png)

side-topic: Can anybody give me a hint where to look for some specific symbols which I can setup in settings if messages are received? Are there any from thunderbird (a mail icon ....)? Cheers.

**Comment by L-U-T-i** [comment]
> Did you recompile the whole app after changing settings.h AND then replace the icon with 48x48?

Sure, there is no settings.h in a compiled version...

**Comment by Mintulix** [comment]
@therob84 
> side-topic: Can anybody give me a hint where to look for some specific symbols which I can setup in settings if messages are received? Are there any from thunderbird (a mail icon ....)? Cheers.

I use these two
[icons.zip](https://github.com/gyunaev/birdtray/files/6123172/icons.zip)
but they are a bit tiny.
