### ISSUE TITLE
[Feature Request] Reset unread emails (ignore) count when showing Thunderbird from tray

### ISSUE THREAD

**Issue by tomas-chrastina** [gyunaev/birdtray#447]
In current version there is setting **When clicking on Birdtray icon to hide Thinderbird, reset the icon by ignoring all currently unread emails**. Which works -> Thank you!

I'd like to have the same option when we click tray icon to **Show** Thunderbird. Context here -> https://github.com/gyunaev/birdtray/issues/377#issuecomment-754957703

Maybe additional checkbox (or radio?) with options **...reset the icon ... when clicking**:
- [ ] hide Thunderbird
- [ ] show Thunderbird

Also maybe also text in tray icon is not resetting correctly?
I can see this even after icon is resetted fine:
![image](https://user-images.githubusercontent.com/14962885/104194514-ba3ac600-5421-11eb-8f98-7dfc0c281257.png)

My current options are:
![image](https://user-images.githubusercontent.com/14962885/104194339-78aa1b00-5421-11eb-8170-5daedd86ba84.png)

Thank you in advance for considering this.

**Comment by Abestanis** [comment]
Please have a look at #452 and tell me if that is what you wanted.

> Also maybe also text in tray icon is not resetting correctly?

This number shows the amount of unread mails that are currently ignored. It's hard bring that across without making the menu entry super long. Do you have a suggestion on how we could improve the wording?

**Comment by tomas-chrastina** [comment]
Provided change/solution looks great => thank you very much for your effort!

> This number shows the amount of unread mails that are currently ignored. It's hard to bring that across without making the menu entry super long. Do you have a suggestion on how we could improve the wording?

I see. I don't know, if you'd like to change spelling, maybe use last instead of now?

But for me personally it would make more sense to change it like this?
    - if there are new mails, icon is changed and number can be displayed on icon. In this case it should be like it is, active and text "Ignore unread mails". Because it is also resetted to this state when I can reset it again.
    - if I pressed ignore, and/or there are no new mails to ignore -> change record to inactive (grayed) and display message (toggle) "Last ignored emails: X".

But now, that i know what it means, can simply ignore it.
