### ISSUE TITLE
Use Dependabot to keep the GithubActions workflows up to date

### ISSUE THREAD

**Issue by Abestanis** [gyunaev/birdtray#450]
@gyunaev What do you think about using [Dependabot](https://dependabot.com/#how-it-works) to keep the actions in the GithubActions workflows up to date. I have seen a couple of other projects use it and it seems like a good idea.

The bot needs to be [enabled in the repository settings](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates#enabling-or-disabling-dependabot-security-updates-for-an-individual-repository). Once enabled, we can add a `dependabot.yml` like [this one](https://github.com/python/cpython/blob/master/.github/dependabot.yml).

**Comment by gyunaev** [comment]
It is enabled for this repo.
