### ISSUE TITLE
Setting UI: blinking speed reversed when transition enabled

### ISSUE THREAD

**Issue by mattuylee** [gyunaev/birdtray#455]
**OS**: Manjaro Linux 20.2.1
**Linux Desktop Manager**: KDE Plasma
**Birdtray version**: 1.9.0
**Thunderbird version**: Not applicable
**Birdtray origin**: From source
**Qt version**: 5.15.2
**Description**
In settings, the blinking speed field is reversed when fade-in/fade-out transition is enabled, but is normal when that disabled.
I found an issue #422 described the same problem which has been closed, so I file this new one.

In my guess, maybe #359 fixed this only for transition disabled case?

**Expected behavior**
Settings UI behaves samely regardless fade-in/fade-out transition enabled or not.

**To Reproduce**

1. Open settings
2. Go to "Advanced" group, check "When blinking, use the fade-in/fade-out transition"
3. Make sure there are unread messages, so that Birdtray will blink the icon
3. Go to "General" group, try to change blinking speed field

**Comment by Abestanis** [comment]
I can confirm that, thank you for reporting.
