### ISSUE TITLE
about language

### ISSUE THREAD

**Issue by fx2013013** [gyunaev/birdtray#456]
how to change the language,Button or add file

**Comment by Abestanis** [comment]
Birdtray used the system language, if there is a translation available for it. There is currently no way from within Birdtray to change the language.
If you are using a Linux operating system such as Ubuntu, there are environment variables which you can change to make Birdtray detect a different system language. language you want to use I can help you to set it up. On Windows that is not possible.

**Comment by fx2013013** [comment]
I use Archlinux, the desktop manager is i3, I have set the system language to Chinese, and other software is also displayed normally

**Comment by gyunaev** [comment]
What does `echo $LANG` say?

**Comment by fx2013013** [comment]
zh_CN.UTF-8

**Comment by Abestanis** [comment]
The Chines translation has only been added very recently in #446 and there is no release which includes it yet. You will need to wait for a new release. Alternatively, you should be able to add these two files to the `translations` directory where Birdtray stores the translations. I don't have access to a computer that runs Archlinux, so unfortunately I can't tell you exactly where that directory is.
[translations_zh_cn.zip](https://github.com/gyunaev/birdtray/files/6026362/translations_zh_cn.zip)

**Comment by fx2013013** [comment]
Okay, I got it, thank you very much
