### ISSUE TITLE
Birdtray with Thunderbird snap

### ISSUE THREAD

**Issue by shmu26** [gyunaev/birdtray#457]
Not sure if this is a bug or a feature, but... 
1 I installed Thunderbird snap.
2 I didn't find a Birdtray snap, so I tried installing it from the Ubuntu repo, and alternatively, from a downloaded .deb. 
3 Either way, Thunderbird apt is considered a prerequisite for Birdtray, so it gets installed along with Birdtray, whether you like it or not. 

I would prefer only one Thunderbird installation -- in my case, the snap, because it gets confusing which instance you launched, and anyways it is bloat to have two.

Indeed, Birdtray works impeccably with TB snap, but I wish it wouldn't force the installation of TB apt. 

Yeah, I tried this way, too:

`sudo dpkg -r --force-depends thunderbird`

And it works, but after a while, you get nags that your system is broken and you have unsatisfied dependencies. I am sure there is a hack to hide that notification, but things should't be so difficult, in an ideal world. :)

**Comment by Abestanis** [comment]
There is no snap version of Birdtray that I'm aware of. We also don't actually maintain the package for Ubuntu, so unfortunately we can't change the dependencies. There is a link at the [Ubuntu package website](https://packages.ubuntu.com/hirsute/birdtray) to report a bug, you could to contact the maintainer that way.

Other then that, there is always the option to build Birdtray from source, of course that means that you don't get automatic updates.

Alternatively, there is a [Flatpak version](https://flathub.org/apps/details/com.ulduzsoft.Birdtray) of both Birdtray and Thunderbird available.

**Comment by shmu26** [comment]
Thanks. I built  1.9.0 from source, and that does the trick. Much less memory usage than the 1.8 version offered in the Ubuntu repo. And it can check for updates at startup, so all's well.

**Comment by ekennedy80** [comment]
> Thanks. I built 1.9.0 from source, and that does the trick. Much less memory usage than the 1.8 version offered in the Ubuntu repo. And it can check for updates at startup, so all's well.

How were you able to get Birdtray to work with the Thunderbird snap?  What command did you use to start Thunderbird?
