### ISSUE TITLE
Tray icon click, only minimizing not hiding TB

### ISSUE THREAD

**Issue by VladimirKadlec** [gyunaev/birdtray#459]
When the systray icon is clicked with the option `Hide/show Thunderbird window when clicing on tray icon` checked, Thunderbird dissapears from the windowmanager's taskbar, even when the option `Hide Thunderbird window when it is minimized"`is **not** checked.

I would like to have an option to minimize (with taskbar) without hiding.

The suggested behaviour is to have something like `Minimize/show Thunderbird window when clicing on tray icon` and to hide on click only if the option `Hide Thunderbird window when it is minimized"`is checked.

The following simple patch solves it for me (X11 only):
```
diff --git a/src/windowtools_x11.cpp b/src/windowtools_x11.cpp
index 3c65b35..fdc5ce6 100644
--- a/src/windowtools_x11.cpp
+++ b/src/windowtools_x11.cpp
@@ -484,7 +484,10 @@ void WindowTools_X11::doHide()
      */
     XIconifyWindow(display, mWinId, screen ); // good for effects too
     XSync(display, False);
-    XWithdrawWindow(display, mWinId, screen );
+
+    if (BirdtrayApp::get()->getSettings()->mHideWhenMinimized) {
+        XWithdrawWindow(display, mWinId, screen );
+    }
 
     // Increase the counter but do not exceed 2
     mHiddenStateCounter++;
```

The string in settings `Hide/show Thunderbird window when clicing on tray icon` is a little bit misleading in this case though (`minimize` not `hide`).

I understand that it would be not that simple as it changes the default behaviour, the text change would mess the translations, etc... Thank you for considering this feature.

**Comment by gyunaev** [comment]
> When the systray icon is clicked with the option Hide/show Thunderbird window when clicing on tray icon checked, Thunderbird dissapears from the windowmanager's taskbar

This is called "hide Thunderbird", so this option works as expected. Note that it is not called "Minimize Thunderbird".

> even when the option Hide Thunderbird window when it is minimized"is not checked.

Because this option applies when you minimize Thunderbird manually.

The proposed patch breaks the existing behavior and for this reason isn't acceptable. A new setting is necessary.
