### ISSUE TITLE
can not select a mail path

### ISSUE THREAD

**Issue by wangwg1** [gyunaev/birdtray#464]
can not select a mail path

![image](https://user-images.githubusercontent.com/20198809/113087747-dd9e3180-9216-11eb-82b5-1a56a642d02e.png)

**Comment by wangwg1** [comment]
<context>
    <name>MailAccountDialog</name>
    <message>
        <source>Choose the Thunderbird profiles path</source>
        <translation>选择Thunderbird数据目录</translation>
    </message>
    <message>
        <source>No folder selected</source>
        <translation>未选择目录</translation>
    </message>
    <message>
        <source>No mail folder was selected to monitor.
Do you want to continue?</source>
        <translatorcomment>checkTranslation ignore: punctuation_end_differ</translatorcomment>
        <translation>未选择任何要监听的邮件目录。
是否继续？</translation>

**Comment by Abestanis** [comment]
Please fill out the issue template. We need at least the Birdtray version, Qt version and Operating system, maybe any custom style that is used.
There should be checkboxes in front of these, maybe they are just not visible with the style you are using.
![Checkboxes in the dialog](https://user-images.githubusercontent.com/6966049/113104074-62ca1c00-9200-11eb-8450-aa9a7dbefae1.png)
It is not enough to select the line, the checkbox must be ticked.

**Comment by wangwg1** [comment]
no, have not checkbox , i modified the program, It's worked: my operating system is deepin 20
![image](https://user-images.githubusercontent.com/20198809/113124879-93ce3f00-9248-11eb-9e74-d1b9105a7ba4.png)
![image](https://user-images.githubusercontent.com/20198809/113125098-d1cb6300-9248-11eb-94d5-6d49ca6a2ebe.png)

**Comment by wangwg1** [comment]
checked --> selected ，can work

**Comment by wangwg1** [comment]
> Please fill out the issue template. We need at least the Birdtray version, Qt version and Operating system, maybe any custom style that is used.
> There should be checkboxes in front of these, maybe they are just not visible with the style you are using.
> ![Checkboxes in the dialog](https://user-images.githubusercontent.com/6966049/113104074-62ca1c00-9200-11eb-8450-aa9a7dbefae1.png)
> It is not enough to select the line, the checkbox must be ticked.

i close issue or pull request ？

**Comment by Abestanis** [comment]
> checked --> selected ，can work

This would be confusing for all platforms where the checkboxes are visible. I still believe this is just a styling bug in Qt/Deepin, probably related to [this one](https://github.com/linuxdeepin/developer-center/issues/1716). Could you try clicking on the space where the checkbox should be and see if it appears in its checked state?

> i close issue or pull request?

I appreciate the offer, but I don't feel like this will benefit the majority of users. @gyunaev what do you think?
For now it looks like it's an OS bug, for which you found a workaround, so I would say close the issue.

If anybody else encounters this problem, there is always the advanced selection dialog. See [this comment](https://github.com/gyunaev/birdtray/issues/393#issuecomment-703170164) on a guide on how to use it.

**Comment by wangwg1** [comment]
ok,this will just a bug in deepin

**Comment by Abestanis** [comment]
Ok, I'm closing this for now, thank you for reporting.
