### ISSUE TITLE
PR #463: Build time is 25 days+

### ISSUE THREAD

**Issue by MichaelPStimpson** [gyunaev/birdtray#471]
On pull request #463 you've got some build script that's been running for 25 days and the average build time for that action appears to be 1 minute. If that's intentional, I apologize!

**Screenshots**

![image](https://user-images.githubusercontent.com/10071798/115896176-c111a580-a420-11eb-9ba9-7ca81045832e.png)

**Comment by Abestanis** [comment]
Looks like it's just a visual bug on GitHub. The job does not come up if you search for running actions in the actions tab. Also, there is no option to cancel the job. I will re-run it and we'll see if that fixes it.

**Comment by Abestanis** [comment]
Yeah, a re-run fixed the issue. I don't think it was actually running for that long, I just think the success message got lost and was not saved by GitHub. Anyways, thanks for reporting.
