### ISSUE TITLE
Left click the icon opens Birdtray again instead of restoring/hiding Thunderbird

### ISSUE THREAD

**Issue by PoisonFrog** [gyunaev/birdtray#472]
When I left click the birdtray icon a new birdtray icon shows up, but if I have birdtray settings open it minimizes and restores the settings instead of opening a new instance. I installed birdtray via flatpak.

Edit: It may be a Gnome 40 bug because it is working like it should in Xfce.

**Comment by gyunaev** [comment]
It is Gnome-specific "feature".
