### ISSUE TITLE
Manual launch of Thunderbird messes Birdtray's tracking of its visible/hidden state

### ISSUE THREAD

**Issue by AdrienMatricon** [gyunaev/birdtray#473]
**OS**: Linux Manjaro 21.0
**Linux Desktop Manager**:  XFCE
**Birdtray version**: 1.9.0
**Thunderbird version**: 78.10.1 
**Birdtray origin**: yay -S birdtray

**To Reproduce**
1. Launch Birdtray
2. Hide Thunderbird
3. Launch Thunderbird from the application menu

(why this happens in my case: Birdtray is launched & hidden on startup, then if Thunderbird was still open when I last logged out, the saved session is restored and Thunderbird is launched again)

**Description**
- If Thunderbird is visible, launching it again from the application menu does nothing, which is good
- If Thunderbird is hidden, launching it again makes it visible, but Birdtray still thinks it's hidden so clicking on the tray icon or minimizing the window doesn't hide it. Closing Thunderbird causes Birdtray to relaunch Thunderbird, but the problem persists as it still thinks Thunderbird is hidden

**Comment by gyunaev** [comment]
This happens because birdtray remembers Thunderbird window has been hidden, but starting Thunderbird (again) manually shows it. This is why it gets confused. 

Unfortunately fixing this introduces other issues, and being a relatively minor problem I'd rather leave it as is.
