### ISSUE TITLE
Opening Thunderbird via notification doesn't work

### ISSUE THREAD

**Issue by RoinujNosde** [gyunaev/birdtray#475]
**OS**:  Linux Mint 20.1 Cinnamon
**Linux Desktop Manager**:  Cinnamon 4.8.6
**Birdtray version**:  1.9.0
**Thunderbird version**:  78.8.1 (64-bit)
**Birdtray origin**:  From source
**Qt version**:  5.12.8 

**Description**

When Thunderbird is hidden, clicking on a new email notification has no effect. It stays hidden.

**Expected behavior**

Thunderbird should open when clicking on a notification.

**To Reproduce**

1.  Open Birdtray and Thunderbird.
2.  Hide Thunderbird.
3. Receive an email (and a Thunderbird notification).
4. Click on the notification.

**Additional context**

Log: https://paste.ubuntu.com/p/fskNTNSz4C/

**Comment by gyunaev** [comment]
Unfortunately Birdtray has no means to know that you've clicked on Thunderbird-shown email notification. Nothing I can do.
