### ISSUE TITLE
MSF files greyed out

### ISSUE THREAD

**Issue by shmu26** [gyunaev/birdtray#476]
I am running  Birdtray version 1.9.0 compiled at Feb 22 2021 22:08:37 using Qt 5.12.8.
And Thunderbird 78.8.1 (64-bit)
On Ubuntu 21.04 with Wayland 
When I browse into the IMAP folder from the Birdtray settings, I see that all the MSF files are greyed out and not selectable. 
![2021-06-19_22-35](https://user-images.githubusercontent.com/13636596/122653653-ad4b9c80-d14e-11eb-99e9-36457faf632a.png)

**Comment by gyunaev** [comment]
This is because it asks you (in the dialog title) to choose the profile PATH (i.e. directory), not the individual files. You don't need to select any files. Just click "open" in this window.
