### ISSUE TITLE
Is there a command to show Thunderbird?

### ISSUE THREAD

**Issue by PoisonFrog** [gyunaev/birdtray#480]
I'm using Linux and I want to bind a command that shows Thunderbird to a keyboard shortcut. The command to open Thunderbird opens a new instance of it. Is it possible?

**Comment by sschwartz96** [comment]
I am using birdtray 1.9.0:

```
-t, --toggle-tb        Toggle the Thunderbird window.
-s, --show-tb          Show the Thunderbird window.
-H, --hide-tb          Hide the Thunderbird window.
```

These commands work as expected, I do have Thunderbird set to open with birdtray.

**Comment by PoisonFrog** [comment]
> I am using birdtray 1.9.0:
> 
> ```
> -t, --toggle-tb        Toggle the Thunderbird window.
> -s, --show-tb          Show the Thunderbird window.
> -H, --hide-tb          Hide the Thunderbird window.
> ```
> 
> These commands work as expected, I do have Thunderbird set to open with birdtray.

Thanks! I removed the flatpak version (because I could not figure out how to do it using the flatpak version) and compiled from source and these commands are working. Fixed my issue.

**Comment by tom-gora** [comment]
If anyone using flatpak was looking for a solution
` flatpak run com.ulduzsoft.Birdtray --toggle-tb`
works perfectly fine.
