### ISSUE TITLE
Showing Thunderbird via birdtray results in temporary white area

### ISSUE THREAD

**Issue by fishstik** [gyunaev/birdtray#487]
**OS**: Windows 10 21H1 64-bit 19043.1165
**Birdtray version**: 1.9.0
**Thunderbird version**: 91.2.0 (32-bit)
**Birdtray origin**: [From installer](https://github.com/gyunaev/birdtray/releases/tag/v1.9.0)

**Description**
When clicking the tray icon or right-click > `Show Thunderbird`, Thunderbird appears with large white blank areas covering the window. 

**Expected behavior**
Thunderbird window should appear normally, with no blank white areas.

**To Reproduce**
1. Start Thunderbird
2. Start Birdtray
3. Minimize Thunderbird by clicking the minimize window button or <kbd>Alt</kbd>+<kbd>Space</kbd>, <kbd>n</kbd>
4. Show Thunderbird by clicking Birdtray or right-clicking Birdtray and selecting `Show Thunderbird`

**Screenshots**
![20211013-140243](https://user-images.githubusercontent.com/4278123/137188243-42d9a84d-09cc-43f7-b29f-95cb07e472d2.png)
Birdtray Hiding settings:
![image](https://user-images.githubusercontent.com/4278123/137187337-bbade783-8481-4f23-af15-5da1157edaba.png)

**Additional context**
- Moving the cursor over it removes the whitespace.
- Clicking outside the window or <kbd>Alt</kbd>+<kbd>Tab</kbd>bing away removes the whitespace.
- It is intermittent. Sometimes the whitespace will appear and then immediately disappear.
- It only occurs if the Thunderbird window was minimized via the window. It does not occur if it was hidden via Birdtray.
- The size and shape of the whitespace is constant with different window sizes. If the window size is smaller than the visible area shown in the screenshot, the whitespace can't be seen.

**Comment by Abestanis** [comment]
Hey @fishstik, sorry for the long wait, thanks for the report.
I was able to see the white spaces on Windows 11 as well, but they disappeared pretty much immediately after restoring the window. I have written a fix for that in #527, but I'm not sure if that will resolve your issue as well.

Could you please try those changes? You can either compile Birdtray from that pull request, or use the installer which includes the changes from [here](https://github.com/Abestanis/birdtray/suites/9298772616/artifacts/436296631).

**Comment by fishstik** [comment]
@Abestanis thanks for following up. Can confirm with changes from #527 that the white spaces disappear, though the flash is still quite noticeable with a dark theme applied.

**Comment by Abestanis** [comment]
Yeah, I see the flash with the dark theme as well, but I also see it without Birdtray when just minimizing and restoring the Thunderbird window.
So it looks like that's just a Thunderbird issue and I don't think we can do much here, other than maybe report a bug report to their bugtracker and hope that they can fix it.
