### ISSUE TITLE
Thunderbird does not hide in the tray occasionally

### ISSUE THREAD

**Issue by raven-kg** [gyunaev/birdtray#488]
**OS**: CentOS 8
**Linux Desktop Manager**: KDE 5 (X11-session)
**Birdtray version**: 1.9.0
**Thunderbird version**: 91.2.1
**Birdtray origin**: rpm
**Qt version**: 5.15.2

**Description**
I'm upgraded thunderbird and birdtray to the latest versions, after that closing the Thunderbird window causes it to close and then restart, instead of hiding in the tray. After restarting birdtray the Thunderbird window behavior returns to normal, but not for long. It doesn't happen all the time, but I face it quite often during the day and it's annoying.

**Expected behavior**
Thunderbird minimizes to tray

**To Reproduce**

1. 
2. 

**Screenshots**

**Additional context**

**Comment by major-mayer** [comment]
I have more or less the same problem.
When I close Thunderbird, Birdtray restarts it, but does not minimize it to tray.
My Thunderbird version is 91.3.1 and i am using Gnome - Wayland.
My Thunderbird is running using native wayland (MOZ_ENABLE_WAYLAND=1), maybe this is the reason.

**Comment by neurodiverseEsoteric** [comment]
Same issue on Manjaro Pahvlo KDE

**Comment by gyunaev** [comment]
Can you please open the code repository page, press Ctrl-F and search for the word "wayland"?

**Comment by raven-kg** [comment]
@gyunaev
>>> Linux Desktop Manager: KDE 5 (X11-session)

**Comment by gyunaev** [comment]
Your bug report is essentially "something sometime doesn't work". What exactly you expect me to fix?

**Comment by raven-kg** [comment]
Well, at least on my system, the Thunderbird window is minimized to the tray regardless of whether I press the Minimize or Close button. And this is what I expect from Birdtray. But occasionally (about 3-5 times a day) Birdtray loses control of the Thunderbird window (when I press Close button) and the window is restored and no longer hides in the tray. If I minimize it at this point, it minimizes to the taskbar instead of the tray.

**Comment by gyunaev** [comment]
Most likely you're closing it and Birdtray restarts it. If you had multiple windows opened, this gonna break up the closing logic. Do not use close button unless you plan to close Birdtray.

**Comment by raven-kg** [comment]
Ok, looks like I'll have to work on my habits) 
Thanks for the clarification!
