### ISSUE TITLE
check hostname/more complex pattern for "TB window name pattern" field

### ISSUE THREAD

**Issue by 2019-05-10** [gyunaev/birdtray#489]
I've running a local TB and a remote one via X2Go.
The local one's window name ends with
"- Mozilla Thunderbird"
the remote's with
"- Mozilla Thunderbird <@hostname>" (where "hostname" is the remote host)
Issues with that:
a) I need to make sure to start the local one first so that Birdtray shows counts etc
b) I can hide/show only one the two TBirds, the remote one mostly just sits in the taskbar.

Changing the pattern to 
"- Mozilla Thunderbird$"
to match the local one's name did not work.

So, it would be great if Birdtray would allow either a more complex pattern to match the window name or would also allow to match more than one property (hostname in my case).

I am well aware that for remote only hide/show would work with that, but that's all I need.

**Comment by gyunaev** [comment]
Can you just change the pattern to "- Mozilla Thunderbird <@hostname>" (where "hostname" is the remote host) - I assume the hostname is the same/rarely changes? It checks it using "endsWith", so the string must end with the specified window name.
