### ISSUE TITLE
JSON attribute 59 in sqlite was 58 in my case

### ISSUE THREAD

**Issue by bxabi** [gyunaev/birdtray#49]
Hi. Thanks for finally solving the tray issue! :)

I am using the sqlite option, because the mork file didn't really work for me (didn't detect changes on one account, and was showing 2-3 unread when everything was read).
As I see the mork file type is deprecated by mozilla, and it's extremely hard to understand them.

So I looked at the sqlite database (global-messages-db.sqlite), and it was easy to get how that works.
Browsing my email database I realized 2 problems:
- I  was getting thousands of unread emails, because in my database the "read" attribute had the ID 58, not 59.
- Even if I filtered for 58, I still got 17 emails which appeared unread, but in Thunderbird they were read.

Both problems were solved by deleting my database and let Thunderbird rebuild it. I also have the ID 59 now, and no read emails showing up as unread. So old databases can have such "corruption" issues.

Maybe it is useful to tell people in the docs that if they get wrong results using the sqlite db, backup and remove their db and let Thunderbird recreate it.

**Comment by gyunaev** [comment]
Added.
