### ISSUE TITLE
Automatic inclusion of (new) subfolders if the parent folder is watched

### ISSUE THREAD

**Issue by malnvenshorn** [gyunaev/birdtray#490]
Automatic inclusion of (new) subfolders if the parent folder is watched. At the moment you have to reconfigure the app every time your folder tree changes. 

The use case is pretty simple. My mail provider automatically creates a subfolder if I receive an email at `me+topic@mail.org`. In this case a folder named `topic` will be created (if it doesn't exist) and the mail will be moved into this folder.

**Comment by gyunaev** [comment]
Too specific use case, sorry. You're welcome to submit a patch.
