### ISSUE TITLE
Add "Get Messages" item to system tray icon's context menu

### ISSUE THREAD

**Issue by vedgy** [gyunaev/birdtray#491]
**Description**
The new context menu item should do exactly what the corresponding Thunderbird toolbar button, or rather its submenu item *Get All New Messages*, does: request new messages from all inbox folders. Alternatively, the Birdtray's context menu item could refresh only the monitored folders, if that's easier to implement.

**Example**
I often check new emails upon resuming from Suspend or Hibernate. Doing this requires two or even three steps right now: show Thunderbird's main window; possibly select the unified Inbox folder; click the *Get Messages* toolbar button. Having this action in Birdtray's context menu would save some time.

**Comment by gyunaev** [comment]
Birdtray cannot "force" Thunderbird to check for emails.
