### ISSUE TITLE
Split birdtray configuration file

### ISSUE THREAD

**Issue by jmichalak9** [gyunaev/birdtray#493]
**Description**

Currently birdtray uses `$HOME/.config/birdtray-config.json` as a configuration file. However, in this file there are:
- accounts (a list of RSS feeds and mail directories in thunderbird profiles)
- birdtray config values like notification font, etc.

If this config file was splitted, it would be handy to easily share the birdtray config without revealing which feeds you subscribe too.
**Example**

**Comment by gyunaev** [comment]
Why would you need to share Birdtray config? It has many things specific to a single PC - for example the Thunderbird profile path, which is going to be unique among different users.

**Comment by jmichalak9** [comment]
I use multiple laptops, so it would be easier to sync this. Just for the same reason people have `.vimrc` in GitHub repos.

**Comment by gyunaev** [comment]
Then I don't understand what issue you have "revealing which feeds you've subscripted to" if those are all your laptops. In any way, doesn't seem to worth implementing.

**Comment by jmichalak9** [comment]
I just asked politely, you don't have to be so edgy. Thanks for your huge help.
