### ISSUE TITLE
Monochrome Icon for "no unread mails"

### ISSUE THREAD

**Issue by riidom** [gyunaev/birdtray#497]
I like to have a monochrome icon for when there are no unread mails, and the default TB icon with number on top for notification.
Since there was no good icon, I made one myself, for anyone who likes it, I attached it. It is 64x64px, but probably be displayed way smaller (for example, mine is ~40% size when it sits in my tray).

Since it is based on the original TB icon (ofc), but simplified for the small size, I'm not sure if I can pick a license myself, but if so, it goes by CC-0.

![tb_bw_vector](https://user-images.githubusercontent.com/437109/147447543-6a58e0c1-62e7-4e9b-b66b-b04b412a59ad.png)

(github doesn't let me upload the .svg unzipped): [birdtray_nomail.zip](https://github.com/gyunaev/birdtray/files/7778981/birdtray_nomail.zip)

Edit:

further simplified, and if this can go into the project, I'd be happy about that, just not sure how to integrate and make a PR for this, so I hope this way is good enough until someone proficent takes care.

**Comment by RasheedAZ** [comment]
Thanks for this. The normal colour icon looks a bit out of place in dark mode as all the other app indicators are white.
