### ISSUE TITLE
Show incoming mails

### ISSUE THREAD

**Issue by sunta3iouxos** [gyunaev/birdtray#501]
Thank you for this extension.
The following is a feature request and probable a question of function that I might not be aware.
Before some updates, I could keep track of the arrival of newer emails by clicking the thunderbird notification icon. This now is not possible via thunderbird (well, as far as I know). Is it possible to implement such a feature?
Thank you

**Description**

**Example**

**Comment by gyunaev** [comment]
Not possible, we do not parse the actual emails, only the metadata.
