### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by lockie** [gyunaev/birdtray#502]
Hello. Is there a way to disable annoying pop-up notifications, but still keep the unread message count on systray icon?

**Comment by Abestanis** [comment]
Yes, the pop-up notifications are generated by Thunderbird, [you can disable it in their settings](https://support.mozilla.org/bm/questions/1330945#:~:text=At%20the%20top%20right%20of,Uncheck%20'Play%20a%20sound'.).

**Comment by lockie** [comment]
Oh boy, I should be reading docs more attentively :sweat_smile: Thank you @Abestanis !
