### ISSUE TITLE
Enhance UI : using different tray icons by default

### ISSUE THREAD

**Issue by Hyphaed** [gyunaev/birdtray#503]
Hi gyunaev

First of all congratulations for the great work you've done

Adding by default 2 different icons for unread and inbox non unread, improves quite a lot the experience, when being something easy to achieve

default inbox all read icon proposal
"Inbox"
https://fonts.google.com/icons?selected=Material+Icons&icon.query=mail
density 1x : size : 24dp ; white  (maybe would be needed then an option inside preferences to set white and dark theme), PNG

default unread icon proposal
"Mark As Unread"
https://fonts.google.com/icons?selected=Material+Icons&icon.query=unread

**Comment by gyunaev** [comment]
This is something easy to do for anyone, so I'm unsure we're adding much value here.
