### ISSUE TITLE
Birdtray doesn't recognize opened Thunderbird

### ISSUE THREAD

**Issue by lakomyt** [gyunaev/birdtray#504]
Thunderbird 91.8.1 (64-bit)
Manjaro 21.2.6 Gnome Wayland
Birdtray version 1.9.0 compiled yestarday using Qt 5.15.3

I have a second pc with manjaro, same version, thunderbird also the same version, compiled using Qt 5.15.2 and there birdtray works

When I launch birdtray it starts thunderbird, but then shows, that thunderbird is not running.

**Comment by lakomyt** [comment]
`wmctrl -l` doesn't show thunderbird, `xprop WM_NAME` doesn't let me click thunderbird window

**Comment by gyunaev** [comment]
Did you look at Readme, notably the Troubleshooting section?

**Comment by lakomyt** [comment]
oh, now I've read troubleshooting
I've buillt birdtray from source code and everything works on wayland on my second pc
