### ISSUE TITLE
Emails automatically moved to the "Junk" folder display a new mail alert even if only "Inbox" is monitored 

### ISSUE THREAD

**Issue by electrotype** [gyunaev/birdtray#508]
I have multiple accounts in Thunderbird, all configured to use "Local Folders". When a new email comes in, it is available in "Local Folders/Inbox". When an email is seen as junk, it is automatically moved to "Local Folders/Junk".

I only want the emails in the "Inbox" folder to trigger Birdtray's "new mail" alert. But, often, Birdtray displays such "new mail" alert even when the email is automatically moved to the "Junk" folder!

In Birdtray, in the "Monitoring" section, I have _one_ entry only: "Local Folders [Inbox]".

I though maybe Birdtray is too quick and "sees" the new email in the Inbox folder before Thunderbird moves it to the Junk folder... So I tried increasing the "advanced/watchfiletimeout" config to 2000. I'm not sure if this config is actually related to my issue, but anyway the modification didn't help.

Am I missing something? How can I prevent emails moved to the Junk folder to trigger a "new email" alert?

Thanks in advance.

--------------------
Birdtray 1.9.0, installed using Pamac.

Operating System: Manjaro Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.4
Kernel Version: 5.15.48-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7300U CPU @ 2.60GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by gyunaev** [comment]
> I though maybe Birdtray is too quick and "sees" the new email in the Inbox folder before Thunderbird moves it to the Junk folder

This is correct. I assume a delay+recheck would need to be added to handle your case. Or you can create a "real inbox" to monitor, and add the rule to move the non-junk files into this inbox, would work too.

**Comment by Abestanis** [comment]
I feel like `advanced/watchfiletimeout` should have done the trick. After we detect that one of the mail account database files was changed we wait for that configured time in milliseconds before we open the database file and parse the unread counter. This then triggers the tray icon to change and calls the `advanced/runProcessOnChange` command from the settings, which I think is what you mean by `Birdtray's "new mail" alert`.
This should give Thunderbird enough time to move the email out of the inbox into the spam folder.

@electrotype did you make sure to restart Birdtray after you edited the configuration file? Also, just to make sure you are editing the right file, try changing something else temporarily and verify that you can see the change in the Birdtray settings after you restarted Birdtray.
Furthermore, did you try increasing the `advanced/watchfiletimeout` value even more? Maybe `2000` (`2` seconds) just wasn't enough time?

If changing the `advanced/watchfiletimeout` solves your problem, I think we should expose it in the `Advanced` tab in the settings.

**Comment by electrotype** [comment]
I'm sorry, I'm not using Birdtray anymore. If it was an issue I could easily reproduce locally I would still run tests in order to help you, but this is not the case, it was random. Good luck!

**Comment by Abestanis** [comment]
Hey @electrotype, no worries, thank you for responding.
I will expose the setting in the settings dialog and then close this issue.
If anybody has a similar issue, they should open a new issue about it.
