### ISSUE TITLE
Unread email count with Thunderbird 102.0.3 not displayed.

### ISSUE THREAD

**Issue by g1bwt** [gyunaev/birdtray#511]
**OS**: Kubuntu 22.04 64Bit
**Linux Desktop Manager**: KDE Plasma 5.24.4, Qt version 5.15.3 X11 window
**Birdtray version**: Birdtray version 1.9.0 compiled at Jul 28 2022 20:18:22 using Qt 5.15.3.
**Thunderbird version**: 102.0.3 downloaded from Thunderbird.net
**Birdtray origin**: Downloaded github.com/gyunaev source, compiled with all defaults and ran from the build directory.
**Qt version**:Qt version 5.15.3 

**Description**
After creating new Thunderbird profile and then copying all of the data from the original 91 version into the new profile, Thunderbird no longer picks up the unread email count when setup in the Monitoring tab. 

**Expected behavior**
Unread inbox email counts are displayed on the birdtray icon.

**To Reproduce**

1. Download and compile the source.
2. Run the source and add the INBOX.msf file into the Accounts to monitor box.
3. Mark email unread in Thunderbird inbox or wait until new unread email is retrieved via IMAP.
4. No unread email count is displayed.

**Screenshots**

**Additional context**
I have checked that the right Thunderbird profile is being used to monitor the inbox and have searched and found nothing similar to this problem.

**Comment by NoXPhasma** [comment]
I have the same issue with Thunderbird 102.2.0.

**Comment by ramon501** [comment]
Works fine for me with thunderbird 102.2.0-1

**Comment by NoXPhasma** [comment]
I've already tried to remove all accounts and re-add them, birdtray still does not see any unread emails.

**Comment by ramon501** [comment]
I had to check most options in the hiding tab, apparently thunderbird needs to be running in the background to work

**Comment by g1bwt** [comment]
Running thunderbird 102.2.0 direct from Mozilla/Thunderbird. It's self updated several times.
Have set it all up using a completely new profile, nothing copied over from old profiles, all setup from scratch, new .msf files created from imap provider and ran birdtray from the downloaded source build that I made earlier. Still nothing in the birdtray icon.

**Comment by indigoxela** [comment]
I can confirm that after upgrading to Thunderbird 102.x no unread mails show up anymore.
I can also confirm that #512 fixes that. After compiling the latest dev, unread mails show up again.

@gyunaev many thanks for the fix (and all your work on Birdtray)! Maybe this change is important enough to warrant a new release?
