### ISSUE TITLE
Hide/Show VS Minimize/Unminimize

### ISSUE THREAD

**Issue by Anard** [gyunaev/birdtray#513]
**Description**
The Show/Hide feature of Birdtray is cool but don't match my needs... As when hidden, thunderbird disappears from  docks. I would prefer a Minimize/Unminimize feature.
Maybe a choice between these 2 behaviours in birdtray's settings panel should be a nice solution.

**System configuration**
Gentoo 2.8 / Xfce 4.16

**Comment by gyunaev** [comment]
You can do minimise/unminimise via Thunderbird icons itself. Birdtray is not for managing Thunderbird from a system tray, it provides functionality which Thunderbird doesn't provide.
