### ISSUE TITLE
Birdtray + Linux Mint + Thunderbird Flatpak

### ISSUE THREAD

**Issue by premier69** [gyunaev/birdtray#514]
Hello

for years now I've been using thunderbird 91 because it's the latest for linux mint and i just found verison 102 of thunderbird flatpak so i installed it. is it possible to get birdtray to work with flatpak version of thunderbird?

**Comment by Abestanis** [comment]
Yes, if you change the Thunderbird start command in the Advanced Settings as described here: https://github.com/gyunaev/birdtray/issues/389#issuecomment-658562057

If I remember correctly, there was also a Flatpak version of Birdtray which worked out of the box with the Flatpak Thunderbird.
