### ISSUE TITLE
Ubuntu 22.04 LTS Gnome Birdtray does not connect to Thunderbird

### ISSUE THREAD

**Issue by Timu57** [gyunaev/birdtray#515]
**OS**: Ubuntu 22.04 LTS
**Linux Desktop Manager**: Gnome
**Birdtray version**: 1.9.0+ds
**Thunderbird version**: 102.3.1 (64-Bit) (From apt not Snap)
**Birdtray origin**: apt
**Qt version**: _NA_ 

**Description**

It seems like birdtray does not connect to Thunderbird. I already looked into the closed issues and figured out that the source of the problem is the name schema in the advanced settings. I already tried to get the schema with `xprop` but that didn't give me a result. Wayland seems to not support that anymore due to security concerns. So I tried out type in the following things but nothing seems to work. "- Mozilla Thunderbird" " - Mozilla Thunderbird" "Mozilla Thunderbird" " Mozilla Thunderbird" "Posteingang - Mozilla Thunderbird" "thunderbird"

**Expected behavior**

Birdtray starts but has a red X and does not recognize that Thunderbird is running. On startup it opens Thunderbird but that's it.

**To Reproduce**

1. Fresh install of Ubuntu 22.04 LTS
2. Install of Birdtray with `sudo apt install birdtray`

**Screenshots**

**Additional context**

**Comment by Timu57** [comment]
For everyone facing the same Problem:

Just do as described in this link to disable Wayland https://askubuntu.com/questions/1273403/unable-to-share-entire-screen


1. Edit /etc/gdm3/custom.conf
2. Uncomment #WaylandEnable=false
3. sudo dpkg-reconfigure gdm3
4. ctrl + alt + backspace or just reboot


I disabled Wayland because Discord was unable to share the screen. As a side effect birdtray started working correctly.

PS: I have "- Mozilla Thunderbird" as name schema (without parentheses)

**Comment by gyunaev** [comment]
Issue #426
