### ISSUE TITLE
Birdtray does not count the messages under Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ksHamburg** [gyunaev/birdtray#516]
I recently installed Ubuntu 22.04 LTS alongside with thunderbird and birdtray. I did set up birdtray to monitor all email accounts that are managed by thunderbird (all folders of every account) and activated the "Show unread count" option. However no number of unread messages is displayed in the tray icon.
I tried to "repair" the respective email folders within thunderbird, without any success.
Is there something else I could try?

**Comment by bmcdougald** [comment]
Same problem here using Elementary OS 7 (Horus) which is based off of 22.04.

**Comment by alphaonex86** [comment]
Same problem with debian 12

**Comment by gyunaev** [comment]
Build from the source.
