### ISSUE TITLE
Cannot locate profile in SNAP install

### ISSUE THREAD

**Issue by tspeidel** [gyunaev/birdtray#519]
In Pop!_OS 22.04 LTS (Ubuntu), birdtray cannot locate the profile of a SNAP install of thunderbird (SNAP is now the default thunderbird installation). I successfully pointed birdtray to the SNAP profile location (`/home/username/.var/app/org.mozilla.Thunderbird/.thunderbird/`) and it sees my IMAP folders:

![image](https://user-images.githubusercontent.com/6731198/198842517-36bede30-a8af-449c-b742-27f7e2b2768c.png)

However, after clicking OK, birdtray keeps complaining that it cannot find the profile:

![image](https://user-images.githubusercontent.com/6731198/198842464-d0632310-1a9e-4462-b9fd-e895c71bd168.png)

Is birdtray still trying to look for the profile in the (old) default profile folder `/home/username/.thunderbird/profilename` ?

**Comment by Abestanis** [comment]
The `Profile Missing` dialog is not generated by Birdtray, it is generated by Thunderbird itself. Looks like Thunderbird is having problems accessing your profile, you can find some suggested solutions [here](https://support.mozilla.org/en-US/questions/1229544).

To clarify, this is not a problem with Birdtray, but with your Thunderbird configuration.
