### ISSUE TITLE
Click on tray icon no longer minimizes/maximizes Thunderbird

### ISSUE THREAD

**Issue by zoof** [gyunaev/birdtray#53]
Updated to current master and `birdtray` no longer minimizes or maximizes Thunderbird when clicking on the tray icon.

**Comment by gyunaev** [comment]
What is the status of "Hide/show Thunderbird when clicking on tray icon" setting?

**Comment by zoof** [comment]
Ugh -- yes, it was unchecked.  Is this a newly available setting?

**Comment by gyunaev** [comment]
It was broken before.
