### ISSUE TITLE
Any timeline, plan for a new tagged release.

### ISSUE THREAD

**Issue by ladar** [gyunaev/birdtray#532]
Looks like a lot has changed since 1.9.0 was tagged in Oct 2020. Is there a reason for no tagged releases since?

**Comment by david-geiger** [comment]
hi,

I agree, please deal with a new release.

Thanks in advance!

**Comment by ladar** [comment]
@gyunaev or @Abestanis ... can you make this happen?

**Comment by Abestanis** [comment]
I can do it if you are ok with it @gyunaev

**Comment by keosion** [comment]
@gyunaev or @Abestanis, please provide a new release, it will fix Birdtray for so many people

**Comment by Abestanis** [comment]
I can not create a release, I'm just a contributor, sorry.

**Comment by gyunaev** [comment]
I've made a source release - feel free to add Windows builds there please :)

**Comment by Abestanis** [comment]
@gyunaev can you recreate the git tag with a `v` in front, so it becomes `v1.11`? Then our CI will automatically create the windows installer and it will be picked up as a new version by the updater checker for Windows users.

**Comment by Abestanis** [comment]
Actually, it has to be `v1.11.0`.

**Comment by gyunaev** [comment]
done.

**Comment by Abestanis** [comment]
Looks like the job to create the installer failed, I'm looking into it.

**Comment by ladar** [comment]
Looks like you got it working, and the artifacts for the new tag are liive, so I'll close this issue.
