### ISSUE TITLE
Need help installing and running Birdtray

### ISSUE THREAD

**Issue by CamperJim** [gyunaev/birdtray#535]
This morning, I attempted to install Birdtray to use as a Thunderbird replacement.  Thunderbird was, for some reason, not available in the Pop_Shop.  My computer is a System76! Thelio desktop running the latest version of Pop_Os! as shown by the following screenshots:
recent:///f88e5d43a871e20035bbbd4663b45528
recent:///b93e8ade8cf8c54c0ec939d963b45528

I would like help and or guidance in getting either Birdtray or Thunderbird working on this computer.  Thunderbird had been working as it should up until about last month.  Not sure if there was a software update/upgrade on Thunderbird or on the OS of the computer that has rendered Thunderbird no longer compatible with this version of Linux.
Thank you,

**Comment by gyunaev** [comment]
This is for issue tracking in Birdtray. We  do not provide support services, please ask a local IT company.
