### ISSUE TITLE
Unicode support (in folders names)

### ISSUE THREAD

**Issue by ScreamT5** [gyunaev/birdtray#54]
I am from Russia, so many of my folders are named in Russian, and Birdtray in the settings (Accounts to monitor section) shows their names like "&BCMENAQwBDsENQQ9BD0ESwQ1-" or "&BCcENQRABD0EPgQyBDgEOgQ4-"

**Comment by gyunaev** [comment]
Are you using Mork parser?

**Comment by ScreamT5** [comment]
I use "global search database".

**Comment by y-salnikov** [comment]
Same thing with Mork index files. Problem is that file names in thunderbird profile is like &BCMENAQwBDsENQQ9BD0ESwQ1- for non-latin folder names.

**Comment by ScreamT5** [comment]
Yes (you are right), but anyway it isn't a random char sequence (I guess), so it can be translated into real human words.

> Same thing with Mork index files. Problem is that file names in thunderbird profile is like &BCMENAQwBDsENQQ9BD0ESwQ1- for non-latin folder names.

**Comment by y-salnikov** [comment]
Its IMAP UTF7 a.k.a RFC2060

**Comment by gyunaev** [comment]
All, can you please try 116c855?

**Comment by ScreamT5** [comment]
Great! It works. Thanks!

**Comment by y-salnikov** [comment]
Multiple files selection in open dialog would be nice, because you can't see real file names it would  be simpler to add all files, then remove unneeded.

**Comment by y-salnikov** [comment]
I don't know, maybe use some separator, like semicolon.
As for now process of add account look like that:
1) add -> browse -> choose 1 unreadable file -> open -> ok
2) now i can see what file it was.
3) repeat
Problem is that i can't distinguish one unreadable file from another and don't know, am i already add it or not? It's not critical, i just can count files.
![_2019-01-27_13-05-04](https://user-images.githubusercontent.com/5237022/51798982-dcd37480-2234-11e9-837e-05898a5fcd00.png)

**Comment by gyunaev** [comment]
Added the "Add multiple..." button in Monitoring dialog, which allows adding multiple files.
