### ISSUE TITLE
MATE Support

### ISSUE THREAD

**Issue by Grafini** [gyunaev/birdtray#540]
**Description**
MATE support.

**Example**
I'm using MATE on Linux Mint, and got a short error message when I tried to run BirdTray: "Sorry, system tray cannot be controlled through this add-on on your operating system." Apparently, it doesn't work with MATE, and I see on the bug report page that it has "known issues." 

Are there plans to fix this on your end? Or is there some workaround you would recommend I do to fix it? Or is there an alternative for this DE? Thank you!

**Comment by gyunaev** [comment]
No plans to fix this.

**Comment by Grafini** [comment]
Thanks. Is there some easy workaround you would recommend I do to fix it? I'm okay with it being a little glitchy, as long as it works reasonably well.

Or could you refer me to a similar program that would run on MATE? Thank you!
