### ISSUE TITLE
There is no indication of the number of new messages - Thunderbird 102

### ISSUE THREAD

**Issue by Vik-Fx** [gyunaev/birdtray#541]
**OS**: Debian - SID - 12
**Linux Desktop Manager**: Gnome 43.3
**Birdtray version**: 1.9.0 (18 sep 2022)
**Thunderbird version**: 102.7 / 102.8
**Birdtray origin**: "From package manager"

**Description**
Installed a clean Thunderbird, set up an account.
I installed Birdtray from the repository, configured monitoring and basic settings.
Birdtray works correctly, it sees folders, but there is no information about new messages.
I checked all the basic Thunderbird settings - everything is normal.

There is a workstation with previously configured Thunderbird and Birdtray, on which everything works correctly

I made a comparison of configurations, settings, options on two computers. There are syntax differences in the files .msf from Thunderbird previous versions and Thunderbird new version.

If you make a backup or transfer INBOX and INBOX.msf from the previous version of Thunderbird to Thunderbird 102, the output of the number of new messages starts working correctly.

**Comment by itzTheMeow** [comment]
I am also not getting an unread indicator with thunderbird 102.7.1
I have birdtray 1.9.0
![image](https://user-images.githubusercontent.com/50887230/220003400-15689689-5ce7-4270-934b-2c3f6ce2285b.png)


logs show its reading the file
![image](https://user-images.githubusercontent.com/50887230/220003286-45234587-3543-4aaf-b0b2-865fe0d5a8e8.png)
the email is in the file
![image](https://user-images.githubusercontent.com/50887230/220003345-0d644ac0-9eae-4a41-8bca-34681ebf6798.png)
and marked unread
![image](https://user-images.githubusercontent.com/50887230/220003375-c0060f5b-49d8-4aac-a7c7-5ed7e26ac731.png)

**Comment by Vik-Fx** [comment]
In #517, the same story is described, collected from sources, version 1.10, sees emails in new and old folders.

**Comment by therob84** [comment]
Also followed #517 and the therein [posted link](https://launchpad.net/~linuxuprising/+archive/ubuntu/apps/+packages) to the "unofficial" birdtray version 1.10 - installed DEB-Package manually over 1.9 under Linux Mint 21.1 and Thunderbird 102.11.0 it now works again without any other things have to be done other than restart birdtray. Finally it works again :-) Thanks for this crosslink!
