### ISSUE TITLE
Betterbird support

### ISSUE THREAD

**Issue by b9AcE** [gyunaev/birdtray#545]
**Description**

I am currently evaluating a switch from Thunderbird to the fork [Betterbird](https://www.betterbird.eu) on a Windows 10 (22H2) system and the only thing I miss from running Thunderbird with the still vastly superior to native birdtray, is that birdtray doesn't seem to understand that Betterbird exists.
I tried modifying the "command line" and the "window name pattern" to match the Betterbird installation, but that changed nothing.

Is this something that is supposed to be working already and I'm just not reconfiguring some component as required, or is this a new feature that would have to be implemented?
In the latter case, I am requesting that, now, here.
I suppose the "Monitoring"-tab would have to be reconfigured to the new Profiles-directory, but since the icon remains stuck at the icon for "Thunderbird is not running" I'll defer reconfiguring all of those until the running-detection is compatible.
Also, once that is done, there should not be any incompatibilities with monitoring Betterbird's profile-files rather than Thunderbird's, right?

Using Betterbird or Thunderbird, now that I know how much better than native this functionality can be handled through birdtray, is just not an option without birdtray.

**Comment by Abestanis** [comment]
Unfortunately, Birdtray is currently hardcoded to search for a process called `thunderbird.exe`, and I assume Betterbirds executable is named differently. The ability to configure this would be a new feature.

> [...] there should not be any incompatibilities with monitoring Betterbird's profile-files rather than Thunderbird's, right?

That depends on how much Betterbird is diverging from Thunderbird. But you can test this right now, the unread counter can be displayed even if the runtime-detection mechanism is not working. Just disable the `Show red X in tray icon if Thunderbird is not running` setting in the `Hiding` settings and you should see the number of unread emails.

**Comment by b9AcE** [comment]
I tested it now as you suggested @Abestanis (thank you!) and it all seems to work except that clicking birdtray's systray-icon doesn't bring up Betterbird but instead does nothing when Thunderbird is not running. This seems to be expected as long as birdtray doesn't get an ability to modify which process birdtray is looking for and toggling between hidden in systray versus brought to be made the front window.
There may of course be some other functionality I didn't think to test.
It seems to me therefore as if it would be good if another input-field was added under the "Advanced" tab of birdtray's settings-window that would allow to dynamically specify the process name that birdtray should look to interact with in the aforementioned way.

**Comment by gyunaev** [comment]
It is, you can change the binary path and the window title name in Advanced settings.

**Comment by b9AcE** [comment]
I already did set the "Thunderbird command line" to "%ProgramFiles%\Betterbird\betterbird.exe" and "Thunderbird window name pattern" to "Betterbird", but the "Hide/show Thunderbird window when it is minimized" and "Hide Thunderbird window when it is minimized" settings do not seem to act on Betterbird as it did for Thunderbird even after making those changes, @gyunaev.

**Comment by gyunaev** [comment]
What is its window title when its running?

**Comment by b9AcE** [comment]
Depending on which mail folder is selected of course, Betterbird's window title is for example "Local Folder - Betterbird", if the equivalent in Thunderbird would have been "Local Folders - Mozilla Thunderbird".

**Comment by Abestanis** [comment]
The window name is ignored when running on Windows, only the executable name matters:
https://github.com/gyunaev/birdtray/blob/ce3a29fe1a159fe0429f51ea0ea4783a75e1d290/src/windowtools_win.cpp#L99

**Comment by b9AcE** [comment]
I did change both those fields, as detailed previously and I also double-checked that there wasn't a typo by giving the same path via copy/paste to "dir" in a command-line window and "dir" found the executable file.
Still birdtray doesn't do the hide/show for Betterbird with those settings, but keeps doing it for Thunderbird with those same settings. I did restart birdtray and Betterbird (and started Thunderbird which is not normally not running) for that test.

**Comment by Abestanis** [comment]
@b9AcE would you be able to compile and test if the changes in #546 work for you?

**Comment by b9AcE** [comment]
Unfortunately @Abestanis, I don't have a suitable Windows compiling environment and with my becoming visually impaired a couple of years ago I think probably setting one up could overwhelm my current capacity.
I will be hoping for a new official precompiled installer though.
Thank you!

**Comment by b9AcE** [comment]
After checking with VirusTotal, Jotti's equivalent and some more, I decided to try your release @Abestanis.
After install I just went to the "Advanced" tab and changed the content of the field "Thunderbird process name" to "betterbird.exe" and it seems to work exactly as desired with Betterbird, as birdtray worked with Thunderbird previously.
This seems to me to be confirmed working well.
Thank you!

**Comment by Abestanis** [comment]
Awesome, thank you for the feedback! I'm glad it works.
