### ISSUE TITLE
One request

### ISSUE THREAD

**Issue by Chandra1963** [gyunaev/birdtray#55]
Thank you for birdtray, you saved me  :)
I propose one change: if I select an image for email unread I would like to have possibility in the next panel NOT have a color for new unread email (only my image selected in previous panel)....

**Comment by gyunaev** [comment]
Settings -> General -> [X] Show unread count -> uncheck?

**Comment by Chandra1963** [comment]
I don't have this option .....

**Comment by gyunaev** [comment]
Please build from the latest source.

**Comment by Chandra1963** [comment]
I have 1.4-1 bionic ...

**Comment by gyunaev** [comment]
I do not know what "1.4-1 bionic" means, as I do not build any packages.

**Comment by Chandra1963** [comment]
OK,
I find this ...
http://ppa.launchpad.net/linuxuprising/apps/ubuntu/pool/main/b/birdtray/

and I installed the last bionic release .......
