### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by madhums** [gyunaev/birdtray#554]
**OS**: 6.2.0-10018-tuxedo OS (using kde plasma on top of ubuntu), x86_64 GNU/Linux
**Linux Desktop Manager**: KDE
**Birdtray version**: 
**Thunderbird version**: 1.9.0
**Birdtray origin**: Flatpak
**Qt version**: _NA_

**Description**
I start birdtray and I open Thunderbird. When I start birdtray it asks for the profile folder, I select `~/.thunderbird` folder but it says no profile found - even though the profile lies in this directory. Nothing really happens when I click on the tray icon. This software does not seem to be working (also looks like the 1.9.0 version hasn't been updated for the last 3 years!)

**Expected behavior**
Expect the tray icon to minimise thunderbird when clicked on tray icon.

**Comment by margual56** [comment]
> Birdtray origin: Flatpak

Have you given the flatpak permission to access that folder? By default, access to the home folder is restricted.

> Expected behavior
Expect the tray icon to minimise thunderbird when clicked on tray icon.

If you are using Wayland, this might be related to issue #426

**Comment by madhums** [comment]
I think giving those permissions fixed it.
