### ISSUE TITLE
Activate/show Thunderbird on click

### ISSUE THREAD

**Issue by lefou** [gyunaev/birdtray#559]
**Description**

I'd like to activate the already open Thunderbird window on a click on the tray.

I use a desktop with multiple virtual workspaces, and Thunderbird is always on a specific one. If I click on the tray icon, I'd like to activate the Thunderbird windows and make it the active application, switching the workspace if necessary (the window manager will do this automatically when we activate the window).

The already existing option to show/hide the Thunderbird window is providing a different experience.
If I click on it, it is minimizing the Thunderbird window (on a different workspace). A second click on the tray will show it again, but also make it show up on the current workspace.

**Example**

The user sees that new emails are present, clicks on the tray and jumps right to the Thunderbird windows. It the window is already shown, it will just be made the active window, if it is hidden, it will be re-shown, and if it is shown on a different virtual workspace/desktop, it will be activated (the window manager will switch to that desktop).

**Comment by gyunaev** [comment]
I don't think this is even possible without making it WM-specific.

**Comment by lefou** [comment]
Fair enough. What about executing an external command on click on the tray icon? That the user can run whatever will make the WM do the appropriate action.

**Comment by gyunaev** [comment]
This could be done - you're welcome to submit a PR.

**Comment by lefou** [comment]
See #575
