### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by Chandra1963** [gyunaev/birdtray#56]
If birdtray automatically start  at the start of kubuntu (I see the icon on the panel with one green sign), birdtray don't work ... If I start manually birdtray after kubuntu start, birdtray work ok (and the icon don't have the green sign)

This is my configuration .....
Linux/KDE Plasma: kubuntu 18.04
KDE Plasma Version: 5.12.7
KDE Frameworks Version: 5.47.0
Qt Version: 5.9.5

**Comment by gyunaev** [comment]
What does "don't work" mean? Please be more specific.

**Comment by Chandra1963** [comment]
If I have a new email, icon don't change ....

**Comment by gyunaev** [comment]
Add a delay into birdtray autostart script, would it help?

**Comment by Chandra1963** [comment]
Yessssss ....
I created one autostart script with a delay and now it's ok ! Thank you  .....
ps: I bother you for #55 ....

**Comment by zluca** [comment]
When a add into autostart script command `cd /home/myname` it starts working. Maybe it helps.

**Comment by gyunaev** [comment]
Similar to #57
