### ISSUE TITLE
precompiled installers for the latest release is missing

### ISSUE THREAD

**Issue by locke45** [gyunaev/birdtray#560]
It is recommended for Windows users to use the [precompiled installers for the latest release](https://github.com/gyunaev/birdtray/releases/latest). 

The Installer is missing for 1.11.0

**Comment by Abestanis** [comment]
Our automated tasks creating the installers seem to be broken, I'm looking into it.

**Comment by aralozkaya** [comment]
> It is recommended for Windows users to use the [precompiled installers for the latest release](https://github.com/gyunaev/birdtray/releases/latest).
> 
> The Installer is missing for 1.11.0

As a temporary workaround, you can compile from source. But for some reason you have to comment or remove lines 7 and 8 from installer/Utils.nsh
