### ISSUE TITLE
Manual update check failed cause of SSL error

### ISSUE THREAD

**Issue by JoGrob** [gyunaev/birdtray#566]
**OS**: Windows 11 x64
**Linux Desktop Manager**: n/a
**Birdtray version**: 1.1.13 x64
**Thunderbird version**: don't care
**Birdtray origin**: From installer
**Qt version**: _NA_ 

**Description**

Go to Settings/Advanced an trigger an manual update check by clicking "Check now"
Error Message "Version check failed... No ssl..." appeared

**Expected behavior**

Manual update check should work.

**To Reproduce**

1.  go to Settings/Advanced 
2.  click "Check now"
Error Message "Version check failed... No ssl..." appeared

**Screenshots**

![Screenshot 2023-09-01](https://github.com/gyunaev/birdtray/assets/59739587/5bbab457-0116-4b15-9e5a-bfc122c74b9c)

**Comment by Abestanis** [comment]
Thank you for reporting this. For anybody affected by this, unfortunately you will have to manually update to the latest version by downloading it from [here](https://github.com/gyunaev/birdtray/releases), since this breaks the automatic update of Birdtray.
