### ISSUE TITLE
BirdTray does not auto-start on Ubuntu 18.04.2

### ISSUE THREAD

**Issue by tryfon** [gyunaev/birdtray#57]
Hello,
I am running Ubuntu 18.04.2 and birdtray works fine except from the fact that it does not auto-start when I login in my user session. I have tried to configure it both through the default Ubuntu app 'Startup Applications' as well as from the 'Gnome Tweaks' app (section Startup Applications) to no avail. Any recommendations/workarounds?

**Comment by MartyMcByte** [comment]
Hi,
I can confirm the behavior
My system is:
Debian 9 stretch
Cinnamon 4.0.9

**Comment by ikn** [comment]
Same here; turns out it segfaults.  Attaching a coredump (though probably not too useful since it's not a debug build) (renamed it to .txt to make GitHub happy for some reason).

[dump.xz.txt](https://github.com/gyunaev/birdtray/files/3000317/dump.xz.txt)

**Comment by Abestanis** [comment]
After looking at the dump file, it seems that birdtray did not segfault but abort.
I have the suspicion, that birdtray starts before the desktop is ready, which causes it to believe that the system tray is not supported on the platform and leads to the abort.
Unfortunately, I don't have a PC with Linux installed, so I can't test it myself.
@ikn Could you compile birdtray from [this branch](https://github.com/Abestanis/birdtray/tree/feature/abortDialog), replace it with the current birdtray installation on your system and remove the 2 second delay on the autostart entry? If my theory is correct, birdtray should display an error dialog when you log in.

**Comment by ikn** [comment]
Yeah, I see an error dialogue.

**Comment by jgieseler** [comment]
I came here searching for a solution to the same problem. I found a workaround somewhere else, so I just want to mention it here. It seems (for me) the problem is that BirdTray is started to fast so that some system stuff is not ready yet. The solution is to postpone the autostart a bit.

So, in 'Startup Applications' put the following into the 'Command' field:

`sh -c "sleep 30; /usr/bin/birdtray"`

(sh -c " " is needed to enter two commands, i.e., sleep and birdtray. Perhaps you have to adjust the path of birdtray.)

**Comment by Abestanis** [comment]
@jgieseler Which version of Birdtray are you using and on which Operating System? Birdtray is supposed to wait up to 60 seconds for the Desktop, so the sleep shouldn't be needed. Support for this was added in `1.6`.

**Comment by jgieseler** [comment]
> @jgieseler Which version of Birdtray are you using and on which Operating System? Birdtray is supposed to wait up to 60 seconds for the Desktop, so the sleep shouldn't be needed. Support for this was added in `1.6`.

@Abestanis 
Birdtray version 1.8.0 compiled at Apr 21 2020 09:21:36. 
Ubuntu 18.04.4 LTS (GNOME 3.28.2)

The only corresponding setting I can find is "Start Thunderbird when Birdtray starts *with a X second delay*". There is no option to autostart **Birdtray** at all.

**Comment by Abestanis** [comment]
Birdtray does not have an option to automatically setup autostarting on Linux machines, but if you set up the autostart via some other mechanism, Birdtray should always wait up to 60 seconds for the Desktop to become available before displaying the `Sorry, system tray cannot be controlled through this add-on on your operating system.` message.
If that is not what is happening for you, please open a new issue and we can take a look at it.

**Comment by jgieseler** [comment]
Well, as I wrote, I found a workaround. As for me, the situation is fine. However, if you as a collaborator would like me to open a new issue, I could do that. But I would only do it to help bugfixing, not for me. :-)

**Comment by Abestanis** [comment]
Yes, please open a issue and please include information on how you set up the auto start and Birdtrays log, if you have the time. Thanks 😃
Birdtray is supposed to wait, if that doesn't work I would consider it a bug. Let's see if we can fix it so other users must not need to google for the solution.
