### ISSUE TITLE
Flatpak version for the latest release (v1.11.4)

### ISSUE THREAD

**Issue by maniadevice** [gyunaev/birdtray#574]
Apologies if this is not the right place to request this. But would it be possible to get Flatpak version of the latest release onto Flathub? Many thanks.

**Comment by Abestanis** [comment]
We don't maintain the Flatpak version ourselves, so we can't make a new release unfortunately. But you can request it [on their Github Repository](https://github.com/flathub/com.ulduzsoft.Birdtray).

**Comment by maniadevice** [comment]
@Abestanis Okay, thank you. I have left a comment here https://github.com/flathub/com.ulduzsoft.Birdtray/issues/6#issuecomment-1751532490
