### ISSUE TITLE
Flatpak version appears outdated (1.9.0)

### ISSUE THREAD

**Issue by MMachado05** [gyunaev/birdtray#576]
**Description**

I'm unfamiliar with how to download and install tarball applications, and I love the convenience of the Flatpak packaging system. However, the version available on Flathub was last updated 3 years ago, and whereas the most recent release here on Github was 1.11.x, the newest there is 1.9.0. It would be great if this were updated to the current available version!

If the official flatpak for Birdtray is being hosted outside of Flathub, I'll be sure to close this issue.

**Example**

N/A

A note: when Thunderbird is closed, it does not notify me of new emails, nor does it appear to update the new emails (I see them appear a second or two after starting Thunderbird). Will this application notify me on new emails even if the Thunderbird flatpak is not open?

**Comment by stefan6419846** [comment]
See #574 - the Flatpak version is managed in a separate repository (https://github.com/flathub/com.ulduzsoft.Birdtray) by @ThanosApostolou.

**Comment by Abestanis** [comment]
> Will this application notify me on new emails even if the Thunderbird flatpak is not open?

No, Birdtray relies on Thunderbird to fetch mails, so Thunderbird needs to be running to receive new mails. That's why Birdtray has the option to hide the Thunderbird window, so it can be running in the background without taking up space in the task bar.

**Comment by gyunaev** [comment]
Flatpak is not built by this project.
