### ISSUE TITLE
How to properly uninstall Birdtray on Ubuntu 22.04 if it has been installed from source?

### ISSUE THREAD

**Issue by ricciolino** [gyunaev/birdtray#581]
Could you please provide step-by-step commands to properly uninstall Birdtray on Ubuntu 22.04 if it has been installed from source?

**Comment by bonelifer** [comment]
If you followed the install directions and used this command to install it:
cmake --build . --target install

it should be here:
/usr/local/bin/birdtray

so run this command (may need sudo):
rm /usr/local/bin/birdtray

you can also use this command to find it if you install it in a different directory:
which birdtray

**Comment by ricciolino** [comment]
so this file ` /usr/local/bin/birdtray` is all that comes out of the cloned repository after the installation command?
No other traces ?

**Comment by lsteeger** [comment]
The following **may** exist _YMMV_ (your mileage may vary):

/usr/bin/birdtray
/usr/share/applications/com.ulduzsoft.Birdtray.desktop
/usr/share/doc/birdtray/README.md
/usr/share/icons/hicolor/128x128/apps/com.ulduzsoft.Birdtray.png
/usr/share/icons/hicolor/32x32/apps/com.ulduzsoft.Birdtray.png
/usr/share/icons/hicolor/48x48/apps/com.ulduzsoft.Birdtray.png
/usr/share/icons/hicolor/64x64/apps/com.ulduzsoft.Birdtray.png
/usr/share/icons/hicolor/scalable/apps/com.ulduzsoft.Birdtray.svg
/usr/share/metainfo/com.ulduzsoft.Birdtray.appdata.xml
/usr/share/ulduzsoft/birdtray/
/usr/share/ulduzsoft/birdtray/translations/
/usr/share/ulduzsoft/birdtray/translations/dynamic_cs.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_de.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_el.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_en.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_es.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_fr.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_it.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_nl.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_pl.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_pt.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_ru.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_sv.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_tr.qm
/usr/share/ulduzsoft/birdtray/translations/dynamic_zh_cn.qm
/usr/share/ulduzsoft/birdtray/translations/main_cs.qm
/usr/share/ulduzsoft/birdtray/translations/main_de.qm
/usr/share/ulduzsoft/birdtray/translations/main_el.qm
/usr/share/ulduzsoft/birdtray/translations/main_en.qm
/usr/share/ulduzsoft/birdtray/translations/main_es.qm
/usr/share/ulduzsoft/birdtray/translations/main_fr.qm
/usr/share/ulduzsoft/birdtray/translations/main_it.qm
/usr/share/ulduzsoft/birdtray/translations/main_nl.qm
/usr/share/ulduzsoft/birdtray/translations/main_pl.qm
/usr/share/ulduzsoft/birdtray/translations/main_pt.qm
/usr/share/ulduzsoft/birdtray/translations/main_ru.qm
/usr/share/ulduzsoft/birdtray/translations/main_sv.qm
/usr/share/ulduzsoft/birdtray/translations/main_tr.qm
/usr/share/ulduzsoft/birdtray/translations/main_zh_cn.qm

**Comment by bonelifer** [comment]
This is what I found using the Makefile and search on my system(xubuntu 22.04):

FILE:
/usr/local/share/applications/com.ulduzsoft.Birdtray.desktop

FILE:
/usr/local/share/metainfo/com.ulduzsoft.Birdtray.appdata.xml

This file:
com.ulduzsoft.Birdtray.png
under this folder in the various size folders for these size(32 48 64 128):
/usr/local/share/icons/hicolor/


FILE:
/usr/local/share/icons/hicolor/scalable/apps/com.ulduzsoft.Birdtray.svg)

FOLDER for translations: /usr/local/share/ulduzsoft/birdtray/

**Comment by ricciolino** [comment]
Thanks for your help guys :)
