### ISSUE TITLE
Open Thunderbird on specific display 

### ISSUE THREAD

**Issue by aindriu80** [gyunaev/birdtray#582]
**Description**

I'm running Pop_OS 22.04 (Wayland) and I have Birdtray scheduled to start up 5 seconds after I log in.  My setup includes two identical monitors.  Currently, Birdtray starts Thunderbird up where the mouse cursor is however I would like Thunderbird always to open on a specific display every time it's opened.  Is this feature possible? 

**Example**

Pop_OS can detect the two displays, is it possible to set a preference in Birdtray to always open Thunderbird on specific such display 1 or display 2?

![2023-12-10_14-35](https://github.com/gyunaev/birdtray/assets/8885837/e0e7b2c8-1a56-49b8-a36b-08f42c4478e2)

Thanks for your time

**Comment by gyunaev** [comment]
Wayland is currently not supported.

**Comment by aindriu80** [comment]
You can use Wayland while starting thunderbird with X11.

`/usr/bin/env GDK_BACKEND=x11 /usr/bin/thunderbird`

**Comment by gyunaev** [comment]
Yes, you can - but it's not supported, so any issues you'd encounter would be on you.
