### ISSUE TITLE
Quit Birdtray when Thunderbird is closed

### ISSUE THREAD

**Issue by Tommimon** [gyunaev/birdtray#583]
**Description**

Currently if you close Thunderbird all you can do is displaying a red cross over the Birdtray icon.
I would like Birdtray to close instead.
In my opinion this should be an option in the settings `Hiding` tab, but I could not find something like this in the settings.

**Reason**

The reason for this is that I don't always keep Thunderbird running in the background, when I want to do it I use `Hide Thunderbird`, but in any other case, I close Thunderbird when I'm done and I would like Birdtray to do the same automatically.

**Example**

1) I click close button in Thunderbird
2) Thunderbird closes
3) Birdtray detects it and closes as well

**Comment by knakamura8** [comment]
I am experiencing a similar issue.  When I close BT, TB reappears in my taskbar, and then I have to Ctrl + Shift + Q exit TB.  This is when BT has the quit TB after closing BT functionality enabled in Windows 10.
