### ISSUE TITLE
Thunderbird does not close when Birdtray is closed, even though exit Thunderbird on Quit selected

### ISSUE THREAD

**Issue by knakamura8** [gyunaev/birdtray#585]
**OS**: Win10 x64
**Birdtray version**: v.1.11.4
**Thunderbird version**: 115.6.0
**Birdtray origin**: from installer, user install

**Description**
Select option to exit TB on BT quit is checked.  Instead, when closing BT, TB window re-opens, and the user has to to Ctrl + Shift + Q or quit from hamburger menu.  This also occurs when TB is hidden.  I have no extensions installed in TB.

**Expected behavior**
When quitting BT, TB should also close.

**To Reproduce**
Have BT in tray, with TB closed to tray.  Right click BT and Quit BT.  The main TB window will open after this, after which the user has to close TB.

I spawn TB via BT in the first place, so I am not opening TB directly at any stage in this process.  Essentially #230 but in Win10 x64

**Comment by Abestanis** [comment]
Hm, I'm having trouble reproducing this. For me, no matter what I do, Thunderbird always quickly pops up and then closes after closing Birdtray. Would it be possible for your settings in the `Hiding` and `Advanced` tabs? Maybe there is a difference to my setup.

Another possibility is that Thunderbird may not be reacting to the quit event Birdtray is sending to it. If you just have Thunderbird running without Birdtray, does it close when you execute `taskkill /IM thunderbird.exe` in a terminal?

**Comment by knakamura8** [comment]
It was a permissions error, that your `taskkill /IM thunderbird.exe` suggestion helped me diagnose!  Thank you!  Works now.
