### ISSUE TITLE
Tray icon displays incorrectly on plasma 6 wayland 

### ISSUE THREAD

**Issue by mingti** [gyunaev/birdtray#590]
**OS**: arch
**Linux Desktop Manager**: kde plasma 6 wayland
**Birdtray version**: birdtray 1.11.4
**Birdtray origin**: aur

**Description**
Tray icon displays incorrectly on plasma 6 wayland , I've run Thunderbird, but it display not running. It's right on x11.

**Screenshots**

![image](https://github.com/gyunaev/birdtray/assets/24843766/c55b5981-ab97-460d-af20-c633dbc9a411)

**Comment by SalvatoreNoschese** [comment]
Tried just today in arch with plasma 6. Do not work as expected. Hope can be fixed.

**Comment by gyunaev** [comment]
https://github.com/gyunaev/birdtray/issues/426
