### ISSUE TITLE
Birdtray doesn't work in Fedora 40 (KDE-Wayland-64 bit)

### ISSUE THREAD

**Issue by linkq-des** [gyunaev/birdtray#596]
**OS:** Operating System: Fedora Linux 40 (64-bit)
**Linux Desktop Manager**: KDE Plasma Version: 6.1.2
                                                      KDE Frameworks Version: 6.3.0
                                                      Qt Version: 6.7.2
                                                      Kernel Version: 6.9.8-200.fc40.x86_64 (64-bit)
                                                      Graphics Platform: Wayland
**Birdtray version**: 1.11.4
**Thunderbird version**: 128.0esr (64-bit)
**Birdtray origin**: From package manager: Discover (Flatpack).
**Qt version**: _NA_ 
**Description**
Birdtray does not detect Thunderbird
**Expected behavior**
Birdtray must be managing Thunderbird
**To Reproduce**
1. SO start
2. Birdtray does not detect Thunderbird
3. Thunderbird acting independently from Birdtray
4.  When the tray accesses or closes Thunderbird, Birdtray fails (see image -ES-)
**Screenshots**
![image](https://github.com/user-attachments/assets/b35e9450-bd53-4b4a-92f3-d16c9a75c638)

**Comment by gyunaev** [comment]
See #426

**Comment by linkq-des** [comment]
Do you not provide the flatpack? Who does it? You are identified as a provider in the package manager, and the link goes directly to your GitHub.
Additionally, I do not see any package or procedure for installing the app in Fedora on your GitHub. Also, the previous version worked smoothly (I do not see those on your GitHub).

**Comment by gyunaev** [comment]
I do not provide the flatpack, and have no idea who does it. And yes, there is no package because nobody built it, and there's no procedure because nobody wrote it. This is free software. I suggest you check your demands accordingly.
