### ISSUE TITLE
Compilation Error Qt5Svg/Qt6Svg

### ISSUE THREAD

**Issue by Handrail9** [gyunaev/birdtray#599]
**OS**: Fedora 40 KDE Spin

**Birdtray version**:  v1.11.4 and Master Branch
**Birdtray origin**: From Source
**Qt version**:  QMake version 3.1
Using Qt version 6.7.2 in /usr/lib64

**Description**
Running cmake -DCMAKE_BUILD_TYPE=Release .. from the most recent master branch and v1.11.4 throws this error. Difference between the two being Qt5 v Qt6.
```
CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a package configuration file provided by "Qt6Svg" with any
  of the following names:

    Qt6SvgConfig.cmake
    qt6svg-config.cmake

  Add the installation prefix of "Qt6Svg" to CMAKE_PREFIX_PATH or set
  "Qt6Svg_DIR" to a directory containing one of the above files.  If "Qt6Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Expected behavior**
Compiles

**To Reproduce**
Git clone or download the latest release and run 
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
```
**Additional context**
Running `sudo dnf install qt6-qtsvg qt5-qtsvg` does not solve the issue.

**Comment by gyunaev** [comment]
You need a devel package for qt6-qtsvg. No idea what's the name on Fedora. On OpenSuSE it's named `qt6-svg-devel`

**Comment by Handrail9** [comment]
> You need a devel package for qt6-qtsvg. No idea what's the name on Fedora. On OpenSuSE it's named `qt6-svg-devel`

I am so sorry for wasting your time. I genuinely feel stupid not having realized that myself LOL
