### ISSUE TITLE
Crash after changing settings

### ISSUE THREAD

**Issue by AGCaesar** [gyunaev/birdtray#6]
First of all, thanks for your work! I missed this type of addon so much!

But now for the problem:
Every time I change some settings, eben if I just open the settings dialog and press cancel, birdtray crashes.
caesar@arch ~ % birdtray 
Color for ID 2: #ff0000
Color for ID 24: #ff0000
Color for ID 32: #ff0000
Color for ID 34: #ff0000
List of all IDs: 2,24,32,34
unreadCounterUpdate 1
Window ID found: 0
Window ID found: 58720272
QProcess: Destroyed while process ("/usr/bin/thunderbird") is still running.

I am on the latest build and use arch with the awesomewm windows manager

**Comment by gyunaev** [comment]
Can you please run it under gdb, such as:

```
gdb src/birdtray
r
```

and provide the crash stack dump?

**Comment by gyunaev** [comment]
It doesn't seem to be crashing.

**Comment by gyunaev** [comment]
[Inferior 1 (process 23553) exited normally] - apparently it just exits. And I have no idea why. Does anyone else experience this?

**Comment by JackDinn** [comment]
nop, never seen this happen. looks like one of them PITA bugs that you would have to track down via debugging on that system with a process of elimination. Wish i could help.

**Comment by AGCaesar** [comment]
I tried it on another machine, also arch+awesomewm, same problem. The initial configuration works great, after that it closes whenecer I cange anything or click Cancle... Maybe some missing dependency on my side? I am really confused. Otherwise it works great!

**Comment by JackDinn** [comment]
dont know if relevant but im just testing on gnome and im seeing it crash/close after hitting OK or Close on the settings. Might just be something completely different but this is a clean install on a VM of manjaro gnome.

```
[greg@greg-pc src]$ ./birdtray 
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: yes
Color for ID 2: #00ff00
List of all IDs: 2
unreadCounterUpdate 3
Window ID found: 3800010
libGL error: pci id for fd 17: 80ee:beef, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)

```

**Comment by gyunaev** [comment]
This one helped. I fixed it now.

**Comment by JackDinn** [comment]
ahh, thats great news, really glad i could be a tiny bit of help even if you do the heavy lifting , cheers.

**Comment by AGCaesar** [comment]
Fixed it here too! Great work again! Sorry I couldn't be more help.

**Comment by gyunaev** [comment]
Cool, thanks for confirming!
