### ISSUE TITLE
Fails to launch in Ubuntu 18.04.2

### ISSUE THREAD

**Issue by tryfon** [gyunaev/birdtray#60]
System info:
Fresh installation of Ubuntu 18.04.2 
birdtray/bionic,now 1.5-1~bionic0 amd64 [installed]

When launching it throws:
birdtray: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory

My relevant installed libraries:
sudo apt list --installed | grep -i libqt5

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libqt5core5a/bionic,now 5.9.5+dfsg-0ubuntu1 amd64 [installed]
libqt5dbus5/bionic,now 5.9.5+dfsg-0ubuntu1 amd64 [installed]
libqt5gui5/bionic,now 5.9.5+dfsg-0ubuntu1 amd64 [installed]
libqt5network5/bionic,now 5.9.5+dfsg-0ubuntu1 amd64 [installed]
libqt5svg5/bionic,now 5.9.5-0ubuntu1 amd64 [installed]
libqt5widgets5/bionic,now 5.9.5+dfsg-0ubuntu1 amd64 [installed]
libqt5x11extras5/bionic,now 5.9.5-0ubuntu1 amd64 [installed,automatic]

**Comment by gyunaev** [comment]
It seems like you do not have the correct libraries installed. Unless you have built the app from the source, please address the questions to the package maintainer.

**Comment by tryfon** [comment]
I have installed the app through this ppa:
https://www.linuxuprising.com/2018/10/birdtray-thunderbird-tray-icon-with-new.html

**Comment by gyunaev** [comment]
I do not create/maintain this PPA, so you should ask from the person who is maintaining it.
