### ISSUE TITLE
Can you reduce Qt requirements to version from the official repo?

### ISSUE THREAD

**Issue by VijitCoder** [gyunaev/birdtray#602]
Your requirements:
> Qt 6.2 or higher

At the same time, in the fresh KUbuntu 24.04, that released a few days ago:
```sh
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.1 LTS"

$  qmake --version
QMake version 3.1
Using Qt version 5.15.13 in /usr/lib/x86_64-linux-gnu
```

So, if I want to compile your tiny program, I need to update Qt library (which is hardly used by KDE in my KUbuntu) from some 3rd party repo. It's look like overhead, no?

**Comment by gyunaev** [comment]
The latest release still support Qt5. Qt6 support is only in current HEAD.

And nobody forces you to compile "my tiny program" nor to incur any overhead while doing it.

**Comment by VijitCoder** [comment]
> The latest release still support Qt5

Greate, thx.
