### ISSUE TITLE
need help installing birdtray on windows please.

### ISSUE THREAD

**Issue by taktakmeian** [gyunaev/birdtray#85]
As I understand it is compatible with windows but I have no idea how to interpret the instructions to install it and I'd like a bit of help with this.

thanks in advance

**Comment by Abestanis** [comment]
Hello, unfortunately, there is no release with an installer for windows yet.
It is possible to create the installer by yourself, but that can be a complicated endeavour.
If you can wait a bit, the next release (which you can find [here](https://github.com/gyunaev/birdtray/releases)) will probably contain the installer for Windows.

If you don't want to wait and you have experience working with Travis, you could take a look at the [Travis file](https://github.com/gyunaev/birdtray/blob/master/.travis.yml). If you can read it, you could extract the steps necessary to build the installer from there.

If the Travis file doesn't help you and you don't want to wait for a new release of birdtray, I could try to write a step by step description on how to install birdtray on windows.

**Comment by taktakmeian** [comment]
Thanks for the answers, I can wait a bit, but if you think it'l be more than a month I could use a step to step whenever you have the time to write one :)

**Comment by gyunaev** [comment]
I will make a release this week. Stay tuned.

**Comment by taktakmeian** [comment]
that's great to hear !

**Comment by Abestanis** [comment]
@taktakmeian The release is [online now](https://github.com/gyunaev/birdtray/releases/tag/RELEASE_1.6). Are you able to install Birdtray with the installer?
