### ISSUE TITLE
Chance config directory to .birdtray

### ISSUE THREAD

**Issue by AGCaesar** [gyunaev/birdtray#9]
I wanted to take a look at the config file and found in in /home/USER/.config/ulduzsoft/birdtray.conf
I think /home/USER/.config/birdtray/birdtray.conf is much more intuitive and saves time when looking for the config file

**Comment by gyunaev** [comment]
This is where Qt stores settings, which are stored according to XDG specification rules. Configuration files are supposed to be stored in .config/<organization>/application.conf - I agree this looks strange, but even crappy rules are better than no rules.

**Comment by AGCaesar** [comment]
I understand the .config/ulduzsoft/application.config part
But is ulduzsoft the name of the software you want to use? Does /home/USER/.config/birdtray/birdtray.conf not follow the XDG specification rules?

**Comment by Chadsr** [comment]
Adding to this, as I was confused by the directory name ulduzsoft. It would be much more user friendly, in my opinion, if the configuration directory was named birdtray (e.g. `.config/birdtray`).

Hugely grateful for this tool!

**Comment by gyunaev** [comment]
Too late now. This would mean all existing users would lose their current configuration.

**Comment by Chadsr** [comment]
Would it not be easy to implement a check for that directory and if found, it gets renamed to birdtray? I'm not familiar with the codebase so maybe this seems easier said than done.

Thanks again.

**Comment by gyunaev** [comment]
No, this won't be easy as I'm not setting those directories directly. Nor that "much more intuitive"  worth the change anyway.

**Comment by Chadsr** [comment]
Understandable. Would be great to have a note in the readme indicating where the config is saved, maybe. Just to avoid users getting confused looking for it like I did.

I would be happy to PR this if you agree.

**Comment by gyunaev** [comment]
Please do.
