### ISSUE TITLE
Unread counter not updating

### ISSUE THREAD

**Issue by RoelerCoaster** [gyunaev/birdtray#95]
**OS:** Windows 10 1903
**Birdtray version**: 1.6.1 x64
**Thunderbird version**: 60.7.1 (32-bit)

I have set up birdtray to use the Mork parser. If I mark a message in my inbox unread, the tray icon does not change. However, if I open and close the settings window the icon _does_ update and shows the correct count.

Similarly, if I now mark the message as read, the icon only updates after opening and closing the settings panel.

I have tried using the global search database option as well, but that just gives me a red X through the icon.

**Comment by Abestanis** [comment]
First of all, thank you for the detailed report, especially including the OS and version information. 👍

I can confirm the problem and from what I can see, the issue issue is caused by Thunderbird not flushing the new data to the `.msf`-files, causing our FileSystemNotifier not to trigger.
I'll keep searching for a solution, but worst case, we'll have to read the `.msf`-files once every minute or so.
@gyunaev Do you have any ideas?

**Comment by gyunaev** [comment]
Must be Windows-specific issue, as it works fine on Linux. But then, how would rereading MSF files help if the issue is that the changes are not flushed there?

**Comment by gyunaev** [comment]
Ultimately, I guess, we'd have to write a TB plugin which receives those notifications directly from TB, and sends them out for Birdtray to read.

**Comment by RoelerCoaster** [comment]
Are the changes really not flushed? Because opening and closing the settings window seems to force a re-read and updates the counter correctly.

**Comment by Abestanis** [comment]
Yes, I was just about to mention that. When manually triggering an via the setting Birdtray will be able to read the updated value. I will investigate this further.

**Comment by baconsalad** [comment]
I'm on Linux and I see this same thing happening. When I open up the settings and click ok it will then again have the correct unread count. 

I have a ton of mail filters that will move messages around, mark them as read etc. Wild guess but that might be screwing it up.

**Comment by pablo-blueoakdb** [comment]
I'm on Linux/TBird 68.1.2/Tumbleweed w/Birdtray version 1.6.0 compiled at Oct 20 2019 16:43:46.

I see the same behavior (open/close birdtray resets counts).

Can I compile birdtray with any debug to help troubleshoot the problem?  Just say the word.  

Thx!

**Comment by Hobbix** [comment]
I confirm this problem. Unfortunately, the application does not work on Windows. It can only be used to minimize the system tray.
The counter is updated only in two cases: 
1) restart Thunderbird,
2) re-save settings.

Please fix this problem. Many people are really looking forward to this. Unfortunately, the FireTray add-on stopped working on Thunderbird 68+ and there is no alternative to it anymore.

OS: Windows 7
Birdtray version: 1.7.0
Thunderbird version: 68.3.1 (32-bit)

**Comment by ampped101** [comment]
As a workaround I have set TB to reopen when it closes. I allow Birdtray to reopen it and this resets the count.

**Comment by tsdg112** [comment]
I have the same issue on Windows.  I have a workaround that works for me: compacting the folder causes birdtray to update the unread message count.   I've installed the xpunge add-on, which allows me to do this with one click.

**Comment by gyunaev** [comment]
I have added an Advanced tab setting which allows you to force rereading indexes every N seconds.

**Comment by Abestanis** [comment]
That is a good short term solution, but we should investigate if we can get the file notifiers to work.

**Comment by GerhardPehland** [comment]
Having the same issue here (version 1.8.0 under Windows).

I have set the option to recheck the index file every 15 seconds, yet the unread counter is not updated properly.

One observation though: if a new email arrives, the counter goes to 1, if I DELETE the new email, the counter is properly reset to zero. If I just READ the new email and keep it, the counter incorrectly stays at 1.

Maybe that helps.

**Comment by GerhardPehland** [comment]
Addendum: it seems, when I delete ANY email, the counter is updated to it's proper value.

**Comment by pablo-blueoakdb** [comment]
Hi,
I've written a simple shell wrapper to _eventually_ fix the unread count.  It restarts birdtray every 15 minutes.

Remove .txt from the end of the file and chmod +x:

[Run_birdtray.txt](https://github.com/gyunaev/birdtray/files/4545606/Run_birdtray.txt)

**Comment by Abestanis** [comment]
> I have set the option to recheck the index file every 15 seconds, yet the unread counter is not updated properly.

This is a known bug and will be fixed in the upcoming `1.8.1` release.

**Comment by GerhardPehland** [comment]
Just got 1.8.1 for Windows and it seems to be fixed indeed.

Thank you!
