### ISSUE TITLE
Only show systray icon if there are new messages

### ISSUE THREAD

**Issue by goodwillcoding** [gyunaev/birdtray#96]
Thank you for birdtray. I was wondering if showing icon only if there are new messages is anywhere on the roadmap

**Comment by gyunaev** [comment]
But since Birdtray itself has no window, how would you change this setting (or any other) if there is no email message?

**Comment by Abestanis** [comment]
How about this:
If you start another birdtray instance, it will first check if there is an instance already running. If so, it would signal the running instance to open the settings dialog and the new instance will exit.

**Comment by gyunaev** [comment]
Possible, but not very user-friendly. Let me think.

**Comment by Abestanis** [comment]
Do we want to implement this now? The system to send a command to the running Birdtray instance is now in place.

**Comment by gyunaev** [comment]
Yes, could be implemented now. Please show a dialogbox when this checkbox is set letting the user know that to remove that setting without receiving an email they have to start Birdtray again which will then show the settings window.

**Comment by Abestanis** [comment]
Should we always show the settings, if another Birdtray instance is started while the first one is hidden? Or only if the second instance is started with the `--settings` command?

**Comment by GerhardPehland** [comment]
Please make this a selectable option only. I am using the tray icon to open/close Thunderbird, and I want to be able to open Thunderbird, when there are no new messages too. To write a new email for one thing...

**Comment by gyunaev** [comment]
Selectable and off by default. Probably in Advanced too.
