### ISSUE TITLE
When the system goes to screen saver mode and return the birdtray icon dissapear

### ISSUE THREAD

**Issue by hetau** [gyunaev/birdtray#97]
When the system enter in screen saver mode and system return to normal the birdtray icon dissapear from the tray.The same situation happen in other situations. In Fedora.

**Comment by Abestanis** [comment]
You might be the victim of this bug in Qt itself: https://bugreports.qt.io/browse/QTBUG-63065
Unfortunately you did not include the Qt version you used to compile Birdtray, nor your version of Fedora or your Birdtray version, so we can't really try to reproduce the issue.

Please try to recompile Birdtray with Qt version 5.9 or newer, where the bug mentioned above has supposedly been fixed. If that doesn't resolve your issue, please provide the requested information and elaborate on the `happens in other situations`, so we can help you.
